/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StorageCredentialTypeOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageCredentialTypeOneOf2{}

// StorageCredentialTypeOneOf2 GCS credential type
type StorageCredentialTypeOneOf2 struct {
	// GCS credential type
	CredentialType GcsCredentialType `json:"credential-type"`
	Type           string            `json:"type"`
}

type _StorageCredentialTypeOneOf2 StorageCredentialTypeOneOf2

// NewStorageCredentialTypeOneOf2 instantiates a new StorageCredentialTypeOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageCredentialTypeOneOf2(credentialType GcsCredentialType, type_ string) *StorageCredentialTypeOneOf2 {
	this := StorageCredentialTypeOneOf2{}
	this.CredentialType = credentialType
	this.Type = type_
	return &this
}

// NewStorageCredentialTypeOneOf2WithDefaults instantiates a new StorageCredentialTypeOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageCredentialTypeOneOf2WithDefaults() *StorageCredentialTypeOneOf2 {
	this := StorageCredentialTypeOneOf2{}
	return &this
}

// GetCredentialType returns the CredentialType field value
func (o *StorageCredentialTypeOneOf2) GetCredentialType() GcsCredentialType {
	if o == nil {
		var ret GcsCredentialType
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *StorageCredentialTypeOneOf2) GetCredentialTypeOk() (*GcsCredentialType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *StorageCredentialTypeOneOf2) SetCredentialType(v GcsCredentialType) {
	o.CredentialType = v
}

// GetType returns the Type field value
func (o *StorageCredentialTypeOneOf2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StorageCredentialTypeOneOf2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StorageCredentialTypeOneOf2) SetType(v string) {
	o.Type = v
}

func (o StorageCredentialTypeOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credential-type"] = o.CredentialType
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *StorageCredentialTypeOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credential-type",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageCredentialTypeOneOf2 := _StorageCredentialTypeOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStorageCredentialTypeOneOf2)

	if err != nil {
		return err
	}

	*o = StorageCredentialTypeOneOf2(varStorageCredentialTypeOneOf2)

	return err
}

type NullableStorageCredentialTypeOneOf2 struct {
	value *StorageCredentialTypeOneOf2
	isSet bool
}

func (v NullableStorageCredentialTypeOneOf2) Get() *StorageCredentialTypeOneOf2 {
	return v.value
}

func (v *NullableStorageCredentialTypeOneOf2) Set(val *StorageCredentialTypeOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageCredentialTypeOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageCredentialTypeOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageCredentialTypeOneOf2(val *StorageCredentialTypeOneOf2) *NullableStorageCredentialTypeOneOf2 {
	return &NullableStorageCredentialTypeOneOf2{value: val, isSet: true}
}

func (v NullableStorageCredentialTypeOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageCredentialTypeOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
