/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the S3CredentialOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3CredentialOneOf{}

// S3CredentialOneOf Authenticate to AWS using access-key and secret-key.
type S3CredentialOneOf struct {
	AccessKeyId     string  `json:"access-key-id"`
	ExternalId      *string `json:"external-id,omitempty"`
	SecretAccessKey string  `json:"secret-access-key"`
	CredentialType  string  `json:"credential-type"`
}

type _S3CredentialOneOf S3CredentialOneOf

// NewS3CredentialOneOf instantiates a new S3CredentialOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3CredentialOneOf(accessKeyId string, secretAccessKey string, credentialType string) *S3CredentialOneOf {
	this := S3CredentialOneOf{}
	this.AccessKeyId = accessKeyId
	this.SecretAccessKey = secretAccessKey
	this.CredentialType = credentialType
	return &this
}

// NewS3CredentialOneOfWithDefaults instantiates a new S3CredentialOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3CredentialOneOfWithDefaults() *S3CredentialOneOf {
	this := S3CredentialOneOf{}
	return &this
}

// GetAccessKeyId returns the AccessKeyId field value
func (o *S3CredentialOneOf) GetAccessKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKeyId
}

// GetAccessKeyIdOk returns a tuple with the AccessKeyId field value
// and a boolean to check if the value has been set.
func (o *S3CredentialOneOf) GetAccessKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessKeyId, true
}

// SetAccessKeyId sets field value
func (o *S3CredentialOneOf) SetAccessKeyId(v string) {
	o.AccessKeyId = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *S3CredentialOneOf) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3CredentialOneOf) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *S3CredentialOneOf) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *S3CredentialOneOf) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetSecretAccessKey returns the SecretAccessKey field value
func (o *S3CredentialOneOf) GetSecretAccessKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretAccessKey
}

// GetSecretAccessKeyOk returns a tuple with the SecretAccessKey field value
// and a boolean to check if the value has been set.
func (o *S3CredentialOneOf) GetSecretAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretAccessKey, true
}

// SetSecretAccessKey sets field value
func (o *S3CredentialOneOf) SetSecretAccessKey(v string) {
	o.SecretAccessKey = v
}

// GetCredentialType returns the CredentialType field value
func (o *S3CredentialOneOf) GetCredentialType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *S3CredentialOneOf) GetCredentialTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *S3CredentialOneOf) SetCredentialType(v string) {
	o.CredentialType = v
}

func (o S3CredentialOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access-key-id"] = o.AccessKeyId
	if !IsNil(o.ExternalId) {
		toSerialize["external-id"] = o.ExternalId
	}
	toSerialize["secret-access-key"] = o.SecretAccessKey
	toSerialize["credential-type"] = o.CredentialType
	return toSerialize, nil
}

func (o *S3CredentialOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access-key-id",
		"secret-access-key",
		"credential-type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varS3CredentialOneOf := _S3CredentialOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varS3CredentialOneOf)

	if err != nil {
		return err
	}

	*o = S3CredentialOneOf(varS3CredentialOneOf)

	return err
}

type NullableS3CredentialOneOf struct {
	value *S3CredentialOneOf
	isSet bool
}

func (v NullableS3CredentialOneOf) Get() *S3CredentialOneOf {
	return v.value
}

func (v *NullableS3CredentialOneOf) Set(val *S3CredentialOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableS3CredentialOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableS3CredentialOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3CredentialOneOf(val *S3CredentialOneOf) *NullableS3CredentialOneOf {
	return &NullableS3CredentialOneOf{value: val, isSet: true}
}

func (v NullableS3CredentialOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3CredentialOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
