/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// CheckOperation - Represents an action on an object
type CheckOperation struct {
	CheckOperationOneOf  *CheckOperationOneOf
	CheckOperationOneOf1 *CheckOperationOneOf1
	CheckOperationOneOf2 *CheckOperationOneOf2
	CheckOperationOneOf3 *CheckOperationOneOf3
	CheckOperationOneOf4 *CheckOperationOneOf4
	CheckOperationOneOf5 *CheckOperationOneOf5
}

// CheckOperationOneOfAsCheckOperation is a convenience function that returns CheckOperationOneOf wrapped in CheckOperation
func CheckOperationOneOfAsCheckOperation(v *CheckOperationOneOf) CheckOperation {
	return CheckOperation{
		CheckOperationOneOf: v,
	}
}

// CheckOperationOneOf1AsCheckOperation is a convenience function that returns CheckOperationOneOf1 wrapped in CheckOperation
func CheckOperationOneOf1AsCheckOperation(v *CheckOperationOneOf1) CheckOperation {
	return CheckOperation{
		CheckOperationOneOf1: v,
	}
}

// CheckOperationOneOf2AsCheckOperation is a convenience function that returns CheckOperationOneOf2 wrapped in CheckOperation
func CheckOperationOneOf2AsCheckOperation(v *CheckOperationOneOf2) CheckOperation {
	return CheckOperation{
		CheckOperationOneOf2: v,
	}
}

// CheckOperationOneOf3AsCheckOperation is a convenience function that returns CheckOperationOneOf3 wrapped in CheckOperation
func CheckOperationOneOf3AsCheckOperation(v *CheckOperationOneOf3) CheckOperation {
	return CheckOperation{
		CheckOperationOneOf3: v,
	}
}

// CheckOperationOneOf4AsCheckOperation is a convenience function that returns CheckOperationOneOf4 wrapped in CheckOperation
func CheckOperationOneOf4AsCheckOperation(v *CheckOperationOneOf4) CheckOperation {
	return CheckOperation{
		CheckOperationOneOf4: v,
	}
}

// CheckOperationOneOf5AsCheckOperation is a convenience function that returns CheckOperationOneOf5 wrapped in CheckOperation
func CheckOperationOneOf5AsCheckOperation(v *CheckOperationOneOf5) CheckOperation {
	return CheckOperation{
		CheckOperationOneOf5: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CheckOperation) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CheckOperationOneOf
	err = json.Unmarshal(data, &dst.CheckOperationOneOf)
	if err == nil {
		jsonCheckOperationOneOf, _ := json.Marshal(dst.CheckOperationOneOf)
		if string(jsonCheckOperationOneOf) == "{}" { // empty struct
			dst.CheckOperationOneOf = nil
		} else {
			match++
		}
	} else {
		dst.CheckOperationOneOf = nil
	}

	// try to unmarshal data into CheckOperationOneOf1
	err = json.Unmarshal(data, &dst.CheckOperationOneOf1)
	if err == nil {
		jsonCheckOperationOneOf1, _ := json.Marshal(dst.CheckOperationOneOf1)
		if string(jsonCheckOperationOneOf1) == "{}" { // empty struct
			dst.CheckOperationOneOf1 = nil
		} else {
			match++
		}
	} else {
		dst.CheckOperationOneOf1 = nil
	}

	// try to unmarshal data into CheckOperationOneOf2
	err = json.Unmarshal(data, &dst.CheckOperationOneOf2)
	if err == nil {
		jsonCheckOperationOneOf2, _ := json.Marshal(dst.CheckOperationOneOf2)
		if string(jsonCheckOperationOneOf2) == "{}" { // empty struct
			dst.CheckOperationOneOf2 = nil
		} else {
			match++
		}
	} else {
		dst.CheckOperationOneOf2 = nil
	}

	// try to unmarshal data into CheckOperationOneOf3
	err = json.Unmarshal(data, &dst.CheckOperationOneOf3)
	if err == nil {
		jsonCheckOperationOneOf3, _ := json.Marshal(dst.CheckOperationOneOf3)
		if string(jsonCheckOperationOneOf3) == "{}" { // empty struct
			dst.CheckOperationOneOf3 = nil
		} else {
			match++
		}
	} else {
		dst.CheckOperationOneOf3 = nil
	}

	// try to unmarshal data into CheckOperationOneOf4
	err = json.Unmarshal(data, &dst.CheckOperationOneOf4)
	if err == nil {
		jsonCheckOperationOneOf4, _ := json.Marshal(dst.CheckOperationOneOf4)
		if string(jsonCheckOperationOneOf4) == "{}" { // empty struct
			dst.CheckOperationOneOf4 = nil
		} else {
			match++
		}
	} else {
		dst.CheckOperationOneOf4 = nil
	}

	// try to unmarshal data into CheckOperationOneOf5
	err = json.Unmarshal(data, &dst.CheckOperationOneOf5)
	if err == nil {
		jsonCheckOperationOneOf5, _ := json.Marshal(dst.CheckOperationOneOf5)
		if string(jsonCheckOperationOneOf5) == "{}" { // empty struct
			dst.CheckOperationOneOf5 = nil
		} else {
			match++
		}
	} else {
		dst.CheckOperationOneOf5 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CheckOperationOneOf = nil
		dst.CheckOperationOneOf1 = nil
		dst.CheckOperationOneOf2 = nil
		dst.CheckOperationOneOf3 = nil
		dst.CheckOperationOneOf4 = nil
		dst.CheckOperationOneOf5 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CheckOperation)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CheckOperation)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CheckOperation) MarshalJSON() ([]byte, error) {
	if src.CheckOperationOneOf != nil {
		return json.Marshal(&src.CheckOperationOneOf)
	}

	if src.CheckOperationOneOf1 != nil {
		return json.Marshal(&src.CheckOperationOneOf1)
	}

	if src.CheckOperationOneOf2 != nil {
		return json.Marshal(&src.CheckOperationOneOf2)
	}

	if src.CheckOperationOneOf3 != nil {
		return json.Marshal(&src.CheckOperationOneOf3)
	}

	if src.CheckOperationOneOf4 != nil {
		return json.Marshal(&src.CheckOperationOneOf4)
	}

	if src.CheckOperationOneOf5 != nil {
		return json.Marshal(&src.CheckOperationOneOf5)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CheckOperation) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CheckOperationOneOf != nil {
		return obj.CheckOperationOneOf
	}

	if obj.CheckOperationOneOf1 != nil {
		return obj.CheckOperationOneOf1
	}

	if obj.CheckOperationOneOf2 != nil {
		return obj.CheckOperationOneOf2
	}

	if obj.CheckOperationOneOf3 != nil {
		return obj.CheckOperationOneOf3
	}

	if obj.CheckOperationOneOf4 != nil {
		return obj.CheckOperationOneOf4
	}

	if obj.CheckOperationOneOf5 != nil {
		return obj.CheckOperationOneOf5
	}

	// all schemas are nil
	return nil
}

type NullableCheckOperation struct {
	value *CheckOperation
	isSet bool
}

func (v NullableCheckOperation) Get() *CheckOperation {
	return v.value
}

func (v *NullableCheckOperation) Set(val *CheckOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckOperation(val *CheckOperation) *NullableCheckOperation {
	return &NullableCheckOperation{value: val, isSet: true}
}

func (v NullableCheckOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
