/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the S3AccessKeyCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3AccessKeyCredential{}

// S3AccessKeyCredential struct for S3AccessKeyCredential
type S3AccessKeyCredential struct {
	AccessKeyId     string  `json:"access-key-id"`
	ExternalId      *string `json:"external-id,omitempty"`
	SecretAccessKey string  `json:"secret-access-key"`
}

type _S3AccessKeyCredential S3AccessKeyCredential

// NewS3AccessKeyCredential instantiates a new S3AccessKeyCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3AccessKeyCredential(accessKeyId string, secretAccessKey string) *S3AccessKeyCredential {
	this := S3AccessKeyCredential{}
	this.AccessKeyId = accessKeyId
	this.SecretAccessKey = secretAccessKey
	return &this
}

// NewS3AccessKeyCredentialWithDefaults instantiates a new S3AccessKeyCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3AccessKeyCredentialWithDefaults() *S3AccessKeyCredential {
	this := S3AccessKeyCredential{}
	return &this
}

// GetAccessKeyId returns the AccessKeyId field value
func (o *S3AccessKeyCredential) GetAccessKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKeyId
}

// GetAccessKeyIdOk returns a tuple with the AccessKeyId field value
// and a boolean to check if the value has been set.
func (o *S3AccessKeyCredential) GetAccessKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessKeyId, true
}

// SetAccessKeyId sets field value
func (o *S3AccessKeyCredential) SetAccessKeyId(v string) {
	o.AccessKeyId = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *S3AccessKeyCredential) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3AccessKeyCredential) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *S3AccessKeyCredential) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *S3AccessKeyCredential) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetSecretAccessKey returns the SecretAccessKey field value
func (o *S3AccessKeyCredential) GetSecretAccessKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretAccessKey
}

// GetSecretAccessKeyOk returns a tuple with the SecretAccessKey field value
// and a boolean to check if the value has been set.
func (o *S3AccessKeyCredential) GetSecretAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretAccessKey, true
}

// SetSecretAccessKey sets field value
func (o *S3AccessKeyCredential) SetSecretAccessKey(v string) {
	o.SecretAccessKey = v
}

func (o S3AccessKeyCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access-key-id"] = o.AccessKeyId
	if !IsNil(o.ExternalId) {
		toSerialize["external-id"] = o.ExternalId
	}
	toSerialize["secret-access-key"] = o.SecretAccessKey
	return toSerialize, nil
}

func (o *S3AccessKeyCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access-key-id",
		"secret-access-key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varS3AccessKeyCredential := _S3AccessKeyCredential{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varS3AccessKeyCredential)

	if err != nil {
		return err
	}

	*o = S3AccessKeyCredential(varS3AccessKeyCredential)

	return err
}

type NullableS3AccessKeyCredential struct {
	value *S3AccessKeyCredential
	isSet bool
}

func (v NullableS3AccessKeyCredential) Get() *S3AccessKeyCredential {
	return v.value
}

func (v *NullableS3AccessKeyCredential) Set(val *S3AccessKeyCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableS3AccessKeyCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableS3AccessKeyCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3AccessKeyCredential(val *S3AccessKeyCredential) *NullableS3AccessKeyCredential {
	return &NullableS3AccessKeyCredential{value: val, isSet: true}
}

func (v NullableS3AccessKeyCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3AccessKeyCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
