/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WarehouseAssignmentCreateUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WarehouseAssignmentCreateUser{}

// WarehouseAssignmentCreateUser struct for WarehouseAssignmentCreateUser
type WarehouseAssignmentCreateUser struct {
	// Id of the user
	User string `json:"user"`
	Type string `json:"type"`
}

type _WarehouseAssignmentCreateUser WarehouseAssignmentCreateUser

// NewWarehouseAssignmentCreateUser instantiates a new WarehouseAssignmentCreateUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWarehouseAssignmentCreateUser(user string, type_ string) *WarehouseAssignmentCreateUser {
	this := WarehouseAssignmentCreateUser{}
	this.User = user
	this.Type = type_
	return &this
}

// NewWarehouseAssignmentCreateUserWithDefaults instantiates a new WarehouseAssignmentCreateUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWarehouseAssignmentCreateUserWithDefaults() *WarehouseAssignmentCreateUser {
	this := WarehouseAssignmentCreateUser{}
	return &this
}

// GetUser returns the User field value
func (o *WarehouseAssignmentCreateUser) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *WarehouseAssignmentCreateUser) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *WarehouseAssignmentCreateUser) SetUser(v string) {
	o.User = v
}

// GetType returns the Type field value
func (o *WarehouseAssignmentCreateUser) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WarehouseAssignmentCreateUser) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WarehouseAssignmentCreateUser) SetType(v string) {
	o.Type = v
}

func (o WarehouseAssignmentCreateUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WarehouseAssignmentCreateUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *WarehouseAssignmentCreateUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWarehouseAssignmentCreateUser := _WarehouseAssignmentCreateUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWarehouseAssignmentCreateUser)

	if err != nil {
		return err
	}

	*o = WarehouseAssignmentCreateUser(varWarehouseAssignmentCreateUser)

	return err
}

type NullableWarehouseAssignmentCreateUser struct {
	value *WarehouseAssignmentCreateUser
	isSet bool
}

func (v NullableWarehouseAssignmentCreateUser) Get() *WarehouseAssignmentCreateUser {
	return v.value
}

func (v *NullableWarehouseAssignmentCreateUser) Set(val *WarehouseAssignmentCreateUser) {
	v.value = val
	v.isSet = true
}

func (v NullableWarehouseAssignmentCreateUser) IsSet() bool {
	return v.isSet
}

func (v *NullableWarehouseAssignmentCreateUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWarehouseAssignmentCreateUser(val *WarehouseAssignmentCreateUser) *NullableWarehouseAssignmentCreateUser {
	return &NullableWarehouseAssignmentCreateUser{value: val, isSet: true}
}

func (v NullableWarehouseAssignmentCreateUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWarehouseAssignmentCreateUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
