/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// TableAssignmentSelect - struct for TableAssignmentSelect
type TableAssignmentSelect struct {
	TableAssignmentSelectRole *TableAssignmentSelectRole
	TableAssignmentSelectUser *TableAssignmentSelectUser
}

// TableAssignmentSelectRoleAsTableAssignmentSelect is a convenience function that returns TableAssignmentSelectRole wrapped in TableAssignmentSelect
func TableAssignmentSelectRoleAsTableAssignmentSelect(v *TableAssignmentSelectRole) TableAssignmentSelect {
	return TableAssignmentSelect{
		TableAssignmentSelectRole: v,
	}
}

// TableAssignmentSelectUserAsTableAssignmentSelect is a convenience function that returns TableAssignmentSelectUser wrapped in TableAssignmentSelect
func TableAssignmentSelectUserAsTableAssignmentSelect(v *TableAssignmentSelectUser) TableAssignmentSelect {
	return TableAssignmentSelect{
		TableAssignmentSelectUser: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *TableAssignmentSelect) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TableAssignmentSelectRole
	err = json.Unmarshal(data, &dst.TableAssignmentSelectRole)
	if err == nil {
		jsonTableAssignmentSelectRole, _ := json.Marshal(dst.TableAssignmentSelectRole)
		if string(jsonTableAssignmentSelectRole) == "{}" { // empty struct
			dst.TableAssignmentSelectRole = nil
		} else {
			match++
		}
	} else {
		dst.TableAssignmentSelectRole = nil
	}

	// try to unmarshal data into TableAssignmentSelectUser
	err = json.Unmarshal(data, &dst.TableAssignmentSelectUser)
	if err == nil {
		jsonTableAssignmentSelectUser, _ := json.Marshal(dst.TableAssignmentSelectUser)
		if string(jsonTableAssignmentSelectUser) == "{}" { // empty struct
			dst.TableAssignmentSelectUser = nil
		} else {
			match++
		}
	} else {
		dst.TableAssignmentSelectUser = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TableAssignmentSelectRole = nil
		dst.TableAssignmentSelectUser = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TableAssignmentSelect)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TableAssignmentSelect)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TableAssignmentSelect) MarshalJSON() ([]byte, error) {
	if src.TableAssignmentSelectRole != nil {
		return json.Marshal(&src.TableAssignmentSelectRole)
	}

	if src.TableAssignmentSelectUser != nil {
		return json.Marshal(&src.TableAssignmentSelectUser)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TableAssignmentSelect) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.TableAssignmentSelectRole != nil {
		return obj.TableAssignmentSelectRole
	}

	if obj.TableAssignmentSelectUser != nil {
		return obj.TableAssignmentSelectUser
	}

	// all schemas are nil
	return nil
}

type NullableTableAssignmentSelect struct {
	value *TableAssignmentSelect
	isSet bool
}

func (v NullableTableAssignmentSelect) Get() *TableAssignmentSelect {
	return v.value
}

func (v *NullableTableAssignmentSelect) Set(val *TableAssignmentSelect) {
	v.value = val
	v.isSet = true
}

func (v NullableTableAssignmentSelect) IsSet() bool {
	return v.isSet
}

func (v *NullableTableAssignmentSelect) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableAssignmentSelect(val *TableAssignmentSelect) *NullableTableAssignmentSelect {
	return &NullableTableAssignmentSelect{value: val, isSet: true}
}

func (v NullableTableAssignmentSelect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableAssignmentSelect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
