/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WarehouseAssignmentCreateRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WarehouseAssignmentCreateRole{}

// WarehouseAssignmentCreateRole struct for WarehouseAssignmentCreateRole
type WarehouseAssignmentCreateRole struct {
	// Id of the role
	Role string `json:"role"`
	Type string `json:"type"`
}

type _WarehouseAssignmentCreateRole WarehouseAssignmentCreateRole

// NewWarehouseAssignmentCreateRole instantiates a new WarehouseAssignmentCreateRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWarehouseAssignmentCreateRole(role string, type_ string) *WarehouseAssignmentCreateRole {
	this := WarehouseAssignmentCreateRole{}
	this.Role = role
	this.Type = type_
	return &this
}

// NewWarehouseAssignmentCreateRoleWithDefaults instantiates a new WarehouseAssignmentCreateRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWarehouseAssignmentCreateRoleWithDefaults() *WarehouseAssignmentCreateRole {
	this := WarehouseAssignmentCreateRole{}
	return &this
}

// GetRole returns the Role field value
func (o *WarehouseAssignmentCreateRole) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *WarehouseAssignmentCreateRole) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *WarehouseAssignmentCreateRole) SetRole(v string) {
	o.Role = v
}

// GetType returns the Type field value
func (o *WarehouseAssignmentCreateRole) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WarehouseAssignmentCreateRole) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WarehouseAssignmentCreateRole) SetType(v string) {
	o.Type = v
}

func (o WarehouseAssignmentCreateRole) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WarehouseAssignmentCreateRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *WarehouseAssignmentCreateRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWarehouseAssignmentCreateRole := _WarehouseAssignmentCreateRole{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWarehouseAssignmentCreateRole)

	if err != nil {
		return err
	}

	*o = WarehouseAssignmentCreateRole(varWarehouseAssignmentCreateRole)

	return err
}

type NullableWarehouseAssignmentCreateRole struct {
	value *WarehouseAssignmentCreateRole
	isSet bool
}

func (v NullableWarehouseAssignmentCreateRole) Get() *WarehouseAssignmentCreateRole {
	return v.value
}

func (v *NullableWarehouseAssignmentCreateRole) Set(val *WarehouseAssignmentCreateRole) {
	v.value = val
	v.isSet = true
}

func (v NullableWarehouseAssignmentCreateRole) IsSet() bool {
	return v.isSet
}

func (v *NullableWarehouseAssignmentCreateRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWarehouseAssignmentCreateRole(val *WarehouseAssignmentCreateRole) *NullableWarehouseAssignmentCreateRole {
	return &NullableWarehouseAssignmentCreateRole{value: val, isSet: true}
}

func (v NullableWarehouseAssignmentCreateRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWarehouseAssignmentCreateRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
