/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// TabularIdentOrUuid - Identifier for a table or view, either a UUID or its name and namespace
type TabularIdentOrUuid struct {
	TabularIdentOrUuidOneOf  *TabularIdentOrUuidOneOf
	TabularIdentOrUuidOneOf1 *TabularIdentOrUuidOneOf1
}

// TabularIdentOrUuidOneOfAsTabularIdentOrUuid is a convenience function that returns TabularIdentOrUuidOneOf wrapped in TabularIdentOrUuid
func TabularIdentOrUuidOneOfAsTabularIdentOrUuid(v *TabularIdentOrUuidOneOf) TabularIdentOrUuid {
	return TabularIdentOrUuid{
		TabularIdentOrUuidOneOf: v,
	}
}

// TabularIdentOrUuidOneOf1AsTabularIdentOrUuid is a convenience function that returns TabularIdentOrUuidOneOf1 wrapped in TabularIdentOrUuid
func TabularIdentOrUuidOneOf1AsTabularIdentOrUuid(v *TabularIdentOrUuidOneOf1) TabularIdentOrUuid {
	return TabularIdentOrUuid{
		TabularIdentOrUuidOneOf1: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *TabularIdentOrUuid) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TabularIdentOrUuidOneOf
	err = json.Unmarshal(data, &dst.TabularIdentOrUuidOneOf)
	if err == nil {
		jsonTabularIdentOrUuidOneOf, _ := json.Marshal(dst.TabularIdentOrUuidOneOf)
		if string(jsonTabularIdentOrUuidOneOf) == "{}" { // empty struct
			dst.TabularIdentOrUuidOneOf = nil
		} else {
			match++
		}
	} else {
		dst.TabularIdentOrUuidOneOf = nil
	}

	// try to unmarshal data into TabularIdentOrUuidOneOf1
	err = json.Unmarshal(data, &dst.TabularIdentOrUuidOneOf1)
	if err == nil {
		jsonTabularIdentOrUuidOneOf1, _ := json.Marshal(dst.TabularIdentOrUuidOneOf1)
		if string(jsonTabularIdentOrUuidOneOf1) == "{}" { // empty struct
			dst.TabularIdentOrUuidOneOf1 = nil
		} else {
			match++
		}
	} else {
		dst.TabularIdentOrUuidOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TabularIdentOrUuidOneOf = nil
		dst.TabularIdentOrUuidOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TabularIdentOrUuid)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TabularIdentOrUuid)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TabularIdentOrUuid) MarshalJSON() ([]byte, error) {
	if src.TabularIdentOrUuidOneOf != nil {
		return json.Marshal(&src.TabularIdentOrUuidOneOf)
	}

	if src.TabularIdentOrUuidOneOf1 != nil {
		return json.Marshal(&src.TabularIdentOrUuidOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TabularIdentOrUuid) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.TabularIdentOrUuidOneOf != nil {
		return obj.TabularIdentOrUuidOneOf
	}

	if obj.TabularIdentOrUuidOneOf1 != nil {
		return obj.TabularIdentOrUuidOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableTabularIdentOrUuid struct {
	value *TabularIdentOrUuid
	isSet bool
}

func (v NullableTabularIdentOrUuid) Get() *TabularIdentOrUuid {
	return v.value
}

func (v *NullableTabularIdentOrUuid) Set(val *TabularIdentOrUuid) {
	v.value = val
	v.isSet = true
}

func (v NullableTabularIdentOrUuid) IsSet() bool {
	return v.isSet
}

func (v *NullableTabularIdentOrUuid) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTabularIdentOrUuid(val *TabularIdentOrUuid) *NullableTabularIdentOrUuid {
	return &NullableTabularIdentOrUuid{value: val, isSet: true}
}

func (v NullableTabularIdentOrUuid) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTabularIdentOrUuid) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
