/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LakekeeperNamespaceActionOneOf7 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LakekeeperNamespaceActionOneOf7{}

// LakekeeperNamespaceActionOneOf7 struct for LakekeeperNamespaceActionOneOf7
type LakekeeperNamespaceActionOneOf7 struct {
	Action string `json:"action"`
}

type _LakekeeperNamespaceActionOneOf7 LakekeeperNamespaceActionOneOf7

// NewLakekeeperNamespaceActionOneOf7 instantiates a new LakekeeperNamespaceActionOneOf7 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLakekeeperNamespaceActionOneOf7(action string) *LakekeeperNamespaceActionOneOf7 {
	this := LakekeeperNamespaceActionOneOf7{}
	this.Action = action
	return &this
}

// NewLakekeeperNamespaceActionOneOf7WithDefaults instantiates a new LakekeeperNamespaceActionOneOf7 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLakekeeperNamespaceActionOneOf7WithDefaults() *LakekeeperNamespaceActionOneOf7 {
	this := LakekeeperNamespaceActionOneOf7{}
	return &this
}

// GetAction returns the Action field value
func (o *LakekeeperNamespaceActionOneOf7) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *LakekeeperNamespaceActionOneOf7) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *LakekeeperNamespaceActionOneOf7) SetAction(v string) {
	o.Action = v
}

func (o LakekeeperNamespaceActionOneOf7) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *LakekeeperNamespaceActionOneOf7) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLakekeeperNamespaceActionOneOf7 := _LakekeeperNamespaceActionOneOf7{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLakekeeperNamespaceActionOneOf7)

	if err != nil {
		return err
	}

	*o = LakekeeperNamespaceActionOneOf7(varLakekeeperNamespaceActionOneOf7)

	return err
}

type NullableLakekeeperNamespaceActionOneOf7 struct {
	value *LakekeeperNamespaceActionOneOf7
	isSet bool
}

func (v NullableLakekeeperNamespaceActionOneOf7) Get() *LakekeeperNamespaceActionOneOf7 {
	return v.value
}

func (v *NullableLakekeeperNamespaceActionOneOf7) Set(val *LakekeeperNamespaceActionOneOf7) {
	v.value = val
	v.isSet = true
}

func (v NullableLakekeeperNamespaceActionOneOf7) IsSet() bool {
	return v.isSet
}

func (v *NullableLakekeeperNamespaceActionOneOf7) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLakekeeperNamespaceActionOneOf7(val *LakekeeperNamespaceActionOneOf7) *NullableLakekeeperNamespaceActionOneOf7 {
	return &NullableLakekeeperNamespaceActionOneOf7{value: val, isSet: true}
}

func (v NullableLakekeeperNamespaceActionOneOf7) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLakekeeperNamespaceActionOneOf7) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
