/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"time"
)

// checks if the ListProjectTasksRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProjectTasksRequest{}

// ListProjectTasksRequest struct for ListProjectTasksRequest
type ListProjectTasksRequest struct {
	// Filter tasks created after this timestamp
	CreatedAfter *time.Time `json:"created-after,omitempty"`
	// Filter tasks created before this timestamp
	CreatedBefore *time.Time `json:"created-before,omitempty"`
	// Number of results per page
	PageSize *int64 `json:"page-size,omitempty"`
	// Next page token, re-use the same request as for the original request, but set this to the `next_page_token` from the previous response. Stop iterating when no more items are returned in a page.
	PageToken *string `json:"page-token,omitempty"`
	// Filter by one or more queue names
	QueueName []string `json:"queue-name,omitempty"`
	// Filter by task status
	Status []TaskStatus `json:"status,omitempty"`
}

// NewListProjectTasksRequest instantiates a new ListProjectTasksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProjectTasksRequest() *ListProjectTasksRequest {
	this := ListProjectTasksRequest{}
	return &this
}

// NewListProjectTasksRequestWithDefaults instantiates a new ListProjectTasksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProjectTasksRequestWithDefaults() *ListProjectTasksRequest {
	this := ListProjectTasksRequest{}
	return &this
}

// GetCreatedAfter returns the CreatedAfter field value if set, zero value otherwise.
func (o *ListProjectTasksRequest) GetCreatedAfter() time.Time {
	if o == nil || IsNil(o.CreatedAfter) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAfter
}

// GetCreatedAfterOk returns a tuple with the CreatedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProjectTasksRequest) GetCreatedAfterOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAfter) {
		return nil, false
	}
	return o.CreatedAfter, true
}

// HasCreatedAfter returns a boolean if a field has been set.
func (o *ListProjectTasksRequest) HasCreatedAfter() bool {
	if o != nil && !IsNil(o.CreatedAfter) {
		return true
	}

	return false
}

// SetCreatedAfter gets a reference to the given time.Time and assigns it to the CreatedAfter field.
func (o *ListProjectTasksRequest) SetCreatedAfter(v time.Time) {
	o.CreatedAfter = &v
}

// GetCreatedBefore returns the CreatedBefore field value if set, zero value otherwise.
func (o *ListProjectTasksRequest) GetCreatedBefore() time.Time {
	if o == nil || IsNil(o.CreatedBefore) {
		var ret time.Time
		return ret
	}
	return *o.CreatedBefore
}

// GetCreatedBeforeOk returns a tuple with the CreatedBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProjectTasksRequest) GetCreatedBeforeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedBefore) {
		return nil, false
	}
	return o.CreatedBefore, true
}

// HasCreatedBefore returns a boolean if a field has been set.
func (o *ListProjectTasksRequest) HasCreatedBefore() bool {
	if o != nil && !IsNil(o.CreatedBefore) {
		return true
	}

	return false
}

// SetCreatedBefore gets a reference to the given time.Time and assigns it to the CreatedBefore field.
func (o *ListProjectTasksRequest) SetCreatedBefore(v time.Time) {
	o.CreatedBefore = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *ListProjectTasksRequest) GetPageSize() int64 {
	if o == nil || IsNil(o.PageSize) {
		var ret int64
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProjectTasksRequest) GetPageSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *ListProjectTasksRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int64 and assigns it to the PageSize field.
func (o *ListProjectTasksRequest) SetPageSize(v int64) {
	o.PageSize = &v
}

// GetPageToken returns the PageToken field value if set, zero value otherwise.
func (o *ListProjectTasksRequest) GetPageToken() string {
	if o == nil || IsNil(o.PageToken) {
		var ret string
		return ret
	}
	return *o.PageToken
}

// GetPageTokenOk returns a tuple with the PageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProjectTasksRequest) GetPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.PageToken) {
		return nil, false
	}
	return o.PageToken, true
}

// HasPageToken returns a boolean if a field has been set.
func (o *ListProjectTasksRequest) HasPageToken() bool {
	if o != nil && !IsNil(o.PageToken) {
		return true
	}

	return false
}

// SetPageToken gets a reference to the given string and assigns it to the PageToken field.
func (o *ListProjectTasksRequest) SetPageToken(v string) {
	o.PageToken = &v
}

// GetQueueName returns the QueueName field value if set, zero value otherwise.
func (o *ListProjectTasksRequest) GetQueueName() []string {
	if o == nil || IsNil(o.QueueName) {
		var ret []string
		return ret
	}
	return o.QueueName
}

// GetQueueNameOk returns a tuple with the QueueName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProjectTasksRequest) GetQueueNameOk() ([]string, bool) {
	if o == nil || IsNil(o.QueueName) {
		return nil, false
	}
	return o.QueueName, true
}

// HasQueueName returns a boolean if a field has been set.
func (o *ListProjectTasksRequest) HasQueueName() bool {
	if o != nil && !IsNil(o.QueueName) {
		return true
	}

	return false
}

// SetQueueName gets a reference to the given []string and assigns it to the QueueName field.
func (o *ListProjectTasksRequest) SetQueueName(v []string) {
	o.QueueName = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListProjectTasksRequest) GetStatus() []TaskStatus {
	if o == nil || IsNil(o.Status) {
		var ret []TaskStatus
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProjectTasksRequest) GetStatusOk() ([]TaskStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListProjectTasksRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given []TaskStatus and assigns it to the Status field.
func (o *ListProjectTasksRequest) SetStatus(v []TaskStatus) {
	o.Status = v
}

func (o ListProjectTasksRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAfter) {
		toSerialize["created-after"] = o.CreatedAfter
	}
	if !IsNil(o.CreatedBefore) {
		toSerialize["created-before"] = o.CreatedBefore
	}
	if !IsNil(o.PageSize) {
		toSerialize["page-size"] = o.PageSize
	}
	if !IsNil(o.PageToken) {
		toSerialize["page-token"] = o.PageToken
	}
	if !IsNil(o.QueueName) {
		toSerialize["queue-name"] = o.QueueName
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableListProjectTasksRequest struct {
	value *ListProjectTasksRequest
	isSet bool
}

func (v NullableListProjectTasksRequest) Get() *ListProjectTasksRequest {
	return v.value
}

func (v *NullableListProjectTasksRequest) Set(val *ListProjectTasksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListProjectTasksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListProjectTasksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProjectTasksRequest(val *ListProjectTasksRequest) *NullableListProjectTasksRequest {
	return &NullableListProjectTasksRequest{value: val, isSet: true}
}

func (v NullableListProjectTasksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProjectTasksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
