/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CheckOperationOneOf5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckOperationOneOf5{}

// CheckOperationOneOf5 struct for CheckOperationOneOf5
type CheckOperationOneOf5 struct {
	View CheckOperationOneOf5View `json:"view"`
}

type _CheckOperationOneOf5 CheckOperationOneOf5

// NewCheckOperationOneOf5 instantiates a new CheckOperationOneOf5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckOperationOneOf5(view CheckOperationOneOf5View) *CheckOperationOneOf5 {
	this := CheckOperationOneOf5{}
	this.View = view
	return &this
}

// NewCheckOperationOneOf5WithDefaults instantiates a new CheckOperationOneOf5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckOperationOneOf5WithDefaults() *CheckOperationOneOf5 {
	this := CheckOperationOneOf5{}
	return &this
}

// GetView returns the View field value
func (o *CheckOperationOneOf5) GetView() CheckOperationOneOf5View {
	if o == nil {
		var ret CheckOperationOneOf5View
		return ret
	}

	return o.View
}

// GetViewOk returns a tuple with the View field value
// and a boolean to check if the value has been set.
func (o *CheckOperationOneOf5) GetViewOk() (*CheckOperationOneOf5View, bool) {
	if o == nil {
		return nil, false
	}
	return &o.View, true
}

// SetView sets field value
func (o *CheckOperationOneOf5) SetView(v CheckOperationOneOf5View) {
	o.View = v
}

func (o CheckOperationOneOf5) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckOperationOneOf5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["view"] = o.View
	return toSerialize, nil
}

func (o *CheckOperationOneOf5) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"view",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckOperationOneOf5 := _CheckOperationOneOf5{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckOperationOneOf5)

	if err != nil {
		return err
	}

	*o = CheckOperationOneOf5(varCheckOperationOneOf5)

	return err
}

type NullableCheckOperationOneOf5 struct {
	value *CheckOperationOneOf5
	isSet bool
}

func (v NullableCheckOperationOneOf5) Get() *CheckOperationOneOf5 {
	return v.value
}

func (v *NullableCheckOperationOneOf5) Set(val *CheckOperationOneOf5) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckOperationOneOf5) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckOperationOneOf5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckOperationOneOf5(val *CheckOperationOneOf5) *NullableCheckOperationOneOf5 {
	return &NullableCheckOperationOneOf5{value: val, isSet: true}
}

func (v NullableCheckOperationOneOf5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckOperationOneOf5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
