/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StorageCredentialAccessKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageCredentialAccessKey{}

// StorageCredentialAccessKey struct for StorageCredentialAccessKey
type StorageCredentialAccessKey struct {
	AccessKeyId     string  `json:"access-key-id"`
	ExternalId      *string `json:"external-id,omitempty"`
	SecretAccessKey string  `json:"secret-access-key"`
	CredentialType  string  `json:"credential-type"`
	Type            string  `json:"type"`
}

type _StorageCredentialAccessKey StorageCredentialAccessKey

// NewStorageCredentialAccessKey instantiates a new StorageCredentialAccessKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageCredentialAccessKey(accessKeyId string, secretAccessKey string, credentialType string, type_ string) *StorageCredentialAccessKey {
	this := StorageCredentialAccessKey{}
	this.AccessKeyId = accessKeyId
	this.SecretAccessKey = secretAccessKey
	this.CredentialType = credentialType
	this.Type = type_
	return &this
}

// NewStorageCredentialAccessKeyWithDefaults instantiates a new StorageCredentialAccessKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageCredentialAccessKeyWithDefaults() *StorageCredentialAccessKey {
	this := StorageCredentialAccessKey{}
	return &this
}

// GetAccessKeyId returns the AccessKeyId field value
func (o *StorageCredentialAccessKey) GetAccessKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKeyId
}

// GetAccessKeyIdOk returns a tuple with the AccessKeyId field value
// and a boolean to check if the value has been set.
func (o *StorageCredentialAccessKey) GetAccessKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessKeyId, true
}

// SetAccessKeyId sets field value
func (o *StorageCredentialAccessKey) SetAccessKeyId(v string) {
	o.AccessKeyId = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *StorageCredentialAccessKey) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageCredentialAccessKey) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *StorageCredentialAccessKey) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *StorageCredentialAccessKey) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetSecretAccessKey returns the SecretAccessKey field value
func (o *StorageCredentialAccessKey) GetSecretAccessKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretAccessKey
}

// GetSecretAccessKeyOk returns a tuple with the SecretAccessKey field value
// and a boolean to check if the value has been set.
func (o *StorageCredentialAccessKey) GetSecretAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretAccessKey, true
}

// SetSecretAccessKey sets field value
func (o *StorageCredentialAccessKey) SetSecretAccessKey(v string) {
	o.SecretAccessKey = v
}

// GetCredentialType returns the CredentialType field value
func (o *StorageCredentialAccessKey) GetCredentialType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *StorageCredentialAccessKey) GetCredentialTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *StorageCredentialAccessKey) SetCredentialType(v string) {
	o.CredentialType = v
}

// GetType returns the Type field value
func (o *StorageCredentialAccessKey) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StorageCredentialAccessKey) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StorageCredentialAccessKey) SetType(v string) {
	o.Type = v
}

func (o StorageCredentialAccessKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageCredentialAccessKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access-key-id"] = o.AccessKeyId
	if !IsNil(o.ExternalId) {
		toSerialize["external-id"] = o.ExternalId
	}
	toSerialize["secret-access-key"] = o.SecretAccessKey
	toSerialize["credential-type"] = o.CredentialType
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *StorageCredentialAccessKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access-key-id",
		"secret-access-key",
		"credential-type",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageCredentialAccessKey := _StorageCredentialAccessKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStorageCredentialAccessKey)

	if err != nil {
		return err
	}

	*o = StorageCredentialAccessKey(varStorageCredentialAccessKey)

	return err
}

type NullableStorageCredentialAccessKey struct {
	value *StorageCredentialAccessKey
	isSet bool
}

func (v NullableStorageCredentialAccessKey) Get() *StorageCredentialAccessKey {
	return v.value
}

func (v *NullableStorageCredentialAccessKey) Set(val *StorageCredentialAccessKey) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageCredentialAccessKey) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageCredentialAccessKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageCredentialAccessKey(val *StorageCredentialAccessKey) *NullableStorageCredentialAccessKey {
	return &NullableStorageCredentialAccessKey{value: val, isSet: true}
}

func (v NullableStorageCredentialAccessKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageCredentialAccessKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
