/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WarehouseFilterOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WarehouseFilterOneOf2{}

// WarehouseFilterOneOf2 Return all items in the current project, regardless of warehouse association
type WarehouseFilterOneOf2 struct {
	Type string `json:"type"`
}

type _WarehouseFilterOneOf2 WarehouseFilterOneOf2

// NewWarehouseFilterOneOf2 instantiates a new WarehouseFilterOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWarehouseFilterOneOf2(type_ string) *WarehouseFilterOneOf2 {
	this := WarehouseFilterOneOf2{}
	this.Type = type_
	return &this
}

// NewWarehouseFilterOneOf2WithDefaults instantiates a new WarehouseFilterOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWarehouseFilterOneOf2WithDefaults() *WarehouseFilterOneOf2 {
	this := WarehouseFilterOneOf2{}
	return &this
}

// GetType returns the Type field value
func (o *WarehouseFilterOneOf2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WarehouseFilterOneOf2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WarehouseFilterOneOf2) SetType(v string) {
	o.Type = v
}

func (o WarehouseFilterOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *WarehouseFilterOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWarehouseFilterOneOf2 := _WarehouseFilterOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWarehouseFilterOneOf2)

	if err != nil {
		return err
	}

	*o = WarehouseFilterOneOf2(varWarehouseFilterOneOf2)

	return err
}

type NullableWarehouseFilterOneOf2 struct {
	value *WarehouseFilterOneOf2
	isSet bool
}

func (v NullableWarehouseFilterOneOf2) Get() *WarehouseFilterOneOf2 {
	return v.value
}

func (v *NullableWarehouseFilterOneOf2) Set(val *WarehouseFilterOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableWarehouseFilterOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableWarehouseFilterOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWarehouseFilterOneOf2(val *WarehouseFilterOneOf2) *NullableWarehouseFilterOneOf2 {
	return &NullableWarehouseFilterOneOf2{value: val, isSet: true}
}

func (v NullableWarehouseFilterOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWarehouseFilterOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
