/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CatalogActionCheckOperationOneOf5View type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogActionCheckOperationOneOf5View{}

// CatalogActionCheckOperationOneOf5View struct for CatalogActionCheckOperationOneOf5View
type CatalogActionCheckOperationOneOf5View struct {
	TableId     string   `json:"table-id"`
	WarehouseId string   `json:"warehouse-id"`
	Namespace   []string `json:"namespace"`
	// Name of the table or view
	Table  string               `json:"table"`
	Action LakekeeperViewAction `json:"action"`
}

type _CatalogActionCheckOperationOneOf5View CatalogActionCheckOperationOneOf5View

// NewCatalogActionCheckOperationOneOf5View instantiates a new CatalogActionCheckOperationOneOf5View object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogActionCheckOperationOneOf5View(tableId string, warehouseId string, namespace []string, table string, action LakekeeperViewAction) *CatalogActionCheckOperationOneOf5View {
	this := CatalogActionCheckOperationOneOf5View{}
	this.TableId = tableId
	this.WarehouseId = warehouseId
	this.Namespace = namespace
	this.Table = table
	this.Action = action
	return &this
}

// NewCatalogActionCheckOperationOneOf5ViewWithDefaults instantiates a new CatalogActionCheckOperationOneOf5View object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogActionCheckOperationOneOf5ViewWithDefaults() *CatalogActionCheckOperationOneOf5View {
	this := CatalogActionCheckOperationOneOf5View{}
	return &this
}

// GetTableId returns the TableId field value
func (o *CatalogActionCheckOperationOneOf5View) GetTableId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TableId
}

// GetTableIdOk returns a tuple with the TableId field value
// and a boolean to check if the value has been set.
func (o *CatalogActionCheckOperationOneOf5View) GetTableIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TableId, true
}

// SetTableId sets field value
func (o *CatalogActionCheckOperationOneOf5View) SetTableId(v string) {
	o.TableId = v
}

// GetWarehouseId returns the WarehouseId field value
func (o *CatalogActionCheckOperationOneOf5View) GetWarehouseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WarehouseId
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value
// and a boolean to check if the value has been set.
func (o *CatalogActionCheckOperationOneOf5View) GetWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarehouseId, true
}

// SetWarehouseId sets field value
func (o *CatalogActionCheckOperationOneOf5View) SetWarehouseId(v string) {
	o.WarehouseId = v
}

// GetNamespace returns the Namespace field value
func (o *CatalogActionCheckOperationOneOf5View) GetNamespace() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *CatalogActionCheckOperationOneOf5View) GetNamespaceOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Namespace, true
}

// SetNamespace sets field value
func (o *CatalogActionCheckOperationOneOf5View) SetNamespace(v []string) {
	o.Namespace = v
}

// GetTable returns the Table field value
func (o *CatalogActionCheckOperationOneOf5View) GetTable() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Table
}

// GetTableOk returns a tuple with the Table field value
// and a boolean to check if the value has been set.
func (o *CatalogActionCheckOperationOneOf5View) GetTableOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Table, true
}

// SetTable sets field value
func (o *CatalogActionCheckOperationOneOf5View) SetTable(v string) {
	o.Table = v
}

// GetAction returns the Action field value
func (o *CatalogActionCheckOperationOneOf5View) GetAction() LakekeeperViewAction {
	if o == nil {
		var ret LakekeeperViewAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CatalogActionCheckOperationOneOf5View) GetActionOk() (*LakekeeperViewAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CatalogActionCheckOperationOneOf5View) SetAction(v LakekeeperViewAction) {
	o.Action = v
}

func (o CatalogActionCheckOperationOneOf5View) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogActionCheckOperationOneOf5View) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["table-id"] = o.TableId
	toSerialize["warehouse-id"] = o.WarehouseId
	toSerialize["namespace"] = o.Namespace
	toSerialize["table"] = o.Table
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *CatalogActionCheckOperationOneOf5View) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"table-id",
		"warehouse-id",
		"namespace",
		"table",
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogActionCheckOperationOneOf5View := _CatalogActionCheckOperationOneOf5View{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogActionCheckOperationOneOf5View)

	if err != nil {
		return err
	}

	*o = CatalogActionCheckOperationOneOf5View(varCatalogActionCheckOperationOneOf5View)

	return err
}

type NullableCatalogActionCheckOperationOneOf5View struct {
	value *CatalogActionCheckOperationOneOf5View
	isSet bool
}

func (v NullableCatalogActionCheckOperationOneOf5View) Get() *CatalogActionCheckOperationOneOf5View {
	return v.value
}

func (v *NullableCatalogActionCheckOperationOneOf5View) Set(val *CatalogActionCheckOperationOneOf5View) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogActionCheckOperationOneOf5View) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogActionCheckOperationOneOf5View) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogActionCheckOperationOneOf5View(val *CatalogActionCheckOperationOneOf5View) *NullableCatalogActionCheckOperationOneOf5View {
	return &NullableCatalogActionCheckOperationOneOf5View{value: val, isSet: true}
}

func (v NullableCatalogActionCheckOperationOneOf5View) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogActionCheckOperationOneOf5View) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
