/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
)

// checks if the UpdateRoleAssignmentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRoleAssignmentsRequest{}

// UpdateRoleAssignmentsRequest struct for UpdateRoleAssignmentsRequest
type UpdateRoleAssignmentsRequest struct {
	Deletes []RoleAssignment `json:"deletes,omitempty"`
	Writes  []RoleAssignment `json:"writes,omitempty"`
}

// NewUpdateRoleAssignmentsRequest instantiates a new UpdateRoleAssignmentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRoleAssignmentsRequest() *UpdateRoleAssignmentsRequest {
	this := UpdateRoleAssignmentsRequest{}
	return &this
}

// NewUpdateRoleAssignmentsRequestWithDefaults instantiates a new UpdateRoleAssignmentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRoleAssignmentsRequestWithDefaults() *UpdateRoleAssignmentsRequest {
	this := UpdateRoleAssignmentsRequest{}
	return &this
}

// GetDeletes returns the Deletes field value if set, zero value otherwise.
func (o *UpdateRoleAssignmentsRequest) GetDeletes() []RoleAssignment {
	if o == nil || IsNil(o.Deletes) {
		var ret []RoleAssignment
		return ret
	}
	return o.Deletes
}

// GetDeletesOk returns a tuple with the Deletes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRoleAssignmentsRequest) GetDeletesOk() ([]RoleAssignment, bool) {
	if o == nil || IsNil(o.Deletes) {
		return nil, false
	}
	return o.Deletes, true
}

// HasDeletes returns a boolean if a field has been set.
func (o *UpdateRoleAssignmentsRequest) HasDeletes() bool {
	if o != nil && !IsNil(o.Deletes) {
		return true
	}

	return false
}

// SetDeletes gets a reference to the given []RoleAssignment and assigns it to the Deletes field.
func (o *UpdateRoleAssignmentsRequest) SetDeletes(v []RoleAssignment) {
	o.Deletes = v
}

// GetWrites returns the Writes field value if set, zero value otherwise.
func (o *UpdateRoleAssignmentsRequest) GetWrites() []RoleAssignment {
	if o == nil || IsNil(o.Writes) {
		var ret []RoleAssignment
		return ret
	}
	return o.Writes
}

// GetWritesOk returns a tuple with the Writes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRoleAssignmentsRequest) GetWritesOk() ([]RoleAssignment, bool) {
	if o == nil || IsNil(o.Writes) {
		return nil, false
	}
	return o.Writes, true
}

// HasWrites returns a boolean if a field has been set.
func (o *UpdateRoleAssignmentsRequest) HasWrites() bool {
	if o != nil && !IsNil(o.Writes) {
		return true
	}

	return false
}

// SetWrites gets a reference to the given []RoleAssignment and assigns it to the Writes field.
func (o *UpdateRoleAssignmentsRequest) SetWrites(v []RoleAssignment) {
	o.Writes = v
}

func (o UpdateRoleAssignmentsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRoleAssignmentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deletes) {
		toSerialize["deletes"] = o.Deletes
	}
	if !IsNil(o.Writes) {
		toSerialize["writes"] = o.Writes
	}
	return toSerialize, nil
}

type NullableUpdateRoleAssignmentsRequest struct {
	value *UpdateRoleAssignmentsRequest
	isSet bool
}

func (v NullableUpdateRoleAssignmentsRequest) Get() *UpdateRoleAssignmentsRequest {
	return v.value
}

func (v *NullableUpdateRoleAssignmentsRequest) Set(val *UpdateRoleAssignmentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRoleAssignmentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRoleAssignmentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRoleAssignmentsRequest(val *UpdateRoleAssignmentsRequest) *NullableUpdateRoleAssignmentsRequest {
	return &NullableUpdateRoleAssignmentsRequest{value: val, isSet: true}
}

func (v NullableUpdateRoleAssignmentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRoleAssignmentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
