/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// TableRelation the model 'TableRelation'
type TableRelation string

// List of TableRelation
const (
	TABLERELATION_OWNERSHIP     TableRelation = "ownership"
	TABLERELATION_PASS_GRANTS   TableRelation = "pass_grants"
	TABLERELATION_MANAGE_GRANTS TableRelation = "manage_grants"
	TABLERELATION_DESCRIBE      TableRelation = "describe"
	TABLERELATION_SELECT        TableRelation = "select"
	TABLERELATION_MODIFY        TableRelation = "modify"
)

// All allowed values of TableRelation enum
var AllowedTableRelationEnumValues = []TableRelation{
	"ownership",
	"pass_grants",
	"manage_grants",
	"describe",
	"select",
	"modify",
}

func (v *TableRelation) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TableRelation(value)
	for _, existing := range AllowedTableRelationEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TableRelation", value)
}

// NewTableRelationFromValue returns a pointer to a valid TableRelation
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTableRelationFromValue(v string) (*TableRelation, error) {
	ev := TableRelation(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TableRelation: valid values are %v", v, AllowedTableRelationEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TableRelation) IsValid() bool {
	for _, existing := range AllowedTableRelationEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TableRelation value
func (v TableRelation) Ptr() *TableRelation {
	return &v
}

type NullableTableRelation struct {
	value *TableRelation
	isSet bool
}

func (v NullableTableRelation) Get() *TableRelation {
	return v.value
}

func (v *NullableTableRelation) Set(val *TableRelation) {
	v.value = val
	v.isSet = true
}

func (v NullableTableRelation) IsSet() bool {
	return v.isSet
}

func (v *NullableTableRelation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableRelation(val *TableRelation) *NullableTableRelation {
	return &NullableTableRelation{value: val, isSet: true}
}

func (v NullableTableRelation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableRelation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
