/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LakekeeperNamespaceActionOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LakekeeperNamespaceActionOneOf2{}

// LakekeeperNamespaceActionOneOf2 struct for LakekeeperNamespaceActionOneOf2
type LakekeeperNamespaceActionOneOf2 struct {
	Action string `json:"action"`
	// Name of the namespace to create.
	Name       *string           `json:"name,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
}

type _LakekeeperNamespaceActionOneOf2 LakekeeperNamespaceActionOneOf2

// NewLakekeeperNamespaceActionOneOf2 instantiates a new LakekeeperNamespaceActionOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLakekeeperNamespaceActionOneOf2(action string) *LakekeeperNamespaceActionOneOf2 {
	this := LakekeeperNamespaceActionOneOf2{}
	this.Action = action
	return &this
}

// NewLakekeeperNamespaceActionOneOf2WithDefaults instantiates a new LakekeeperNamespaceActionOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLakekeeperNamespaceActionOneOf2WithDefaults() *LakekeeperNamespaceActionOneOf2 {
	this := LakekeeperNamespaceActionOneOf2{}
	return &this
}

// GetAction returns the Action field value
func (o *LakekeeperNamespaceActionOneOf2) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *LakekeeperNamespaceActionOneOf2) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *LakekeeperNamespaceActionOneOf2) SetAction(v string) {
	o.Action = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LakekeeperNamespaceActionOneOf2) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LakekeeperNamespaceActionOneOf2) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LakekeeperNamespaceActionOneOf2) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LakekeeperNamespaceActionOneOf2) SetName(v string) {
	o.Name = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *LakekeeperNamespaceActionOneOf2) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LakekeeperNamespaceActionOneOf2) GetPropertiesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return map[string]string{}, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *LakekeeperNamespaceActionOneOf2) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *LakekeeperNamespaceActionOneOf2) SetProperties(v map[string]string) {
	o.Properties = v
}

func (o LakekeeperNamespaceActionOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

func (o *LakekeeperNamespaceActionOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLakekeeperNamespaceActionOneOf2 := _LakekeeperNamespaceActionOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLakekeeperNamespaceActionOneOf2)

	if err != nil {
		return err
	}

	*o = LakekeeperNamespaceActionOneOf2(varLakekeeperNamespaceActionOneOf2)

	return err
}

type NullableLakekeeperNamespaceActionOneOf2 struct {
	value *LakekeeperNamespaceActionOneOf2
	isSet bool
}

func (v NullableLakekeeperNamespaceActionOneOf2) Get() *LakekeeperNamespaceActionOneOf2 {
	return v.value
}

func (v *NullableLakekeeperNamespaceActionOneOf2) Set(val *LakekeeperNamespaceActionOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableLakekeeperNamespaceActionOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableLakekeeperNamespaceActionOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLakekeeperNamespaceActionOneOf2(val *LakekeeperNamespaceActionOneOf2) *NullableLakekeeperNamespaceActionOneOf2 {
	return &NullableLakekeeperNamespaceActionOneOf2{value: val, isSet: true}
}

func (v NullableLakekeeperNamespaceActionOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLakekeeperNamespaceActionOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
