/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// ProjectRelation the model 'ProjectRelation'
type ProjectRelation string

// List of ProjectRelation
const (
	PROJECTRELATION_PROJECT_ADMIN  ProjectRelation = "project_admin"
	PROJECTRELATION_SECURITY_ADMIN ProjectRelation = "security_admin"
	PROJECTRELATION_DATA_ADMIN     ProjectRelation = "data_admin"
	PROJECTRELATION_ROLE_CREATOR   ProjectRelation = "role_creator"
	PROJECTRELATION_DESCRIBE       ProjectRelation = "describe"
	PROJECTRELATION_SELECT         ProjectRelation = "select"
	PROJECTRELATION_CREATE         ProjectRelation = "create"
	PROJECTRELATION_MODIFY         ProjectRelation = "modify"
)

// All allowed values of ProjectRelation enum
var AllowedProjectRelationEnumValues = []ProjectRelation{
	"project_admin",
	"security_admin",
	"data_admin",
	"role_creator",
	"describe",
	"select",
	"create",
	"modify",
}

func (v *ProjectRelation) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProjectRelation(value)
	for _, existing := range AllowedProjectRelationEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ProjectRelation", value)
}

// NewProjectRelationFromValue returns a pointer to a valid ProjectRelation
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewProjectRelationFromValue(v string) (*ProjectRelation, error) {
	ev := ProjectRelation(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ProjectRelation: valid values are %v", v, AllowedProjectRelationEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ProjectRelation) IsValid() bool {
	for _, existing := range AllowedProjectRelationEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ProjectRelation value
func (v ProjectRelation) Ptr() *ProjectRelation {
	return &v
}

type NullableProjectRelation struct {
	value *ProjectRelation
	isSet bool
}

func (v NullableProjectRelation) Get() *ProjectRelation {
	return v.value
}

func (v *NullableProjectRelation) Set(val *ProjectRelation) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectRelation) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectRelation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectRelation(val *ProjectRelation) *NullableProjectRelation {
	return &NullableProjectRelation{value: val, isSet: true}
}

func (v NullableProjectRelation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectRelation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
