/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CatalogActionCheckOperationProjectProject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogActionCheckOperationProjectProject{}

// CatalogActionCheckOperationProjectProject struct for CatalogActionCheckOperationProjectProject
type CatalogActionCheckOperationProjectProject struct {
	Action    LakekeeperProjectAction `json:"action"`
	ProjectId NullableString          `json:"project-id,omitempty"`
}

type _CatalogActionCheckOperationProjectProject CatalogActionCheckOperationProjectProject

// NewCatalogActionCheckOperationProjectProject instantiates a new CatalogActionCheckOperationProjectProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogActionCheckOperationProjectProject(action LakekeeperProjectAction) *CatalogActionCheckOperationProjectProject {
	this := CatalogActionCheckOperationProjectProject{}
	this.Action = action
	return &this
}

// NewCatalogActionCheckOperationProjectProjectWithDefaults instantiates a new CatalogActionCheckOperationProjectProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogActionCheckOperationProjectProjectWithDefaults() *CatalogActionCheckOperationProjectProject {
	this := CatalogActionCheckOperationProjectProject{}
	return &this
}

// GetAction returns the Action field value
func (o *CatalogActionCheckOperationProjectProject) GetAction() LakekeeperProjectAction {
	if o == nil {
		var ret LakekeeperProjectAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CatalogActionCheckOperationProjectProject) GetActionOk() (*LakekeeperProjectAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CatalogActionCheckOperationProjectProject) SetAction(v LakekeeperProjectAction) {
	o.Action = v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CatalogActionCheckOperationProjectProject) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CatalogActionCheckOperationProjectProject) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *CatalogActionCheckOperationProjectProject) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *CatalogActionCheckOperationProjectProject) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}

// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *CatalogActionCheckOperationProjectProject) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *CatalogActionCheckOperationProjectProject) UnsetProjectId() {
	o.ProjectId.Unset()
}

func (o CatalogActionCheckOperationProjectProject) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogActionCheckOperationProjectProject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if o.ProjectId.IsSet() {
		toSerialize["project-id"] = o.ProjectId.Get()
	}
	return toSerialize, nil
}

func (o *CatalogActionCheckOperationProjectProject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogActionCheckOperationProjectProject := _CatalogActionCheckOperationProjectProject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogActionCheckOperationProjectProject)

	if err != nil {
		return err
	}

	*o = CatalogActionCheckOperationProjectProject(varCatalogActionCheckOperationProjectProject)

	return err
}

type NullableCatalogActionCheckOperationProjectProject struct {
	value *CatalogActionCheckOperationProjectProject
	isSet bool
}

func (v NullableCatalogActionCheckOperationProjectProject) Get() *CatalogActionCheckOperationProjectProject {
	return v.value
}

func (v *NullableCatalogActionCheckOperationProjectProject) Set(val *CatalogActionCheckOperationProjectProject) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogActionCheckOperationProjectProject) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogActionCheckOperationProjectProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogActionCheckOperationProjectProject(val *CatalogActionCheckOperationProjectProject) *NullableCatalogActionCheckOperationProjectProject {
	return &NullableCatalogActionCheckOperationProjectProject{value: val, isSet: true}
}

func (v NullableCatalogActionCheckOperationProjectProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogActionCheckOperationProjectProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
