/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
)

// checks if the TaskLogCleanupConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskLogCleanupConfig{}

// TaskLogCleanupConfig struct for TaskLogCleanupConfig
type TaskLogCleanupConfig struct {
	// How often to run the cleanup task in ISO8601 duration format. Defaults to once a day (P1D). If a value below 1 day is provided, it will be set to the default of 1 day.
	CleanupPeriod NullableString `json:"cleanup-period,omitempty"`
	// How long to retain task logs before deletion in ISO8601 duration format. Defaults to 90 days.
	RetentionPeriod NullableString `json:"retention-period,omitempty"`
}

// NewTaskLogCleanupConfig instantiates a new TaskLogCleanupConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskLogCleanupConfig() *TaskLogCleanupConfig {
	this := TaskLogCleanupConfig{}
	return &this
}

// NewTaskLogCleanupConfigWithDefaults instantiates a new TaskLogCleanupConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskLogCleanupConfigWithDefaults() *TaskLogCleanupConfig {
	this := TaskLogCleanupConfig{}
	return &this
}

// GetCleanupPeriod returns the CleanupPeriod field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaskLogCleanupConfig) GetCleanupPeriod() string {
	if o == nil || IsNil(o.CleanupPeriod.Get()) {
		var ret string
		return ret
	}
	return *o.CleanupPeriod.Get()
}

// GetCleanupPeriodOk returns a tuple with the CleanupPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskLogCleanupConfig) GetCleanupPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CleanupPeriod.Get(), o.CleanupPeriod.IsSet()
}

// HasCleanupPeriod returns a boolean if a field has been set.
func (o *TaskLogCleanupConfig) HasCleanupPeriod() bool {
	if o != nil && o.CleanupPeriod.IsSet() {
		return true
	}

	return false
}

// SetCleanupPeriod gets a reference to the given NullableString and assigns it to the CleanupPeriod field.
func (o *TaskLogCleanupConfig) SetCleanupPeriod(v string) {
	o.CleanupPeriod.Set(&v)
}

// SetCleanupPeriodNil sets the value for CleanupPeriod to be an explicit nil
func (o *TaskLogCleanupConfig) SetCleanupPeriodNil() {
	o.CleanupPeriod.Set(nil)
}

// UnsetCleanupPeriod ensures that no value is present for CleanupPeriod, not even an explicit nil
func (o *TaskLogCleanupConfig) UnsetCleanupPeriod() {
	o.CleanupPeriod.Unset()
}

// GetRetentionPeriod returns the RetentionPeriod field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaskLogCleanupConfig) GetRetentionPeriod() string {
	if o == nil || IsNil(o.RetentionPeriod.Get()) {
		var ret string
		return ret
	}
	return *o.RetentionPeriod.Get()
}

// GetRetentionPeriodOk returns a tuple with the RetentionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaskLogCleanupConfig) GetRetentionPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetentionPeriod.Get(), o.RetentionPeriod.IsSet()
}

// HasRetentionPeriod returns a boolean if a field has been set.
func (o *TaskLogCleanupConfig) HasRetentionPeriod() bool {
	if o != nil && o.RetentionPeriod.IsSet() {
		return true
	}

	return false
}

// SetRetentionPeriod gets a reference to the given NullableString and assigns it to the RetentionPeriod field.
func (o *TaskLogCleanupConfig) SetRetentionPeriod(v string) {
	o.RetentionPeriod.Set(&v)
}

// SetRetentionPeriodNil sets the value for RetentionPeriod to be an explicit nil
func (o *TaskLogCleanupConfig) SetRetentionPeriodNil() {
	o.RetentionPeriod.Set(nil)
}

// UnsetRetentionPeriod ensures that no value is present for RetentionPeriod, not even an explicit nil
func (o *TaskLogCleanupConfig) UnsetRetentionPeriod() {
	o.RetentionPeriod.Unset()
}

func (o TaskLogCleanupConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskLogCleanupConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CleanupPeriod.IsSet() {
		toSerialize["cleanup-period"] = o.CleanupPeriod.Get()
	}
	if o.RetentionPeriod.IsSet() {
		toSerialize["retention-period"] = o.RetentionPeriod.Get()
	}
	return toSerialize, nil
}

type NullableTaskLogCleanupConfig struct {
	value *TaskLogCleanupConfig
	isSet bool
}

func (v NullableTaskLogCleanupConfig) Get() *TaskLogCleanupConfig {
	return v.value
}

func (v *NullableTaskLogCleanupConfig) Set(val *TaskLogCleanupConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskLogCleanupConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskLogCleanupConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskLogCleanupConfig(val *TaskLogCleanupConfig) *NullableTaskLogCleanupConfig {
	return &NullableTaskLogCleanupConfig{value: val, isSet: true}
}

func (v NullableTaskLogCleanupConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskLogCleanupConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
