/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WarehouseTaskEntityIdOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WarehouseTaskEntityIdOneOf1{}

// WarehouseTaskEntityIdOneOf1 struct for WarehouseTaskEntityIdOneOf1
type WarehouseTaskEntityIdOneOf1 struct {
	Type   string `json:"type"`
	ViewId string `json:"view-id"`
}

type _WarehouseTaskEntityIdOneOf1 WarehouseTaskEntityIdOneOf1

// NewWarehouseTaskEntityIdOneOf1 instantiates a new WarehouseTaskEntityIdOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWarehouseTaskEntityIdOneOf1(type_ string, viewId string) *WarehouseTaskEntityIdOneOf1 {
	this := WarehouseTaskEntityIdOneOf1{}
	this.Type = type_
	this.ViewId = viewId
	return &this
}

// NewWarehouseTaskEntityIdOneOf1WithDefaults instantiates a new WarehouseTaskEntityIdOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWarehouseTaskEntityIdOneOf1WithDefaults() *WarehouseTaskEntityIdOneOf1 {
	this := WarehouseTaskEntityIdOneOf1{}
	return &this
}

// GetType returns the Type field value
func (o *WarehouseTaskEntityIdOneOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WarehouseTaskEntityIdOneOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WarehouseTaskEntityIdOneOf1) SetType(v string) {
	o.Type = v
}

// GetViewId returns the ViewId field value
func (o *WarehouseTaskEntityIdOneOf1) GetViewId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ViewId
}

// GetViewIdOk returns a tuple with the ViewId field value
// and a boolean to check if the value has been set.
func (o *WarehouseTaskEntityIdOneOf1) GetViewIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViewId, true
}

// SetViewId sets field value
func (o *WarehouseTaskEntityIdOneOf1) SetViewId(v string) {
	o.ViewId = v
}

func (o WarehouseTaskEntityIdOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WarehouseTaskEntityIdOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["view-id"] = o.ViewId
	return toSerialize, nil
}

func (o *WarehouseTaskEntityIdOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"view-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWarehouseTaskEntityIdOneOf1 := _WarehouseTaskEntityIdOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWarehouseTaskEntityIdOneOf1)

	if err != nil {
		return err
	}

	*o = WarehouseTaskEntityIdOneOf1(varWarehouseTaskEntityIdOneOf1)

	return err
}

type NullableWarehouseTaskEntityIdOneOf1 struct {
	value *WarehouseTaskEntityIdOneOf1
	isSet bool
}

func (v NullableWarehouseTaskEntityIdOneOf1) Get() *WarehouseTaskEntityIdOneOf1 {
	return v.value
}

func (v *NullableWarehouseTaskEntityIdOneOf1) Set(val *WarehouseTaskEntityIdOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableWarehouseTaskEntityIdOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableWarehouseTaskEntityIdOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWarehouseTaskEntityIdOneOf1(val *WarehouseTaskEntityIdOneOf1) *NullableWarehouseTaskEntityIdOneOf1 {
	return &NullableWarehouseTaskEntityIdOneOf1{value: val, isSet: true}
}

func (v NullableWarehouseTaskEntityIdOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWarehouseTaskEntityIdOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
