/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LakekeeperRoleActionOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LakekeeperRoleActionOneOf{}

// LakekeeperRoleActionOneOf struct for LakekeeperRoleActionOneOf
type LakekeeperRoleActionOneOf struct {
	Action string `json:"action"`
}

type _LakekeeperRoleActionOneOf LakekeeperRoleActionOneOf

// NewLakekeeperRoleActionOneOf instantiates a new LakekeeperRoleActionOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLakekeeperRoleActionOneOf(action string) *LakekeeperRoleActionOneOf {
	this := LakekeeperRoleActionOneOf{}
	this.Action = action
	return &this
}

// NewLakekeeperRoleActionOneOfWithDefaults instantiates a new LakekeeperRoleActionOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLakekeeperRoleActionOneOfWithDefaults() *LakekeeperRoleActionOneOf {
	this := LakekeeperRoleActionOneOf{}
	return &this
}

// GetAction returns the Action field value
func (o *LakekeeperRoleActionOneOf) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *LakekeeperRoleActionOneOf) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *LakekeeperRoleActionOneOf) SetAction(v string) {
	o.Action = v
}

func (o LakekeeperRoleActionOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *LakekeeperRoleActionOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLakekeeperRoleActionOneOf := _LakekeeperRoleActionOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLakekeeperRoleActionOneOf)

	if err != nil {
		return err
	}

	*o = LakekeeperRoleActionOneOf(varLakekeeperRoleActionOneOf)

	return err
}

type NullableLakekeeperRoleActionOneOf struct {
	value *LakekeeperRoleActionOneOf
	isSet bool
}

func (v NullableLakekeeperRoleActionOneOf) Get() *LakekeeperRoleActionOneOf {
	return v.value
}

func (v *NullableLakekeeperRoleActionOneOf) Set(val *LakekeeperRoleActionOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableLakekeeperRoleActionOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableLakekeeperRoleActionOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLakekeeperRoleActionOneOf(val *LakekeeperRoleActionOneOf) *NullableLakekeeperRoleActionOneOf {
	return &NullableLakekeeperRoleActionOneOf{value: val, isSet: true}
}

func (v NullableLakekeeperRoleActionOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLakekeeperRoleActionOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
