/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// NamespaceAssignmentCreate - struct for NamespaceAssignmentCreate
type NamespaceAssignmentCreate struct {
	NamespaceAssignmentCreateRole *NamespaceAssignmentCreateRole
	NamespaceAssignmentCreateUser *NamespaceAssignmentCreateUser
}

// NamespaceAssignmentCreateRoleAsNamespaceAssignmentCreate is a convenience function that returns NamespaceAssignmentCreateRole wrapped in NamespaceAssignmentCreate
func NamespaceAssignmentCreateRoleAsNamespaceAssignmentCreate(v *NamespaceAssignmentCreateRole) NamespaceAssignmentCreate {
	return NamespaceAssignmentCreate{
		NamespaceAssignmentCreateRole: v,
	}
}

// NamespaceAssignmentCreateUserAsNamespaceAssignmentCreate is a convenience function that returns NamespaceAssignmentCreateUser wrapped in NamespaceAssignmentCreate
func NamespaceAssignmentCreateUserAsNamespaceAssignmentCreate(v *NamespaceAssignmentCreateUser) NamespaceAssignmentCreate {
	return NamespaceAssignmentCreate{
		NamespaceAssignmentCreateUser: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *NamespaceAssignmentCreate) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into NamespaceAssignmentCreateRole
	err = json.Unmarshal(data, &dst.NamespaceAssignmentCreateRole)
	if err == nil {
		jsonNamespaceAssignmentCreateRole, _ := json.Marshal(dst.NamespaceAssignmentCreateRole)
		if string(jsonNamespaceAssignmentCreateRole) == "{}" { // empty struct
			dst.NamespaceAssignmentCreateRole = nil
		} else {
			match++
		}
	} else {
		dst.NamespaceAssignmentCreateRole = nil
	}

	// try to unmarshal data into NamespaceAssignmentCreateUser
	err = json.Unmarshal(data, &dst.NamespaceAssignmentCreateUser)
	if err == nil {
		jsonNamespaceAssignmentCreateUser, _ := json.Marshal(dst.NamespaceAssignmentCreateUser)
		if string(jsonNamespaceAssignmentCreateUser) == "{}" { // empty struct
			dst.NamespaceAssignmentCreateUser = nil
		} else {
			match++
		}
	} else {
		dst.NamespaceAssignmentCreateUser = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.NamespaceAssignmentCreateRole = nil
		dst.NamespaceAssignmentCreateUser = nil

		return fmt.Errorf("data matches more than one schema in oneOf(NamespaceAssignmentCreate)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(NamespaceAssignmentCreate)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NamespaceAssignmentCreate) MarshalJSON() ([]byte, error) {
	if src.NamespaceAssignmentCreateRole != nil {
		return json.Marshal(&src.NamespaceAssignmentCreateRole)
	}

	if src.NamespaceAssignmentCreateUser != nil {
		return json.Marshal(&src.NamespaceAssignmentCreateUser)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *NamespaceAssignmentCreate) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.NamespaceAssignmentCreateRole != nil {
		return obj.NamespaceAssignmentCreateRole
	}

	if obj.NamespaceAssignmentCreateUser != nil {
		return obj.NamespaceAssignmentCreateUser
	}

	// all schemas are nil
	return nil
}

type NullableNamespaceAssignmentCreate struct {
	value *NamespaceAssignmentCreate
	isSet bool
}

func (v NullableNamespaceAssignmentCreate) Get() *NamespaceAssignmentCreate {
	return v.value
}

func (v *NullableNamespaceAssignmentCreate) Set(val *NamespaceAssignmentCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceAssignmentCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceAssignmentCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceAssignmentCreate(val *NamespaceAssignmentCreate) *NullableNamespaceAssignmentCreate {
	return &NullableNamespaceAssignmentCreate{value: val, isSet: true}
}

func (v NullableNamespaceAssignmentCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceAssignmentCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
