/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// ServerAssignmentAdmin - struct for ServerAssignmentAdmin
type ServerAssignmentAdmin struct {
	ServerAssignmentAdminRole *ServerAssignmentAdminRole
	ServerAssignmentAdminUser *ServerAssignmentAdminUser
}

// ServerAssignmentAdminRoleAsServerAssignmentAdmin is a convenience function that returns ServerAssignmentAdminRole wrapped in ServerAssignmentAdmin
func ServerAssignmentAdminRoleAsServerAssignmentAdmin(v *ServerAssignmentAdminRole) ServerAssignmentAdmin {
	return ServerAssignmentAdmin{
		ServerAssignmentAdminRole: v,
	}
}

// ServerAssignmentAdminUserAsServerAssignmentAdmin is a convenience function that returns ServerAssignmentAdminUser wrapped in ServerAssignmentAdmin
func ServerAssignmentAdminUserAsServerAssignmentAdmin(v *ServerAssignmentAdminUser) ServerAssignmentAdmin {
	return ServerAssignmentAdmin{
		ServerAssignmentAdminUser: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ServerAssignmentAdmin) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ServerAssignmentAdminRole
	err = json.Unmarshal(data, &dst.ServerAssignmentAdminRole)
	if err == nil {
		jsonServerAssignmentAdminRole, _ := json.Marshal(dst.ServerAssignmentAdminRole)
		if string(jsonServerAssignmentAdminRole) == "{}" { // empty struct
			dst.ServerAssignmentAdminRole = nil
		} else {
			match++
		}
	} else {
		dst.ServerAssignmentAdminRole = nil
	}

	// try to unmarshal data into ServerAssignmentAdminUser
	err = json.Unmarshal(data, &dst.ServerAssignmentAdminUser)
	if err == nil {
		jsonServerAssignmentAdminUser, _ := json.Marshal(dst.ServerAssignmentAdminUser)
		if string(jsonServerAssignmentAdminUser) == "{}" { // empty struct
			dst.ServerAssignmentAdminUser = nil
		} else {
			match++
		}
	} else {
		dst.ServerAssignmentAdminUser = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ServerAssignmentAdminRole = nil
		dst.ServerAssignmentAdminUser = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ServerAssignmentAdmin)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ServerAssignmentAdmin)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ServerAssignmentAdmin) MarshalJSON() ([]byte, error) {
	if src.ServerAssignmentAdminRole != nil {
		return json.Marshal(&src.ServerAssignmentAdminRole)
	}

	if src.ServerAssignmentAdminUser != nil {
		return json.Marshal(&src.ServerAssignmentAdminUser)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ServerAssignmentAdmin) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ServerAssignmentAdminRole != nil {
		return obj.ServerAssignmentAdminRole
	}

	if obj.ServerAssignmentAdminUser != nil {
		return obj.ServerAssignmentAdminUser
	}

	// all schemas are nil
	return nil
}

type NullableServerAssignmentAdmin struct {
	value *ServerAssignmentAdmin
	isSet bool
}

func (v NullableServerAssignmentAdmin) Get() *ServerAssignmentAdmin {
	return v.value
}

func (v *NullableServerAssignmentAdmin) Set(val *ServerAssignmentAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableServerAssignmentAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableServerAssignmentAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerAssignmentAdmin(val *ServerAssignmentAdmin) *NullableServerAssignmentAdmin {
	return &NullableServerAssignmentAdmin{value: val, isSet: true}
}

func (v NullableServerAssignmentAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerAssignmentAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
