/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// WarehouseAssignmentModify - struct for WarehouseAssignmentModify
type WarehouseAssignmentModify struct {
	WarehouseAssignmentModifyRole *WarehouseAssignmentModifyRole
	WarehouseAssignmentModifyUser *WarehouseAssignmentModifyUser
}

// WarehouseAssignmentModifyRoleAsWarehouseAssignmentModify is a convenience function that returns WarehouseAssignmentModifyRole wrapped in WarehouseAssignmentModify
func WarehouseAssignmentModifyRoleAsWarehouseAssignmentModify(v *WarehouseAssignmentModifyRole) WarehouseAssignmentModify {
	return WarehouseAssignmentModify{
		WarehouseAssignmentModifyRole: v,
	}
}

// WarehouseAssignmentModifyUserAsWarehouseAssignmentModify is a convenience function that returns WarehouseAssignmentModifyUser wrapped in WarehouseAssignmentModify
func WarehouseAssignmentModifyUserAsWarehouseAssignmentModify(v *WarehouseAssignmentModifyUser) WarehouseAssignmentModify {
	return WarehouseAssignmentModify{
		WarehouseAssignmentModifyUser: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *WarehouseAssignmentModify) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into WarehouseAssignmentModifyRole
	err = json.Unmarshal(data, &dst.WarehouseAssignmentModifyRole)
	if err == nil {
		jsonWarehouseAssignmentModifyRole, _ := json.Marshal(dst.WarehouseAssignmentModifyRole)
		if string(jsonWarehouseAssignmentModifyRole) == "{}" { // empty struct
			dst.WarehouseAssignmentModifyRole = nil
		} else {
			match++
		}
	} else {
		dst.WarehouseAssignmentModifyRole = nil
	}

	// try to unmarshal data into WarehouseAssignmentModifyUser
	err = json.Unmarshal(data, &dst.WarehouseAssignmentModifyUser)
	if err == nil {
		jsonWarehouseAssignmentModifyUser, _ := json.Marshal(dst.WarehouseAssignmentModifyUser)
		if string(jsonWarehouseAssignmentModifyUser) == "{}" { // empty struct
			dst.WarehouseAssignmentModifyUser = nil
		} else {
			match++
		}
	} else {
		dst.WarehouseAssignmentModifyUser = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.WarehouseAssignmentModifyRole = nil
		dst.WarehouseAssignmentModifyUser = nil

		return fmt.Errorf("data matches more than one schema in oneOf(WarehouseAssignmentModify)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(WarehouseAssignmentModify)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src WarehouseAssignmentModify) MarshalJSON() ([]byte, error) {
	if src.WarehouseAssignmentModifyRole != nil {
		return json.Marshal(&src.WarehouseAssignmentModifyRole)
	}

	if src.WarehouseAssignmentModifyUser != nil {
		return json.Marshal(&src.WarehouseAssignmentModifyUser)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *WarehouseAssignmentModify) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.WarehouseAssignmentModifyRole != nil {
		return obj.WarehouseAssignmentModifyRole
	}

	if obj.WarehouseAssignmentModifyUser != nil {
		return obj.WarehouseAssignmentModifyUser
	}

	// all schemas are nil
	return nil
}

type NullableWarehouseAssignmentModify struct {
	value *WarehouseAssignmentModify
	isSet bool
}

func (v NullableWarehouseAssignmentModify) Get() *WarehouseAssignmentModify {
	return v.value
}

func (v *NullableWarehouseAssignmentModify) Set(val *WarehouseAssignmentModify) {
	v.value = val
	v.isSet = true
}

func (v NullableWarehouseAssignmentModify) IsSet() bool {
	return v.isSet
}

func (v *NullableWarehouseAssignmentModify) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWarehouseAssignmentModify(val *WarehouseAssignmentModify) *NullableWarehouseAssignmentModify {
	return &NullableWarehouseAssignmentModify{value: val, isSet: true}
}

func (v NullableWarehouseAssignmentModify) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWarehouseAssignmentModify) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
