/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// NamespaceAssignment - struct for NamespaceAssignment
type NamespaceAssignment struct {
	NamespaceAssignmentCreate       *NamespaceAssignmentCreate
	NamespaceAssignmentDescribe     *NamespaceAssignmentDescribe
	NamespaceAssignmentManageGrants *NamespaceAssignmentManageGrants
	NamespaceAssignmentModify       *NamespaceAssignmentModify
	NamespaceAssignmentOwnership    *NamespaceAssignmentOwnership
	NamespaceAssignmentPassGrants   *NamespaceAssignmentPassGrants
	NamespaceAssignmentSelect       *NamespaceAssignmentSelect
}

// NamespaceAssignmentCreateAsNamespaceAssignment is a convenience function that returns NamespaceAssignmentCreate wrapped in NamespaceAssignment
func NamespaceAssignmentCreateAsNamespaceAssignment(v *NamespaceAssignmentCreate) NamespaceAssignment {
	return NamespaceAssignment{
		NamespaceAssignmentCreate: v,
	}
}

// NamespaceAssignmentDescribeAsNamespaceAssignment is a convenience function that returns NamespaceAssignmentDescribe wrapped in NamespaceAssignment
func NamespaceAssignmentDescribeAsNamespaceAssignment(v *NamespaceAssignmentDescribe) NamespaceAssignment {
	return NamespaceAssignment{
		NamespaceAssignmentDescribe: v,
	}
}

// NamespaceAssignmentManageGrantsAsNamespaceAssignment is a convenience function that returns NamespaceAssignmentManageGrants wrapped in NamespaceAssignment
func NamespaceAssignmentManageGrantsAsNamespaceAssignment(v *NamespaceAssignmentManageGrants) NamespaceAssignment {
	return NamespaceAssignment{
		NamespaceAssignmentManageGrants: v,
	}
}

// NamespaceAssignmentModifyAsNamespaceAssignment is a convenience function that returns NamespaceAssignmentModify wrapped in NamespaceAssignment
func NamespaceAssignmentModifyAsNamespaceAssignment(v *NamespaceAssignmentModify) NamespaceAssignment {
	return NamespaceAssignment{
		NamespaceAssignmentModify: v,
	}
}

// NamespaceAssignmentOwnershipAsNamespaceAssignment is a convenience function that returns NamespaceAssignmentOwnership wrapped in NamespaceAssignment
func NamespaceAssignmentOwnershipAsNamespaceAssignment(v *NamespaceAssignmentOwnership) NamespaceAssignment {
	return NamespaceAssignment{
		NamespaceAssignmentOwnership: v,
	}
}

// NamespaceAssignmentPassGrantsAsNamespaceAssignment is a convenience function that returns NamespaceAssignmentPassGrants wrapped in NamespaceAssignment
func NamespaceAssignmentPassGrantsAsNamespaceAssignment(v *NamespaceAssignmentPassGrants) NamespaceAssignment {
	return NamespaceAssignment{
		NamespaceAssignmentPassGrants: v,
	}
}

// NamespaceAssignmentSelectAsNamespaceAssignment is a convenience function that returns NamespaceAssignmentSelect wrapped in NamespaceAssignment
func NamespaceAssignmentSelectAsNamespaceAssignment(v *NamespaceAssignmentSelect) NamespaceAssignment {
	return NamespaceAssignment{
		NamespaceAssignmentSelect: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *NamespaceAssignment) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into NamespaceAssignmentCreate
	err = json.Unmarshal(data, &dst.NamespaceAssignmentCreate)
	if err == nil {
		jsonNamespaceAssignmentCreate, _ := json.Marshal(dst.NamespaceAssignmentCreate)
		if string(jsonNamespaceAssignmentCreate) == "{}" { // empty struct
			dst.NamespaceAssignmentCreate = nil
		} else {
			match++
		}
	} else {
		dst.NamespaceAssignmentCreate = nil
	}

	// try to unmarshal data into NamespaceAssignmentDescribe
	err = json.Unmarshal(data, &dst.NamespaceAssignmentDescribe)
	if err == nil {
		jsonNamespaceAssignmentDescribe, _ := json.Marshal(dst.NamespaceAssignmentDescribe)
		if string(jsonNamespaceAssignmentDescribe) == "{}" { // empty struct
			dst.NamespaceAssignmentDescribe = nil
		} else {
			match++
		}
	} else {
		dst.NamespaceAssignmentDescribe = nil
	}

	// try to unmarshal data into NamespaceAssignmentManageGrants
	err = json.Unmarshal(data, &dst.NamespaceAssignmentManageGrants)
	if err == nil {
		jsonNamespaceAssignmentManageGrants, _ := json.Marshal(dst.NamespaceAssignmentManageGrants)
		if string(jsonNamespaceAssignmentManageGrants) == "{}" { // empty struct
			dst.NamespaceAssignmentManageGrants = nil
		} else {
			match++
		}
	} else {
		dst.NamespaceAssignmentManageGrants = nil
	}

	// try to unmarshal data into NamespaceAssignmentModify
	err = json.Unmarshal(data, &dst.NamespaceAssignmentModify)
	if err == nil {
		jsonNamespaceAssignmentModify, _ := json.Marshal(dst.NamespaceAssignmentModify)
		if string(jsonNamespaceAssignmentModify) == "{}" { // empty struct
			dst.NamespaceAssignmentModify = nil
		} else {
			match++
		}
	} else {
		dst.NamespaceAssignmentModify = nil
	}

	// try to unmarshal data into NamespaceAssignmentOwnership
	err = json.Unmarshal(data, &dst.NamespaceAssignmentOwnership)
	if err == nil {
		jsonNamespaceAssignmentOwnership, _ := json.Marshal(dst.NamespaceAssignmentOwnership)
		if string(jsonNamespaceAssignmentOwnership) == "{}" { // empty struct
			dst.NamespaceAssignmentOwnership = nil
		} else {
			match++
		}
	} else {
		dst.NamespaceAssignmentOwnership = nil
	}

	// try to unmarshal data into NamespaceAssignmentPassGrants
	err = json.Unmarshal(data, &dst.NamespaceAssignmentPassGrants)
	if err == nil {
		jsonNamespaceAssignmentPassGrants, _ := json.Marshal(dst.NamespaceAssignmentPassGrants)
		if string(jsonNamespaceAssignmentPassGrants) == "{}" { // empty struct
			dst.NamespaceAssignmentPassGrants = nil
		} else {
			match++
		}
	} else {
		dst.NamespaceAssignmentPassGrants = nil
	}

	// try to unmarshal data into NamespaceAssignmentSelect
	err = json.Unmarshal(data, &dst.NamespaceAssignmentSelect)
	if err == nil {
		jsonNamespaceAssignmentSelect, _ := json.Marshal(dst.NamespaceAssignmentSelect)
		if string(jsonNamespaceAssignmentSelect) == "{}" { // empty struct
			dst.NamespaceAssignmentSelect = nil
		} else {
			match++
		}
	} else {
		dst.NamespaceAssignmentSelect = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.NamespaceAssignmentCreate = nil
		dst.NamespaceAssignmentDescribe = nil
		dst.NamespaceAssignmentManageGrants = nil
		dst.NamespaceAssignmentModify = nil
		dst.NamespaceAssignmentOwnership = nil
		dst.NamespaceAssignmentPassGrants = nil
		dst.NamespaceAssignmentSelect = nil

		return fmt.Errorf("data matches more than one schema in oneOf(NamespaceAssignment)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(NamespaceAssignment)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NamespaceAssignment) MarshalJSON() ([]byte, error) {
	if src.NamespaceAssignmentCreate != nil {
		return json.Marshal(&src.NamespaceAssignmentCreate)
	}

	if src.NamespaceAssignmentDescribe != nil {
		return json.Marshal(&src.NamespaceAssignmentDescribe)
	}

	if src.NamespaceAssignmentManageGrants != nil {
		return json.Marshal(&src.NamespaceAssignmentManageGrants)
	}

	if src.NamespaceAssignmentModify != nil {
		return json.Marshal(&src.NamespaceAssignmentModify)
	}

	if src.NamespaceAssignmentOwnership != nil {
		return json.Marshal(&src.NamespaceAssignmentOwnership)
	}

	if src.NamespaceAssignmentPassGrants != nil {
		return json.Marshal(&src.NamespaceAssignmentPassGrants)
	}

	if src.NamespaceAssignmentSelect != nil {
		return json.Marshal(&src.NamespaceAssignmentSelect)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *NamespaceAssignment) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.NamespaceAssignmentCreate != nil {
		return obj.NamespaceAssignmentCreate
	}

	if obj.NamespaceAssignmentDescribe != nil {
		return obj.NamespaceAssignmentDescribe
	}

	if obj.NamespaceAssignmentManageGrants != nil {
		return obj.NamespaceAssignmentManageGrants
	}

	if obj.NamespaceAssignmentModify != nil {
		return obj.NamespaceAssignmentModify
	}

	if obj.NamespaceAssignmentOwnership != nil {
		return obj.NamespaceAssignmentOwnership
	}

	if obj.NamespaceAssignmentPassGrants != nil {
		return obj.NamespaceAssignmentPassGrants
	}

	if obj.NamespaceAssignmentSelect != nil {
		return obj.NamespaceAssignmentSelect
	}

	// all schemas are nil
	return nil
}

type NullableNamespaceAssignment struct {
	value *NamespaceAssignment
	isSet bool
}

func (v NullableNamespaceAssignment) Get() *NamespaceAssignment {
	return v.value
}

func (v *NullableNamespaceAssignment) Set(val *NamespaceAssignment) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceAssignment) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceAssignment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceAssignment(val *NamespaceAssignment) *NullableNamespaceAssignment {
	return &NullableNamespaceAssignment{value: val, isSet: true}
}

func (v NullableNamespaceAssignment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceAssignment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
