/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// ProjectAction the model 'ProjectAction'
type ProjectAction string

// List of ProjectAction
const (
	PROJECTACTION_CREATE_WAREHOUSE        ProjectAction = "create_warehouse"
	PROJECTACTION_DELETE                  ProjectAction = "delete"
	PROJECTACTION_RENAME                  ProjectAction = "rename"
	PROJECTACTION_LIST_WAREHOUSES         ProjectAction = "list_warehouses"
	PROJECTACTION_CREATE_ROLE             ProjectAction = "create_role"
	PROJECTACTION_LIST_ROLES              ProjectAction = "list_roles"
	PROJECTACTION_SEARCH_ROLES            ProjectAction = "search_roles"
	PROJECTACTION_READ_ASSIGNMENTS        ProjectAction = "read_assignments"
	PROJECTACTION_GRANT_ROLE_CREATOR      ProjectAction = "grant_role_creator"
	PROJECTACTION_GRANT_CREATE            ProjectAction = "grant_create"
	PROJECTACTION_GRANT_DESCRIBE          ProjectAction = "grant_describe"
	PROJECTACTION_GRANT_MODIFY            ProjectAction = "grant_modify"
	PROJECTACTION_GRANT_SELECT            ProjectAction = "grant_select"
	PROJECTACTION_GRANT_PROJECT_ADMIN     ProjectAction = "grant_project_admin"
	PROJECTACTION_GRANT_SECURITY_ADMIN    ProjectAction = "grant_security_admin"
	PROJECTACTION_GRANT_DATA_ADMIN        ProjectAction = "grant_data_admin"
	PROJECTACTION_GET_ENDPOINT_STATISTICS ProjectAction = "get_endpoint_statistics"
)

// All allowed values of ProjectAction enum
var AllowedProjectActionEnumValues = []ProjectAction{
	"create_warehouse",
	"delete",
	"rename",
	"list_warehouses",
	"create_role",
	"list_roles",
	"search_roles",
	"read_assignments",
	"grant_role_creator",
	"grant_create",
	"grant_describe",
	"grant_modify",
	"grant_select",
	"grant_project_admin",
	"grant_security_admin",
	"grant_data_admin",
	"get_endpoint_statistics",
}

func (v *ProjectAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProjectAction(value)
	for _, existing := range AllowedProjectActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ProjectAction", value)
}

// NewProjectActionFromValue returns a pointer to a valid ProjectAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewProjectActionFromValue(v string) (*ProjectAction, error) {
	ev := ProjectAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ProjectAction: valid values are %v", v, AllowedProjectActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ProjectAction) IsValid() bool {
	for _, existing := range AllowedProjectActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ProjectAction value
func (v ProjectAction) Ptr() *ProjectAction {
	return &v
}

type NullableProjectAction struct {
	value *ProjectAction
	isSet bool
}

func (v NullableProjectAction) Get() *ProjectAction {
	return v.value
}

func (v *NullableProjectAction) Set(val *ProjectAction) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAction) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAction(val *ProjectAction) *NullableProjectAction {
	return &NullableProjectAction{value: val, isSet: true}
}

func (v NullableProjectAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
