/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the S3Profile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3Profile{}

// S3Profile struct for S3Profile
type S3Profile struct {
	// Allow `s3a://` and `s3n://` in locations. This is disabled by default. We do not recommend to use this setting except for migration of old hadoop-based tables via the register endpoint. Tables with `s3a` paths are not accessible outside the Java ecosystem.
	AllowAlternativeProtocols NullableBool `json:"allow-alternative-protocols,omitempty"`
	// Optional ARN to assume when accessing the bucket from Lakekeeper.
	AssumeRoleArn NullableString `json:"assume-role-arn,omitempty"`
	// ARN of the KMS key used to encrypt the S3 bucket, if any.
	AwsKmsKeyArn NullableString `json:"aws-kms-key-arn,omitempty"`
	// Name of the S3 bucket
	Bucket string `json:"bucket"`
	// Optional endpoint to use for S3 requests, if not provided the region will be used to determine the endpoint. If both region and endpoint are provided, the endpoint will be used. Example: `http://s3-de.my-domain.com:9000`
	Endpoint NullableString `json:"endpoint,omitempty"`
	// S3 flavor to use. Defaults to AWS
	Flavor *S3Flavor `json:"flavor,omitempty"`
	// Subpath in the bucket to use.
	KeyPrefix NullableString `json:"key-prefix,omitempty"`
	// Legacy MD5 behavior for S3 operations requiring checksums. When enabled, Lakekeeper will use the legacy MD5 checksum for operations like `DeleteObjects`.
	LegacyMd5Behavior NullableBool `json:"legacy-md5-behavior,omitempty"`
	// Path style access for S3 requests. If the underlying S3 supports both, we recommend to not set `path_style_access`.
	PathStyleAccess NullableBool `json:"path-style-access,omitempty"`
	// Controls whether the `s3.delete-enabled=false` flag is sent to clients.  In all Iceberg 1.x versions, when Spark executes `DROP TABLE xxx PURGE`, it directly deletes files from S3, bypassing the catalog's soft-deletion mechanism. Other query engines properly delegate this operation to the catalog. This Spark behavior is expected to change in Iceberg 2.0.  Setting this to `true` pushes the `s3.delete-enabled=false` flag to clients, which discourages Spark from directly deleting files during `DROP TABLE xxx PURGE` operations. Note that clients may override this setting, and it affects other Spark operations that require file deletion, such as removing snapshots.  For more details, refer to Lakekeeper's [Soft-Deletion documentation](https://docs.lakekeeper.io/docs/nightly/concepts/#soft-deletion). This flag has no effect if Soft-Deletion is disabled for the warehouse.
	PushS3DeleteDisabled *bool `json:"push-s3-delete-disabled,omitempty"`
	// Region to use for S3 requests.
	Region string `json:"region"`
	// Enable remote signing for S3 requests. When disabled, clients cannot use remote signing even if STS is disabled. Defaults to true.
	RemoteSigningEnabled *bool `json:"remote-signing-enabled,omitempty"`
	// S3 URL style detection mode for remote signing. One of `auto`, `path-style`, `virtual-host`. Default: `auto`. When set to `auto`, Lakekeeper will first try to parse the URL as `virtual-host` and then attempt `path-style`. `path` assumes the bucket name is the first path segment in the URL. `virtual-host` assumes the bucket name is the first subdomain if it is preceding `.s3` or `.s3-`.  Examples  Virtual host:   - <https://bucket.s3.endpoint.com/bar/a/key>   - <https://bucket.s3-eu-central-1.amazonaws.com/file>  Path style:   - <https://s3.endpoint.com/bucket/bar/a/key>   - <https://s3.us-east-1.amazonaws.com/bucket/file>
	RemoteSigningUrlStyle *S3UrlStyleDetectionMode `json:"remote-signing-url-style,omitempty"`
	// Storage layout for namespace and tabular paths.
	StorageLayout NullableStorageLayout `json:"storage-layout,omitempty"`
	StsEnabled    bool                  `json:"sts-enabled"`
	// Optional endpoint to use for STS requests. Use this when the STS endpoint differs from the S3 endpoint, which is common with S3-compatible storage systems. If not provided, the S3 `endpoint` is used for STS requests as well.
	StsEndpoint NullableString `json:"sts-endpoint,omitempty"`
	// Optional role ARN to assume for sts vended-credentials. If not provided, `assume_role_arn` is used. Either `assume_role_arn` or `sts_role_arn` must be provided if `sts_enabled` is true.
	StsRoleArn NullableString `json:"sts-role-arn,omitempty"`
	// Optional session tags for STS assume role operations.
	StsSessionTags map[string]string `json:"sts-session-tags,omitempty"`
	// The validity of the sts tokens in seconds. Default is 3600
	StsTokenValiditySeconds *int64 `json:"sts-token-validity-seconds,omitempty"`
}

type _S3Profile S3Profile

// NewS3Profile instantiates a new S3Profile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3Profile(bucket string, region string, stsEnabled bool) *S3Profile {
	this := S3Profile{}
	this.Bucket = bucket
	this.Region = region
	this.StsEnabled = stsEnabled
	return &this
}

// NewS3ProfileWithDefaults instantiates a new S3Profile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3ProfileWithDefaults() *S3Profile {
	this := S3Profile{}
	return &this
}

// GetAllowAlternativeProtocols returns the AllowAlternativeProtocols field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetAllowAlternativeProtocols() bool {
	if o == nil || IsNil(o.AllowAlternativeProtocols.Get()) {
		var ret bool
		return ret
	}
	return *o.AllowAlternativeProtocols.Get()
}

// GetAllowAlternativeProtocolsOk returns a tuple with the AllowAlternativeProtocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetAllowAlternativeProtocolsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowAlternativeProtocols.Get(), o.AllowAlternativeProtocols.IsSet()
}

// HasAllowAlternativeProtocols returns a boolean if a field has been set.
func (o *S3Profile) HasAllowAlternativeProtocols() bool {
	if o != nil && o.AllowAlternativeProtocols.IsSet() {
		return true
	}

	return false
}

// SetAllowAlternativeProtocols gets a reference to the given NullableBool and assigns it to the AllowAlternativeProtocols field.
func (o *S3Profile) SetAllowAlternativeProtocols(v bool) {
	o.AllowAlternativeProtocols.Set(&v)
}

// SetAllowAlternativeProtocolsNil sets the value for AllowAlternativeProtocols to be an explicit nil
func (o *S3Profile) SetAllowAlternativeProtocolsNil() {
	o.AllowAlternativeProtocols.Set(nil)
}

// UnsetAllowAlternativeProtocols ensures that no value is present for AllowAlternativeProtocols, not even an explicit nil
func (o *S3Profile) UnsetAllowAlternativeProtocols() {
	o.AllowAlternativeProtocols.Unset()
}

// GetAssumeRoleArn returns the AssumeRoleArn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetAssumeRoleArn() string {
	if o == nil || IsNil(o.AssumeRoleArn.Get()) {
		var ret string
		return ret
	}
	return *o.AssumeRoleArn.Get()
}

// GetAssumeRoleArnOk returns a tuple with the AssumeRoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetAssumeRoleArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssumeRoleArn.Get(), o.AssumeRoleArn.IsSet()
}

// HasAssumeRoleArn returns a boolean if a field has been set.
func (o *S3Profile) HasAssumeRoleArn() bool {
	if o != nil && o.AssumeRoleArn.IsSet() {
		return true
	}

	return false
}

// SetAssumeRoleArn gets a reference to the given NullableString and assigns it to the AssumeRoleArn field.
func (o *S3Profile) SetAssumeRoleArn(v string) {
	o.AssumeRoleArn.Set(&v)
}

// SetAssumeRoleArnNil sets the value for AssumeRoleArn to be an explicit nil
func (o *S3Profile) SetAssumeRoleArnNil() {
	o.AssumeRoleArn.Set(nil)
}

// UnsetAssumeRoleArn ensures that no value is present for AssumeRoleArn, not even an explicit nil
func (o *S3Profile) UnsetAssumeRoleArn() {
	o.AssumeRoleArn.Unset()
}

// GetAwsKmsKeyArn returns the AwsKmsKeyArn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetAwsKmsKeyArn() string {
	if o == nil || IsNil(o.AwsKmsKeyArn.Get()) {
		var ret string
		return ret
	}
	return *o.AwsKmsKeyArn.Get()
}

// GetAwsKmsKeyArnOk returns a tuple with the AwsKmsKeyArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetAwsKmsKeyArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AwsKmsKeyArn.Get(), o.AwsKmsKeyArn.IsSet()
}

// HasAwsKmsKeyArn returns a boolean if a field has been set.
func (o *S3Profile) HasAwsKmsKeyArn() bool {
	if o != nil && o.AwsKmsKeyArn.IsSet() {
		return true
	}

	return false
}

// SetAwsKmsKeyArn gets a reference to the given NullableString and assigns it to the AwsKmsKeyArn field.
func (o *S3Profile) SetAwsKmsKeyArn(v string) {
	o.AwsKmsKeyArn.Set(&v)
}

// SetAwsKmsKeyArnNil sets the value for AwsKmsKeyArn to be an explicit nil
func (o *S3Profile) SetAwsKmsKeyArnNil() {
	o.AwsKmsKeyArn.Set(nil)
}

// UnsetAwsKmsKeyArn ensures that no value is present for AwsKmsKeyArn, not even an explicit nil
func (o *S3Profile) UnsetAwsKmsKeyArn() {
	o.AwsKmsKeyArn.Unset()
}

// GetBucket returns the Bucket field value
func (o *S3Profile) GetBucket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value
// and a boolean to check if the value has been set.
func (o *S3Profile) GetBucketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bucket, true
}

// SetBucket sets field value
func (o *S3Profile) SetBucket(v string) {
	o.Bucket = v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint.Get()) {
		var ret string
		return ret
	}
	return *o.Endpoint.Get()
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Endpoint.Get(), o.Endpoint.IsSet()
}

// HasEndpoint returns a boolean if a field has been set.
func (o *S3Profile) HasEndpoint() bool {
	if o != nil && o.Endpoint.IsSet() {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given NullableString and assigns it to the Endpoint field.
func (o *S3Profile) SetEndpoint(v string) {
	o.Endpoint.Set(&v)
}

// SetEndpointNil sets the value for Endpoint to be an explicit nil
func (o *S3Profile) SetEndpointNil() {
	o.Endpoint.Set(nil)
}

// UnsetEndpoint ensures that no value is present for Endpoint, not even an explicit nil
func (o *S3Profile) UnsetEndpoint() {
	o.Endpoint.Unset()
}

// GetFlavor returns the Flavor field value if set, zero value otherwise.
func (o *S3Profile) GetFlavor() S3Flavor {
	if o == nil || IsNil(o.Flavor) {
		var ret S3Flavor
		return ret
	}
	return *o.Flavor
}

// GetFlavorOk returns a tuple with the Flavor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Profile) GetFlavorOk() (*S3Flavor, bool) {
	if o == nil || IsNil(o.Flavor) {
		return nil, false
	}
	return o.Flavor, true
}

// HasFlavor returns a boolean if a field has been set.
func (o *S3Profile) HasFlavor() bool {
	if o != nil && !IsNil(o.Flavor) {
		return true
	}

	return false
}

// SetFlavor gets a reference to the given S3Flavor and assigns it to the Flavor field.
func (o *S3Profile) SetFlavor(v S3Flavor) {
	o.Flavor = &v
}

// GetKeyPrefix returns the KeyPrefix field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetKeyPrefix() string {
	if o == nil || IsNil(o.KeyPrefix.Get()) {
		var ret string
		return ret
	}
	return *o.KeyPrefix.Get()
}

// GetKeyPrefixOk returns a tuple with the KeyPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetKeyPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyPrefix.Get(), o.KeyPrefix.IsSet()
}

// HasKeyPrefix returns a boolean if a field has been set.
func (o *S3Profile) HasKeyPrefix() bool {
	if o != nil && o.KeyPrefix.IsSet() {
		return true
	}

	return false
}

// SetKeyPrefix gets a reference to the given NullableString and assigns it to the KeyPrefix field.
func (o *S3Profile) SetKeyPrefix(v string) {
	o.KeyPrefix.Set(&v)
}

// SetKeyPrefixNil sets the value for KeyPrefix to be an explicit nil
func (o *S3Profile) SetKeyPrefixNil() {
	o.KeyPrefix.Set(nil)
}

// UnsetKeyPrefix ensures that no value is present for KeyPrefix, not even an explicit nil
func (o *S3Profile) UnsetKeyPrefix() {
	o.KeyPrefix.Unset()
}

// GetLegacyMd5Behavior returns the LegacyMd5Behavior field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetLegacyMd5Behavior() bool {
	if o == nil || IsNil(o.LegacyMd5Behavior.Get()) {
		var ret bool
		return ret
	}
	return *o.LegacyMd5Behavior.Get()
}

// GetLegacyMd5BehaviorOk returns a tuple with the LegacyMd5Behavior field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetLegacyMd5BehaviorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.LegacyMd5Behavior.Get(), o.LegacyMd5Behavior.IsSet()
}

// HasLegacyMd5Behavior returns a boolean if a field has been set.
func (o *S3Profile) HasLegacyMd5Behavior() bool {
	if o != nil && o.LegacyMd5Behavior.IsSet() {
		return true
	}

	return false
}

// SetLegacyMd5Behavior gets a reference to the given NullableBool and assigns it to the LegacyMd5Behavior field.
func (o *S3Profile) SetLegacyMd5Behavior(v bool) {
	o.LegacyMd5Behavior.Set(&v)
}

// SetLegacyMd5BehaviorNil sets the value for LegacyMd5Behavior to be an explicit nil
func (o *S3Profile) SetLegacyMd5BehaviorNil() {
	o.LegacyMd5Behavior.Set(nil)
}

// UnsetLegacyMd5Behavior ensures that no value is present for LegacyMd5Behavior, not even an explicit nil
func (o *S3Profile) UnsetLegacyMd5Behavior() {
	o.LegacyMd5Behavior.Unset()
}

// GetPathStyleAccess returns the PathStyleAccess field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetPathStyleAccess() bool {
	if o == nil || IsNil(o.PathStyleAccess.Get()) {
		var ret bool
		return ret
	}
	return *o.PathStyleAccess.Get()
}

// GetPathStyleAccessOk returns a tuple with the PathStyleAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetPathStyleAccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.PathStyleAccess.Get(), o.PathStyleAccess.IsSet()
}

// HasPathStyleAccess returns a boolean if a field has been set.
func (o *S3Profile) HasPathStyleAccess() bool {
	if o != nil && o.PathStyleAccess.IsSet() {
		return true
	}

	return false
}

// SetPathStyleAccess gets a reference to the given NullableBool and assigns it to the PathStyleAccess field.
func (o *S3Profile) SetPathStyleAccess(v bool) {
	o.PathStyleAccess.Set(&v)
}

// SetPathStyleAccessNil sets the value for PathStyleAccess to be an explicit nil
func (o *S3Profile) SetPathStyleAccessNil() {
	o.PathStyleAccess.Set(nil)
}

// UnsetPathStyleAccess ensures that no value is present for PathStyleAccess, not even an explicit nil
func (o *S3Profile) UnsetPathStyleAccess() {
	o.PathStyleAccess.Unset()
}

// GetPushS3DeleteDisabled returns the PushS3DeleteDisabled field value if set, zero value otherwise.
func (o *S3Profile) GetPushS3DeleteDisabled() bool {
	if o == nil || IsNil(o.PushS3DeleteDisabled) {
		var ret bool
		return ret
	}
	return *o.PushS3DeleteDisabled
}

// GetPushS3DeleteDisabledOk returns a tuple with the PushS3DeleteDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Profile) GetPushS3DeleteDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.PushS3DeleteDisabled) {
		return nil, false
	}
	return o.PushS3DeleteDisabled, true
}

// HasPushS3DeleteDisabled returns a boolean if a field has been set.
func (o *S3Profile) HasPushS3DeleteDisabled() bool {
	if o != nil && !IsNil(o.PushS3DeleteDisabled) {
		return true
	}

	return false
}

// SetPushS3DeleteDisabled gets a reference to the given bool and assigns it to the PushS3DeleteDisabled field.
func (o *S3Profile) SetPushS3DeleteDisabled(v bool) {
	o.PushS3DeleteDisabled = &v
}

// GetRegion returns the Region field value
func (o *S3Profile) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *S3Profile) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *S3Profile) SetRegion(v string) {
	o.Region = v
}

// GetRemoteSigningEnabled returns the RemoteSigningEnabled field value if set, zero value otherwise.
func (o *S3Profile) GetRemoteSigningEnabled() bool {
	if o == nil || IsNil(o.RemoteSigningEnabled) {
		var ret bool
		return ret
	}
	return *o.RemoteSigningEnabled
}

// GetRemoteSigningEnabledOk returns a tuple with the RemoteSigningEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Profile) GetRemoteSigningEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.RemoteSigningEnabled) {
		return nil, false
	}
	return o.RemoteSigningEnabled, true
}

// HasRemoteSigningEnabled returns a boolean if a field has been set.
func (o *S3Profile) HasRemoteSigningEnabled() bool {
	if o != nil && !IsNil(o.RemoteSigningEnabled) {
		return true
	}

	return false
}

// SetRemoteSigningEnabled gets a reference to the given bool and assigns it to the RemoteSigningEnabled field.
func (o *S3Profile) SetRemoteSigningEnabled(v bool) {
	o.RemoteSigningEnabled = &v
}

// GetRemoteSigningUrlStyle returns the RemoteSigningUrlStyle field value if set, zero value otherwise.
func (o *S3Profile) GetRemoteSigningUrlStyle() S3UrlStyleDetectionMode {
	if o == nil || IsNil(o.RemoteSigningUrlStyle) {
		var ret S3UrlStyleDetectionMode
		return ret
	}
	return *o.RemoteSigningUrlStyle
}

// GetRemoteSigningUrlStyleOk returns a tuple with the RemoteSigningUrlStyle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Profile) GetRemoteSigningUrlStyleOk() (*S3UrlStyleDetectionMode, bool) {
	if o == nil || IsNil(o.RemoteSigningUrlStyle) {
		return nil, false
	}
	return o.RemoteSigningUrlStyle, true
}

// HasRemoteSigningUrlStyle returns a boolean if a field has been set.
func (o *S3Profile) HasRemoteSigningUrlStyle() bool {
	if o != nil && !IsNil(o.RemoteSigningUrlStyle) {
		return true
	}

	return false
}

// SetRemoteSigningUrlStyle gets a reference to the given S3UrlStyleDetectionMode and assigns it to the RemoteSigningUrlStyle field.
func (o *S3Profile) SetRemoteSigningUrlStyle(v S3UrlStyleDetectionMode) {
	o.RemoteSigningUrlStyle = &v
}

// GetStorageLayout returns the StorageLayout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetStorageLayout() StorageLayout {
	if o == nil || IsNil(o.StorageLayout.Get()) {
		var ret StorageLayout
		return ret
	}
	return *o.StorageLayout.Get()
}

// GetStorageLayoutOk returns a tuple with the StorageLayout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetStorageLayoutOk() (*StorageLayout, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageLayout.Get(), o.StorageLayout.IsSet()
}

// HasStorageLayout returns a boolean if a field has been set.
func (o *S3Profile) HasStorageLayout() bool {
	if o != nil && o.StorageLayout.IsSet() {
		return true
	}

	return false
}

// SetStorageLayout gets a reference to the given NullableStorageLayout and assigns it to the StorageLayout field.
func (o *S3Profile) SetStorageLayout(v StorageLayout) {
	o.StorageLayout.Set(&v)
}

// SetStorageLayoutNil sets the value for StorageLayout to be an explicit nil
func (o *S3Profile) SetStorageLayoutNil() {
	o.StorageLayout.Set(nil)
}

// UnsetStorageLayout ensures that no value is present for StorageLayout, not even an explicit nil
func (o *S3Profile) UnsetStorageLayout() {
	o.StorageLayout.Unset()
}

// GetStsEnabled returns the StsEnabled field value
func (o *S3Profile) GetStsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.StsEnabled
}

// GetStsEnabledOk returns a tuple with the StsEnabled field value
// and a boolean to check if the value has been set.
func (o *S3Profile) GetStsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StsEnabled, true
}

// SetStsEnabled sets field value
func (o *S3Profile) SetStsEnabled(v bool) {
	o.StsEnabled = v
}

// GetStsEndpoint returns the StsEndpoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetStsEndpoint() string {
	if o == nil || IsNil(o.StsEndpoint.Get()) {
		var ret string
		return ret
	}
	return *o.StsEndpoint.Get()
}

// GetStsEndpointOk returns a tuple with the StsEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetStsEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StsEndpoint.Get(), o.StsEndpoint.IsSet()
}

// HasStsEndpoint returns a boolean if a field has been set.
func (o *S3Profile) HasStsEndpoint() bool {
	if o != nil && o.StsEndpoint.IsSet() {
		return true
	}

	return false
}

// SetStsEndpoint gets a reference to the given NullableString and assigns it to the StsEndpoint field.
func (o *S3Profile) SetStsEndpoint(v string) {
	o.StsEndpoint.Set(&v)
}

// SetStsEndpointNil sets the value for StsEndpoint to be an explicit nil
func (o *S3Profile) SetStsEndpointNil() {
	o.StsEndpoint.Set(nil)
}

// UnsetStsEndpoint ensures that no value is present for StsEndpoint, not even an explicit nil
func (o *S3Profile) UnsetStsEndpoint() {
	o.StsEndpoint.Unset()
}

// GetStsRoleArn returns the StsRoleArn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3Profile) GetStsRoleArn() string {
	if o == nil || IsNil(o.StsRoleArn.Get()) {
		var ret string
		return ret
	}
	return *o.StsRoleArn.Get()
}

// GetStsRoleArnOk returns a tuple with the StsRoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3Profile) GetStsRoleArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StsRoleArn.Get(), o.StsRoleArn.IsSet()
}

// HasStsRoleArn returns a boolean if a field has been set.
func (o *S3Profile) HasStsRoleArn() bool {
	if o != nil && o.StsRoleArn.IsSet() {
		return true
	}

	return false
}

// SetStsRoleArn gets a reference to the given NullableString and assigns it to the StsRoleArn field.
func (o *S3Profile) SetStsRoleArn(v string) {
	o.StsRoleArn.Set(&v)
}

// SetStsRoleArnNil sets the value for StsRoleArn to be an explicit nil
func (o *S3Profile) SetStsRoleArnNil() {
	o.StsRoleArn.Set(nil)
}

// UnsetStsRoleArn ensures that no value is present for StsRoleArn, not even an explicit nil
func (o *S3Profile) UnsetStsRoleArn() {
	o.StsRoleArn.Unset()
}

// GetStsSessionTags returns the StsSessionTags field value if set, zero value otherwise.
func (o *S3Profile) GetStsSessionTags() map[string]string {
	if o == nil || IsNil(o.StsSessionTags) {
		var ret map[string]string
		return ret
	}
	return o.StsSessionTags
}

// GetStsSessionTagsOk returns a tuple with the StsSessionTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Profile) GetStsSessionTagsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.StsSessionTags) {
		return map[string]string{}, false
	}
	return o.StsSessionTags, true
}

// HasStsSessionTags returns a boolean if a field has been set.
func (o *S3Profile) HasStsSessionTags() bool {
	if o != nil && !IsNil(o.StsSessionTags) {
		return true
	}

	return false
}

// SetStsSessionTags gets a reference to the given map[string]string and assigns it to the StsSessionTags field.
func (o *S3Profile) SetStsSessionTags(v map[string]string) {
	o.StsSessionTags = v
}

// GetStsTokenValiditySeconds returns the StsTokenValiditySeconds field value if set, zero value otherwise.
func (o *S3Profile) GetStsTokenValiditySeconds() int64 {
	if o == nil || IsNil(o.StsTokenValiditySeconds) {
		var ret int64
		return ret
	}
	return *o.StsTokenValiditySeconds
}

// GetStsTokenValiditySecondsOk returns a tuple with the StsTokenValiditySeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Profile) GetStsTokenValiditySecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.StsTokenValiditySeconds) {
		return nil, false
	}
	return o.StsTokenValiditySeconds, true
}

// HasStsTokenValiditySeconds returns a boolean if a field has been set.
func (o *S3Profile) HasStsTokenValiditySeconds() bool {
	if o != nil && !IsNil(o.StsTokenValiditySeconds) {
		return true
	}

	return false
}

// SetStsTokenValiditySeconds gets a reference to the given int64 and assigns it to the StsTokenValiditySeconds field.
func (o *S3Profile) SetStsTokenValiditySeconds(v int64) {
	o.StsTokenValiditySeconds = &v
}

func (o S3Profile) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3Profile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowAlternativeProtocols.IsSet() {
		toSerialize["allow-alternative-protocols"] = o.AllowAlternativeProtocols.Get()
	}
	if o.AssumeRoleArn.IsSet() {
		toSerialize["assume-role-arn"] = o.AssumeRoleArn.Get()
	}
	if o.AwsKmsKeyArn.IsSet() {
		toSerialize["aws-kms-key-arn"] = o.AwsKmsKeyArn.Get()
	}
	toSerialize["bucket"] = o.Bucket
	if o.Endpoint.IsSet() {
		toSerialize["endpoint"] = o.Endpoint.Get()
	}
	if !IsNil(o.Flavor) {
		toSerialize["flavor"] = o.Flavor
	}
	if o.KeyPrefix.IsSet() {
		toSerialize["key-prefix"] = o.KeyPrefix.Get()
	}
	if o.LegacyMd5Behavior.IsSet() {
		toSerialize["legacy-md5-behavior"] = o.LegacyMd5Behavior.Get()
	}
	if o.PathStyleAccess.IsSet() {
		toSerialize["path-style-access"] = o.PathStyleAccess.Get()
	}
	if !IsNil(o.PushS3DeleteDisabled) {
		toSerialize["push-s3-delete-disabled"] = o.PushS3DeleteDisabled
	}
	toSerialize["region"] = o.Region
	if !IsNil(o.RemoteSigningEnabled) {
		toSerialize["remote-signing-enabled"] = o.RemoteSigningEnabled
	}
	if !IsNil(o.RemoteSigningUrlStyle) {
		toSerialize["remote-signing-url-style"] = o.RemoteSigningUrlStyle
	}
	if o.StorageLayout.IsSet() {
		toSerialize["storage-layout"] = o.StorageLayout.Get()
	}
	toSerialize["sts-enabled"] = o.StsEnabled
	if o.StsEndpoint.IsSet() {
		toSerialize["sts-endpoint"] = o.StsEndpoint.Get()
	}
	if o.StsRoleArn.IsSet() {
		toSerialize["sts-role-arn"] = o.StsRoleArn.Get()
	}
	if !IsNil(o.StsSessionTags) {
		toSerialize["sts-session-tags"] = o.StsSessionTags
	}
	if !IsNil(o.StsTokenValiditySeconds) {
		toSerialize["sts-token-validity-seconds"] = o.StsTokenValiditySeconds
	}
	return toSerialize, nil
}

func (o *S3Profile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bucket",
		"region",
		"sts-enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varS3Profile := _S3Profile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varS3Profile)

	if err != nil {
		return err
	}

	*o = S3Profile(varS3Profile)

	return err
}

type NullableS3Profile struct {
	value *S3Profile
	isSet bool
}

func (v NullableS3Profile) Get() *S3Profile {
	return v.value
}

func (v *NullableS3Profile) Set(val *S3Profile) {
	v.value = val
	v.isSet = true
}

func (v NullableS3Profile) IsSet() bool {
	return v.isSet
}

func (v *NullableS3Profile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3Profile(val *S3Profile) *NullableS3Profile {
	return &NullableS3Profile{value: val, isSet: true}
}

func (v NullableS3Profile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3Profile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
