/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ListDeletedTabularsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDeletedTabularsResponse{}

// ListDeletedTabularsResponse struct for ListDeletedTabularsResponse
type ListDeletedTabularsResponse struct {
	// Token to fetch the next page
	NextPageToken NullableString `json:"next-page-token,omitempty"`
	// List of tabulars
	Tabulars []DeletedTabularResponse `json:"tabulars"`
}

type _ListDeletedTabularsResponse ListDeletedTabularsResponse

// NewListDeletedTabularsResponse instantiates a new ListDeletedTabularsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDeletedTabularsResponse(tabulars []DeletedTabularResponse) *ListDeletedTabularsResponse {
	this := ListDeletedTabularsResponse{}
	this.Tabulars = tabulars
	return &this
}

// NewListDeletedTabularsResponseWithDefaults instantiates a new ListDeletedTabularsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDeletedTabularsResponseWithDefaults() *ListDeletedTabularsResponse {
	this := ListDeletedTabularsResponse{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListDeletedTabularsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken.Get()) {
		var ret string
		return ret
	}
	return *o.NextPageToken.Get()
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListDeletedTabularsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPageToken.Get(), o.NextPageToken.IsSet()
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListDeletedTabularsResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken.IsSet() {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given NullableString and assigns it to the NextPageToken field.
func (o *ListDeletedTabularsResponse) SetNextPageToken(v string) {
	o.NextPageToken.Set(&v)
}

// SetNextPageTokenNil sets the value for NextPageToken to be an explicit nil
func (o *ListDeletedTabularsResponse) SetNextPageTokenNil() {
	o.NextPageToken.Set(nil)
}

// UnsetNextPageToken ensures that no value is present for NextPageToken, not even an explicit nil
func (o *ListDeletedTabularsResponse) UnsetNextPageToken() {
	o.NextPageToken.Unset()
}

// GetTabulars returns the Tabulars field value
func (o *ListDeletedTabularsResponse) GetTabulars() []DeletedTabularResponse {
	if o == nil {
		var ret []DeletedTabularResponse
		return ret
	}

	return o.Tabulars
}

// GetTabularsOk returns a tuple with the Tabulars field value
// and a boolean to check if the value has been set.
func (o *ListDeletedTabularsResponse) GetTabularsOk() ([]DeletedTabularResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tabulars, true
}

// SetTabulars sets field value
func (o *ListDeletedTabularsResponse) SetTabulars(v []DeletedTabularResponse) {
	o.Tabulars = v
}

func (o ListDeletedTabularsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDeletedTabularsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NextPageToken.IsSet() {
		toSerialize["next-page-token"] = o.NextPageToken.Get()
	}
	toSerialize["tabulars"] = o.Tabulars
	return toSerialize, nil
}

func (o *ListDeletedTabularsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tabulars",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDeletedTabularsResponse := _ListDeletedTabularsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListDeletedTabularsResponse)

	if err != nil {
		return err
	}

	*o = ListDeletedTabularsResponse(varListDeletedTabularsResponse)

	return err
}

type NullableListDeletedTabularsResponse struct {
	value *ListDeletedTabularsResponse
	isSet bool
}

func (v NullableListDeletedTabularsResponse) Get() *ListDeletedTabularsResponse {
	return v.value
}

func (v *NullableListDeletedTabularsResponse) Set(val *ListDeletedTabularsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListDeletedTabularsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListDeletedTabularsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDeletedTabularsResponse(val *ListDeletedTabularsResponse) *NullableListDeletedTabularsResponse {
	return &NullableListDeletedTabularsResponse{value: val, isSet: true}
}

func (v NullableListDeletedTabularsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDeletedTabularsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
