/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProjectAssignmentSecurityAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAssignmentSecurityAdmin{}

// ProjectAssignmentSecurityAdmin struct for ProjectAssignmentSecurityAdmin
type ProjectAssignmentSecurityAdmin struct {
	// Id of the user
	User string `json:"user"`
	// Id of the role
	Role string `json:"role"`
	Type string `json:"type"`
}

type _ProjectAssignmentSecurityAdmin ProjectAssignmentSecurityAdmin

// NewProjectAssignmentSecurityAdmin instantiates a new ProjectAssignmentSecurityAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAssignmentSecurityAdmin(user string, role string, type_ string) *ProjectAssignmentSecurityAdmin {
	this := ProjectAssignmentSecurityAdmin{}
	this.User = user
	this.Role = role
	this.Type = type_
	return &this
}

// NewProjectAssignmentSecurityAdminWithDefaults instantiates a new ProjectAssignmentSecurityAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAssignmentSecurityAdminWithDefaults() *ProjectAssignmentSecurityAdmin {
	this := ProjectAssignmentSecurityAdmin{}
	return &this
}

// GetUser returns the User field value
func (o *ProjectAssignmentSecurityAdmin) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *ProjectAssignmentSecurityAdmin) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *ProjectAssignmentSecurityAdmin) SetUser(v string) {
	o.User = v
}

// GetRole returns the Role field value
func (o *ProjectAssignmentSecurityAdmin) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ProjectAssignmentSecurityAdmin) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ProjectAssignmentSecurityAdmin) SetRole(v string) {
	o.Role = v
}

// GetType returns the Type field value
func (o *ProjectAssignmentSecurityAdmin) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProjectAssignmentSecurityAdmin) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProjectAssignmentSecurityAdmin) SetType(v string) {
	o.Type = v
}

func (o ProjectAssignmentSecurityAdmin) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAssignmentSecurityAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User
	toSerialize["role"] = o.Role
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ProjectAssignmentSecurityAdmin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
		"role",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectAssignmentSecurityAdmin := _ProjectAssignmentSecurityAdmin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectAssignmentSecurityAdmin)

	if err != nil {
		return err
	}

	*o = ProjectAssignmentSecurityAdmin(varProjectAssignmentSecurityAdmin)

	return err
}

type NullableProjectAssignmentSecurityAdmin struct {
	value *ProjectAssignmentSecurityAdmin
	isSet bool
}

func (v NullableProjectAssignmentSecurityAdmin) Get() *ProjectAssignmentSecurityAdmin {
	return v.value
}

func (v *NullableProjectAssignmentSecurityAdmin) Set(val *ProjectAssignmentSecurityAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAssignmentSecurityAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAssignmentSecurityAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAssignmentSecurityAdmin(val *ProjectAssignmentSecurityAdmin) *NullableProjectAssignmentSecurityAdmin {
	return &NullableProjectAssignmentSecurityAdmin{value: val, isSet: true}
}

func (v NullableProjectAssignmentSecurityAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAssignmentSecurityAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
