/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LakekeeperProjectActionOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LakekeeperProjectActionOneOf2{}

// LakekeeperProjectActionOneOf2 struct for LakekeeperProjectActionOneOf2
type LakekeeperProjectActionOneOf2 struct {
	Action string `json:"action"`
}

type _LakekeeperProjectActionOneOf2 LakekeeperProjectActionOneOf2

// NewLakekeeperProjectActionOneOf2 instantiates a new LakekeeperProjectActionOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLakekeeperProjectActionOneOf2(action string) *LakekeeperProjectActionOneOf2 {
	this := LakekeeperProjectActionOneOf2{}
	this.Action = action
	return &this
}

// NewLakekeeperProjectActionOneOf2WithDefaults instantiates a new LakekeeperProjectActionOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLakekeeperProjectActionOneOf2WithDefaults() *LakekeeperProjectActionOneOf2 {
	this := LakekeeperProjectActionOneOf2{}
	return &this
}

// GetAction returns the Action field value
func (o *LakekeeperProjectActionOneOf2) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *LakekeeperProjectActionOneOf2) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *LakekeeperProjectActionOneOf2) SetAction(v string) {
	o.Action = v
}

func (o LakekeeperProjectActionOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *LakekeeperProjectActionOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLakekeeperProjectActionOneOf2 := _LakekeeperProjectActionOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLakekeeperProjectActionOneOf2)

	if err != nil {
		return err
	}

	*o = LakekeeperProjectActionOneOf2(varLakekeeperProjectActionOneOf2)

	return err
}

type NullableLakekeeperProjectActionOneOf2 struct {
	value *LakekeeperProjectActionOneOf2
	isSet bool
}

func (v NullableLakekeeperProjectActionOneOf2) Get() *LakekeeperProjectActionOneOf2 {
	return v.value
}

func (v *NullableLakekeeperProjectActionOneOf2) Set(val *LakekeeperProjectActionOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableLakekeeperProjectActionOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableLakekeeperProjectActionOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLakekeeperProjectActionOneOf2(val *LakekeeperProjectActionOneOf2) *NullableLakekeeperProjectActionOneOf2 {
	return &NullableLakekeeperProjectActionOneOf2{value: val, isSet: true}
}

func (v NullableLakekeeperProjectActionOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLakekeeperProjectActionOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
