/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LakekeeperWarehouseActionOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LakekeeperWarehouseActionOneOf3{}

// LakekeeperWarehouseActionOneOf3 struct for LakekeeperWarehouseActionOneOf3
type LakekeeperWarehouseActionOneOf3 struct {
	Action string `json:"action"`
}

type _LakekeeperWarehouseActionOneOf3 LakekeeperWarehouseActionOneOf3

// NewLakekeeperWarehouseActionOneOf3 instantiates a new LakekeeperWarehouseActionOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLakekeeperWarehouseActionOneOf3(action string) *LakekeeperWarehouseActionOneOf3 {
	this := LakekeeperWarehouseActionOneOf3{}
	this.Action = action
	return &this
}

// NewLakekeeperWarehouseActionOneOf3WithDefaults instantiates a new LakekeeperWarehouseActionOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLakekeeperWarehouseActionOneOf3WithDefaults() *LakekeeperWarehouseActionOneOf3 {
	this := LakekeeperWarehouseActionOneOf3{}
	return &this
}

// GetAction returns the Action field value
func (o *LakekeeperWarehouseActionOneOf3) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *LakekeeperWarehouseActionOneOf3) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *LakekeeperWarehouseActionOneOf3) SetAction(v string) {
	o.Action = v
}

func (o LakekeeperWarehouseActionOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LakekeeperWarehouseActionOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *LakekeeperWarehouseActionOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLakekeeperWarehouseActionOneOf3 := _LakekeeperWarehouseActionOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLakekeeperWarehouseActionOneOf3)

	if err != nil {
		return err
	}

	*o = LakekeeperWarehouseActionOneOf3(varLakekeeperWarehouseActionOneOf3)

	return err
}

type NullableLakekeeperWarehouseActionOneOf3 struct {
	value *LakekeeperWarehouseActionOneOf3
	isSet bool
}

func (v NullableLakekeeperWarehouseActionOneOf3) Get() *LakekeeperWarehouseActionOneOf3 {
	return v.value
}

func (v *NullableLakekeeperWarehouseActionOneOf3) Set(val *LakekeeperWarehouseActionOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableLakekeeperWarehouseActionOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableLakekeeperWarehouseActionOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLakekeeperWarehouseActionOneOf3(val *LakekeeperWarehouseActionOneOf3) *NullableLakekeeperWarehouseActionOneOf3 {
	return &NullableLakekeeperWarehouseActionOneOf3{value: val, isSet: true}
}

func (v NullableLakekeeperWarehouseActionOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLakekeeperWarehouseActionOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
