/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LakekeeperProjectActionOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LakekeeperProjectActionOneOf{}

// LakekeeperProjectActionOneOf struct for LakekeeperProjectActionOneOf
type LakekeeperProjectActionOneOf struct {
	Action string `json:"action"`
	// Name of the warehouse to create.
	Name NullableString `json:"name,omitempty"`
}

type _LakekeeperProjectActionOneOf LakekeeperProjectActionOneOf

// NewLakekeeperProjectActionOneOf instantiates a new LakekeeperProjectActionOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLakekeeperProjectActionOneOf(action string) *LakekeeperProjectActionOneOf {
	this := LakekeeperProjectActionOneOf{}
	this.Action = action
	return &this
}

// NewLakekeeperProjectActionOneOfWithDefaults instantiates a new LakekeeperProjectActionOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLakekeeperProjectActionOneOfWithDefaults() *LakekeeperProjectActionOneOf {
	this := LakekeeperProjectActionOneOf{}
	return &this
}

// GetAction returns the Action field value
func (o *LakekeeperProjectActionOneOf) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *LakekeeperProjectActionOneOf) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *LakekeeperProjectActionOneOf) SetAction(v string) {
	o.Action = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LakekeeperProjectActionOneOf) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LakekeeperProjectActionOneOf) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *LakekeeperProjectActionOneOf) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *LakekeeperProjectActionOneOf) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *LakekeeperProjectActionOneOf) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *LakekeeperProjectActionOneOf) UnsetName() {
	o.Name.Unset()
}

func (o LakekeeperProjectActionOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LakekeeperProjectActionOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

func (o *LakekeeperProjectActionOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLakekeeperProjectActionOneOf := _LakekeeperProjectActionOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLakekeeperProjectActionOneOf)

	if err != nil {
		return err
	}

	*o = LakekeeperProjectActionOneOf(varLakekeeperProjectActionOneOf)

	return err
}

type NullableLakekeeperProjectActionOneOf struct {
	value *LakekeeperProjectActionOneOf
	isSet bool
}

func (v NullableLakekeeperProjectActionOneOf) Get() *LakekeeperProjectActionOneOf {
	return v.value
}

func (v *NullableLakekeeperProjectActionOneOf) Set(val *LakekeeperProjectActionOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableLakekeeperProjectActionOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableLakekeeperProjectActionOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLakekeeperProjectActionOneOf(val *LakekeeperProjectActionOneOf) *NullableLakekeeperProjectActionOneOf {
	return &NullableLakekeeperProjectActionOneOf{value: val, isSet: true}
}

func (v NullableLakekeeperProjectActionOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLakekeeperProjectActionOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
