/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetLakekeeperViewActionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLakekeeperViewActionsResponse{}

// GetLakekeeperViewActionsResponse struct for GetLakekeeperViewActionsResponse
type GetLakekeeperViewActionsResponse struct {
	AllowedActions []LakekeeperViewAction `json:"allowed-actions"`
}

type _GetLakekeeperViewActionsResponse GetLakekeeperViewActionsResponse

// NewGetLakekeeperViewActionsResponse instantiates a new GetLakekeeperViewActionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLakekeeperViewActionsResponse(allowedActions []LakekeeperViewAction) *GetLakekeeperViewActionsResponse {
	this := GetLakekeeperViewActionsResponse{}
	this.AllowedActions = allowedActions
	return &this
}

// NewGetLakekeeperViewActionsResponseWithDefaults instantiates a new GetLakekeeperViewActionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLakekeeperViewActionsResponseWithDefaults() *GetLakekeeperViewActionsResponse {
	this := GetLakekeeperViewActionsResponse{}
	return &this
}

// GetAllowedActions returns the AllowedActions field value
func (o *GetLakekeeperViewActionsResponse) GetAllowedActions() []LakekeeperViewAction {
	if o == nil {
		var ret []LakekeeperViewAction
		return ret
	}

	return o.AllowedActions
}

// GetAllowedActionsOk returns a tuple with the AllowedActions field value
// and a boolean to check if the value has been set.
func (o *GetLakekeeperViewActionsResponse) GetAllowedActionsOk() ([]LakekeeperViewAction, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedActions, true
}

// SetAllowedActions sets field value
func (o *GetLakekeeperViewActionsResponse) SetAllowedActions(v []LakekeeperViewAction) {
	o.AllowedActions = v
}

func (o GetLakekeeperViewActionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allowed-actions"] = o.AllowedActions
	return toSerialize, nil
}

func (o *GetLakekeeperViewActionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allowed-actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetLakekeeperViewActionsResponse := _GetLakekeeperViewActionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetLakekeeperViewActionsResponse)

	if err != nil {
		return err
	}

	*o = GetLakekeeperViewActionsResponse(varGetLakekeeperViewActionsResponse)

	return err
}

type NullableGetLakekeeperViewActionsResponse struct {
	value *GetLakekeeperViewActionsResponse
	isSet bool
}

func (v NullableGetLakekeeperViewActionsResponse) Get() *GetLakekeeperViewActionsResponse {
	return v.value
}

func (v *NullableGetLakekeeperViewActionsResponse) Set(val *GetLakekeeperViewActionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLakekeeperViewActionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLakekeeperViewActionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLakekeeperViewActionsResponse(val *GetLakekeeperViewActionsResponse) *NullableGetLakekeeperViewActionsResponse {
	return &NullableGetLakekeeperViewActionsResponse{value: val, isSet: true}
}

func (v NullableGetLakekeeperViewActionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLakekeeperViewActionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
