/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CheckOperationWarehouse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckOperationWarehouse{}

// CheckOperationWarehouse struct for CheckOperationWarehouse
type CheckOperationWarehouse struct {
	Warehouse CheckOperationWarehouseWarehouse `json:"warehouse"`
}

type _CheckOperationWarehouse CheckOperationWarehouse

// NewCheckOperationWarehouse instantiates a new CheckOperationWarehouse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckOperationWarehouse(warehouse CheckOperationWarehouseWarehouse) *CheckOperationWarehouse {
	this := CheckOperationWarehouse{}
	this.Warehouse = warehouse
	return &this
}

// NewCheckOperationWarehouseWithDefaults instantiates a new CheckOperationWarehouse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckOperationWarehouseWithDefaults() *CheckOperationWarehouse {
	this := CheckOperationWarehouse{}
	return &this
}

// GetWarehouse returns the Warehouse field value
func (o *CheckOperationWarehouse) GetWarehouse() CheckOperationWarehouseWarehouse {
	if o == nil {
		var ret CheckOperationWarehouseWarehouse
		return ret
	}

	return o.Warehouse
}

// GetWarehouseOk returns a tuple with the Warehouse field value
// and a boolean to check if the value has been set.
func (o *CheckOperationWarehouse) GetWarehouseOk() (*CheckOperationWarehouseWarehouse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Warehouse, true
}

// SetWarehouse sets field value
func (o *CheckOperationWarehouse) SetWarehouse(v CheckOperationWarehouseWarehouse) {
	o.Warehouse = v
}

func (o CheckOperationWarehouse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["warehouse"] = o.Warehouse
	return toSerialize, nil
}

func (o *CheckOperationWarehouse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"warehouse",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckOperationWarehouse := _CheckOperationWarehouse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckOperationWarehouse)

	if err != nil {
		return err
	}

	*o = CheckOperationWarehouse(varCheckOperationWarehouse)

	return err
}

type NullableCheckOperationWarehouse struct {
	value *CheckOperationWarehouse
	isSet bool
}

func (v NullableCheckOperationWarehouse) Get() *CheckOperationWarehouse {
	return v.value
}

func (v *NullableCheckOperationWarehouse) Set(val *CheckOperationWarehouse) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckOperationWarehouse) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckOperationWarehouse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckOperationWarehouse(val *CheckOperationWarehouse) *NullableCheckOperationWarehouse {
	return &NullableCheckOperationWarehouse{value: val, isSet: true}
}

func (v NullableCheckOperationWarehouse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckOperationWarehouse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
