/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TimeWindowSelectorOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimeWindowSelectorOneOf1{}

// TimeWindowSelectorOneOf1 struct for TimeWindowSelectorOneOf1
type TimeWindowSelectorOneOf1 struct {
	// Opaque Token from previous response for paginating through time windows  Use the `next_page_token` or `previous_page_token` from a previous response
	Token string `json:"token"`
	Type  string `json:"type"`
}

type _TimeWindowSelectorOneOf1 TimeWindowSelectorOneOf1

// NewTimeWindowSelectorOneOf1 instantiates a new TimeWindowSelectorOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeWindowSelectorOneOf1(token string, type_ string) *TimeWindowSelectorOneOf1 {
	this := TimeWindowSelectorOneOf1{}
	this.Token = token
	this.Type = type_
	return &this
}

// NewTimeWindowSelectorOneOf1WithDefaults instantiates a new TimeWindowSelectorOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeWindowSelectorOneOf1WithDefaults() *TimeWindowSelectorOneOf1 {
	this := TimeWindowSelectorOneOf1{}
	return &this
}

// GetToken returns the Token field value
func (o *TimeWindowSelectorOneOf1) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *TimeWindowSelectorOneOf1) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *TimeWindowSelectorOneOf1) SetToken(v string) {
	o.Token = v
}

// GetType returns the Type field value
func (o *TimeWindowSelectorOneOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TimeWindowSelectorOneOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TimeWindowSelectorOneOf1) SetType(v string) {
	o.Type = v
}

func (o TimeWindowSelectorOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TimeWindowSelectorOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimeWindowSelectorOneOf1 := _TimeWindowSelectorOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimeWindowSelectorOneOf1)

	if err != nil {
		return err
	}

	*o = TimeWindowSelectorOneOf1(varTimeWindowSelectorOneOf1)

	return err
}

type NullableTimeWindowSelectorOneOf1 struct {
	value *TimeWindowSelectorOneOf1
	isSet bool
}

func (v NullableTimeWindowSelectorOneOf1) Get() *TimeWindowSelectorOneOf1 {
	return v.value
}

func (v *NullableTimeWindowSelectorOneOf1) Set(val *TimeWindowSelectorOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeWindowSelectorOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeWindowSelectorOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeWindowSelectorOneOf1(val *TimeWindowSelectorOneOf1) *NullableTimeWindowSelectorOneOf1 {
	return &NullableTimeWindowSelectorOneOf1{value: val, isSet: true}
}

func (v NullableTimeWindowSelectorOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeWindowSelectorOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
