/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
)

// checks if the UpdateServerAssignmentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateServerAssignmentsRequest{}

// UpdateServerAssignmentsRequest struct for UpdateServerAssignmentsRequest
type UpdateServerAssignmentsRequest struct {
	Deletes []ServerAssignment `json:"deletes,omitempty"`
	Writes  []ServerAssignment `json:"writes,omitempty"`
}

// NewUpdateServerAssignmentsRequest instantiates a new UpdateServerAssignmentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateServerAssignmentsRequest() *UpdateServerAssignmentsRequest {
	this := UpdateServerAssignmentsRequest{}
	return &this
}

// NewUpdateServerAssignmentsRequestWithDefaults instantiates a new UpdateServerAssignmentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateServerAssignmentsRequestWithDefaults() *UpdateServerAssignmentsRequest {
	this := UpdateServerAssignmentsRequest{}
	return &this
}

// GetDeletes returns the Deletes field value if set, zero value otherwise.
func (o *UpdateServerAssignmentsRequest) GetDeletes() []ServerAssignment {
	if o == nil || IsNil(o.Deletes) {
		var ret []ServerAssignment
		return ret
	}
	return o.Deletes
}

// GetDeletesOk returns a tuple with the Deletes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateServerAssignmentsRequest) GetDeletesOk() ([]ServerAssignment, bool) {
	if o == nil || IsNil(o.Deletes) {
		return nil, false
	}
	return o.Deletes, true
}

// HasDeletes returns a boolean if a field has been set.
func (o *UpdateServerAssignmentsRequest) HasDeletes() bool {
	if o != nil && !IsNil(o.Deletes) {
		return true
	}

	return false
}

// SetDeletes gets a reference to the given []ServerAssignment and assigns it to the Deletes field.
func (o *UpdateServerAssignmentsRequest) SetDeletes(v []ServerAssignment) {
	o.Deletes = v
}

// GetWrites returns the Writes field value if set, zero value otherwise.
func (o *UpdateServerAssignmentsRequest) GetWrites() []ServerAssignment {
	if o == nil || IsNil(o.Writes) {
		var ret []ServerAssignment
		return ret
	}
	return o.Writes
}

// GetWritesOk returns a tuple with the Writes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateServerAssignmentsRequest) GetWritesOk() ([]ServerAssignment, bool) {
	if o == nil || IsNil(o.Writes) {
		return nil, false
	}
	return o.Writes, true
}

// HasWrites returns a boolean if a field has been set.
func (o *UpdateServerAssignmentsRequest) HasWrites() bool {
	if o != nil && !IsNil(o.Writes) {
		return true
	}

	return false
}

// SetWrites gets a reference to the given []ServerAssignment and assigns it to the Writes field.
func (o *UpdateServerAssignmentsRequest) SetWrites(v []ServerAssignment) {
	o.Writes = v
}

func (o UpdateServerAssignmentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deletes) {
		toSerialize["deletes"] = o.Deletes
	}
	if !IsNil(o.Writes) {
		toSerialize["writes"] = o.Writes
	}
	return toSerialize, nil
}

type NullableUpdateServerAssignmentsRequest struct {
	value *UpdateServerAssignmentsRequest
	isSet bool
}

func (v NullableUpdateServerAssignmentsRequest) Get() *UpdateServerAssignmentsRequest {
	return v.value
}

func (v *NullableUpdateServerAssignmentsRequest) Set(val *UpdateServerAssignmentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateServerAssignmentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateServerAssignmentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateServerAssignmentsRequest(val *UpdateServerAssignmentsRequest) *NullableUpdateServerAssignmentsRequest {
	return &NullableUpdateServerAssignmentsRequest{value: val, isSet: true}
}

func (v NullableUpdateServerAssignmentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateServerAssignmentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
