/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NamespaceIdentOrUuidOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NamespaceIdentOrUuidOneOf1{}

// NamespaceIdentOrUuidOneOf1 struct for NamespaceIdentOrUuidOneOf1
type NamespaceIdentOrUuidOneOf1 struct {
	Namespace   []string `json:"namespace"`
	WarehouseId string   `json:"warehouse-id"`
}

type _NamespaceIdentOrUuidOneOf1 NamespaceIdentOrUuidOneOf1

// NewNamespaceIdentOrUuidOneOf1 instantiates a new NamespaceIdentOrUuidOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNamespaceIdentOrUuidOneOf1(namespace []string, warehouseId string) *NamespaceIdentOrUuidOneOf1 {
	this := NamespaceIdentOrUuidOneOf1{}
	this.Namespace = namespace
	this.WarehouseId = warehouseId
	return &this
}

// NewNamespaceIdentOrUuidOneOf1WithDefaults instantiates a new NamespaceIdentOrUuidOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamespaceIdentOrUuidOneOf1WithDefaults() *NamespaceIdentOrUuidOneOf1 {
	this := NamespaceIdentOrUuidOneOf1{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *NamespaceIdentOrUuidOneOf1) GetNamespace() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *NamespaceIdentOrUuidOneOf1) GetNamespaceOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Namespace, true
}

// SetNamespace sets field value
func (o *NamespaceIdentOrUuidOneOf1) SetNamespace(v []string) {
	o.Namespace = v
}

// GetWarehouseId returns the WarehouseId field value
func (o *NamespaceIdentOrUuidOneOf1) GetWarehouseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WarehouseId
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value
// and a boolean to check if the value has been set.
func (o *NamespaceIdentOrUuidOneOf1) GetWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarehouseId, true
}

// SetWarehouseId sets field value
func (o *NamespaceIdentOrUuidOneOf1) SetWarehouseId(v string) {
	o.WarehouseId = v
}

func (o NamespaceIdentOrUuidOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NamespaceIdentOrUuidOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["namespace"] = o.Namespace
	toSerialize["warehouse-id"] = o.WarehouseId
	return toSerialize, nil
}

func (o *NamespaceIdentOrUuidOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"warehouse-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNamespaceIdentOrUuidOneOf1 := _NamespaceIdentOrUuidOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNamespaceIdentOrUuidOneOf1)

	if err != nil {
		return err
	}

	*o = NamespaceIdentOrUuidOneOf1(varNamespaceIdentOrUuidOneOf1)

	return err
}

type NullableNamespaceIdentOrUuidOneOf1 struct {
	value *NamespaceIdentOrUuidOneOf1
	isSet bool
}

func (v NullableNamespaceIdentOrUuidOneOf1) Get() *NamespaceIdentOrUuidOneOf1 {
	return v.value
}

func (v *NullableNamespaceIdentOrUuidOneOf1) Set(val *NamespaceIdentOrUuidOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceIdentOrUuidOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceIdentOrUuidOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceIdentOrUuidOneOf1(val *NamespaceIdentOrUuidOneOf1) *NullableNamespaceIdentOrUuidOneOf1 {
	return &NullableNamespaceIdentOrUuidOneOf1{value: val, isSet: true}
}

func (v NullableNamespaceIdentOrUuidOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceIdentOrUuidOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
