/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// OpenFGARoleAction the model 'OpenFGARoleAction'
type OpenFGARoleAction string

// List of OpenFGARoleAction
const (
	OPENFGAROLEACTION_ASSUME               OpenFGARoleAction = "assume"
	OPENFGAROLEACTION_CAN_GRANT_ASSIGNEE   OpenFGARoleAction = "can_grant_assignee"
	OPENFGAROLEACTION_CAN_CHANGE_OWNERSHIP OpenFGARoleAction = "can_change_ownership"
	OPENFGAROLEACTION_READ_ASSIGNMENTS     OpenFGARoleAction = "read_assignments"
)

// All allowed values of OpenFGARoleAction enum
var AllowedOpenFGARoleActionEnumValues = []OpenFGARoleAction{
	"assume",
	"can_grant_assignee",
	"can_change_ownership",
	"read_assignments",
}

func (v *OpenFGARoleAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OpenFGARoleAction(value)
	for _, existing := range AllowedOpenFGARoleActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OpenFGARoleAction", value)
}

// NewOpenFGARoleActionFromValue returns a pointer to a valid OpenFGARoleAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOpenFGARoleActionFromValue(v string) (*OpenFGARoleAction, error) {
	ev := OpenFGARoleAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OpenFGARoleAction: valid values are %v", v, AllowedOpenFGARoleActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OpenFGARoleAction) IsValid() bool {
	for _, existing := range AllowedOpenFGARoleActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OpenFGARoleAction value
func (v OpenFGARoleAction) Ptr() *OpenFGARoleAction {
	return &v
}

type NullableOpenFGARoleAction struct {
	value *OpenFGARoleAction
	isSet bool
}

func (v NullableOpenFGARoleAction) Get() *OpenFGARoleAction {
	return v.value
}

func (v *NullableOpenFGARoleAction) Set(val *OpenFGARoleAction) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenFGARoleAction) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenFGARoleAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenFGARoleAction(val *OpenFGARoleAction) *NullableOpenFGARoleAction {
	return &NullableOpenFGARoleAction{value: val, isSet: true}
}

func (v NullableOpenFGARoleAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenFGARoleAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
