/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// StorageProfile - Storage profile for a warehouse.
type StorageProfile struct {
	StorageProfileAdls *StorageProfileAdls
	StorageProfileGcs  *StorageProfileGcs
	StorageProfileS3   *StorageProfileS3
}

// StorageProfileAdlsAsStorageProfile is a convenience function that returns StorageProfileAdls wrapped in StorageProfile
func StorageProfileAdlsAsStorageProfile(v *StorageProfileAdls) StorageProfile {
	return StorageProfile{
		StorageProfileAdls: v,
	}
}

// StorageProfileGcsAsStorageProfile is a convenience function that returns StorageProfileGcs wrapped in StorageProfile
func StorageProfileGcsAsStorageProfile(v *StorageProfileGcs) StorageProfile {
	return StorageProfile{
		StorageProfileGcs: v,
	}
}

// StorageProfileS3AsStorageProfile is a convenience function that returns StorageProfileS3 wrapped in StorageProfile
func StorageProfileS3AsStorageProfile(v *StorageProfileS3) StorageProfile {
	return StorageProfile{
		StorageProfileS3: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *StorageProfile) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into StorageProfileAdls
	err = json.Unmarshal(data, &dst.StorageProfileAdls)
	if err == nil {
		jsonStorageProfileAdls, _ := json.Marshal(dst.StorageProfileAdls)
		if string(jsonStorageProfileAdls) == "{}" { // empty struct
			dst.StorageProfileAdls = nil
		} else {
			match++
		}
	} else {
		dst.StorageProfileAdls = nil
	}

	// try to unmarshal data into StorageProfileGcs
	err = json.Unmarshal(data, &dst.StorageProfileGcs)
	if err == nil {
		jsonStorageProfileGcs, _ := json.Marshal(dst.StorageProfileGcs)
		if string(jsonStorageProfileGcs) == "{}" { // empty struct
			dst.StorageProfileGcs = nil
		} else {
			match++
		}
	} else {
		dst.StorageProfileGcs = nil
	}

	// try to unmarshal data into StorageProfileS3
	err = json.Unmarshal(data, &dst.StorageProfileS3)
	if err == nil {
		jsonStorageProfileS3, _ := json.Marshal(dst.StorageProfileS3)
		if string(jsonStorageProfileS3) == "{}" { // empty struct
			dst.StorageProfileS3 = nil
		} else {
			match++
		}
	} else {
		dst.StorageProfileS3 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.StorageProfileAdls = nil
		dst.StorageProfileGcs = nil
		dst.StorageProfileS3 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(StorageProfile)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(StorageProfile)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src StorageProfile) MarshalJSON() ([]byte, error) {
	if src.StorageProfileAdls != nil {
		return json.Marshal(&src.StorageProfileAdls)
	}

	if src.StorageProfileGcs != nil {
		return json.Marshal(&src.StorageProfileGcs)
	}

	if src.StorageProfileS3 != nil {
		return json.Marshal(&src.StorageProfileS3)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *StorageProfile) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.StorageProfileAdls != nil {
		return obj.StorageProfileAdls
	}

	if obj.StorageProfileGcs != nil {
		return obj.StorageProfileGcs
	}

	if obj.StorageProfileS3 != nil {
		return obj.StorageProfileS3
	}

	// all schemas are nil
	return nil
}

type NullableStorageProfile struct {
	value *StorageProfile
	isSet bool
}

func (v NullableStorageProfile) Get() *StorageProfile {
	return v.value
}

func (v *NullableStorageProfile) Set(val *StorageProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageProfile(val *StorageProfile) *NullableStorageProfile {
	return &NullableStorageProfile{value: val, isSet: true}
}

func (v NullableStorageProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
