/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ProjectTaskInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectTaskInfo{}

// ProjectTaskInfo struct for ProjectTaskInfo
type ProjectTaskInfo struct {
	// Current attempt number
	Attempt int32 `json:"attempt"`
	// When this task attempt was created
	CreatedAt time.Time `json:"created-at"`
	// Last heartbeat timestamp for running tasks
	LastHeartbeatAt *time.Time `json:"last-heartbeat-at,omitempty"`
	// Parent task ID if this is a sub-task
	ParentTaskId *string `json:"parent-task-id,omitempty"`
	// When the latest attempt of the task was picked up for processing by a worker.
	PickedUpAt *time.Time `json:"picked-up-at,omitempty"`
	// Progress of the task (0.0 to 1.0)
	Progress float32 `json:"progress"`
	// Project ID associated with the task
	ProjectId string `json:"project-id"`
	// Name of the queue processing this task
	QueueName string `json:"queue-name"`
	// When the latest attempt of the task is scheduled for
	ScheduledFor time.Time `json:"scheduled-for"`
	// Current status of the task
	Status TaskStatus `json:"status"`
	// Unique identifier for the task
	TaskId string `json:"task-id"`
	// When the task was last updated
	UpdatedAt *time.Time `json:"updated-at,omitempty"`
}

type _ProjectTaskInfo ProjectTaskInfo

// NewProjectTaskInfo instantiates a new ProjectTaskInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectTaskInfo(attempt int32, createdAt time.Time, progress float32, projectId string, queueName string, scheduledFor time.Time, status TaskStatus, taskId string) *ProjectTaskInfo {
	this := ProjectTaskInfo{}
	this.Attempt = attempt
	this.CreatedAt = createdAt
	this.Progress = progress
	this.ProjectId = projectId
	this.QueueName = queueName
	this.ScheduledFor = scheduledFor
	this.Status = status
	this.TaskId = taskId
	return &this
}

// NewProjectTaskInfoWithDefaults instantiates a new ProjectTaskInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectTaskInfoWithDefaults() *ProjectTaskInfo {
	this := ProjectTaskInfo{}
	return &this
}

// GetAttempt returns the Attempt field value
func (o *ProjectTaskInfo) GetAttempt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Attempt
}

// GetAttemptOk returns a tuple with the Attempt field value
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetAttemptOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempt, true
}

// SetAttempt sets field value
func (o *ProjectTaskInfo) SetAttempt(v int32) {
	o.Attempt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ProjectTaskInfo) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ProjectTaskInfo) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetLastHeartbeatAt returns the LastHeartbeatAt field value if set, zero value otherwise.
func (o *ProjectTaskInfo) GetLastHeartbeatAt() time.Time {
	if o == nil || IsNil(o.LastHeartbeatAt) {
		var ret time.Time
		return ret
	}
	return *o.LastHeartbeatAt
}

// GetLastHeartbeatAtOk returns a tuple with the LastHeartbeatAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetLastHeartbeatAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastHeartbeatAt) {
		return nil, false
	}
	return o.LastHeartbeatAt, true
}

// HasLastHeartbeatAt returns a boolean if a field has been set.
func (o *ProjectTaskInfo) HasLastHeartbeatAt() bool {
	if o != nil && !IsNil(o.LastHeartbeatAt) {
		return true
	}

	return false
}

// SetLastHeartbeatAt gets a reference to the given time.Time and assigns it to the LastHeartbeatAt field.
func (o *ProjectTaskInfo) SetLastHeartbeatAt(v time.Time) {
	o.LastHeartbeatAt = &v
}

// GetParentTaskId returns the ParentTaskId field value if set, zero value otherwise.
func (o *ProjectTaskInfo) GetParentTaskId() string {
	if o == nil || IsNil(o.ParentTaskId) {
		var ret string
		return ret
	}
	return *o.ParentTaskId
}

// GetParentTaskIdOk returns a tuple with the ParentTaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetParentTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentTaskId) {
		return nil, false
	}
	return o.ParentTaskId, true
}

// HasParentTaskId returns a boolean if a field has been set.
func (o *ProjectTaskInfo) HasParentTaskId() bool {
	if o != nil && !IsNil(o.ParentTaskId) {
		return true
	}

	return false
}

// SetParentTaskId gets a reference to the given string and assigns it to the ParentTaskId field.
func (o *ProjectTaskInfo) SetParentTaskId(v string) {
	o.ParentTaskId = &v
}

// GetPickedUpAt returns the PickedUpAt field value if set, zero value otherwise.
func (o *ProjectTaskInfo) GetPickedUpAt() time.Time {
	if o == nil || IsNil(o.PickedUpAt) {
		var ret time.Time
		return ret
	}
	return *o.PickedUpAt
}

// GetPickedUpAtOk returns a tuple with the PickedUpAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetPickedUpAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PickedUpAt) {
		return nil, false
	}
	return o.PickedUpAt, true
}

// HasPickedUpAt returns a boolean if a field has been set.
func (o *ProjectTaskInfo) HasPickedUpAt() bool {
	if o != nil && !IsNil(o.PickedUpAt) {
		return true
	}

	return false
}

// SetPickedUpAt gets a reference to the given time.Time and assigns it to the PickedUpAt field.
func (o *ProjectTaskInfo) SetPickedUpAt(v time.Time) {
	o.PickedUpAt = &v
}

// GetProgress returns the Progress field value
func (o *ProjectTaskInfo) GetProgress() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Progress
}

// GetProgressOk returns a tuple with the Progress field value
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetProgressOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Progress, true
}

// SetProgress sets field value
func (o *ProjectTaskInfo) SetProgress(v float32) {
	o.Progress = v
}

// GetProjectId returns the ProjectId field value
func (o *ProjectTaskInfo) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ProjectTaskInfo) SetProjectId(v string) {
	o.ProjectId = v
}

// GetQueueName returns the QueueName field value
func (o *ProjectTaskInfo) GetQueueName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueueName
}

// GetQueueNameOk returns a tuple with the QueueName field value
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetQueueNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueueName, true
}

// SetQueueName sets field value
func (o *ProjectTaskInfo) SetQueueName(v string) {
	o.QueueName = v
}

// GetScheduledFor returns the ScheduledFor field value
func (o *ProjectTaskInfo) GetScheduledFor() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ScheduledFor
}

// GetScheduledForOk returns a tuple with the ScheduledFor field value
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetScheduledForOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledFor, true
}

// SetScheduledFor sets field value
func (o *ProjectTaskInfo) SetScheduledFor(v time.Time) {
	o.ScheduledFor = v
}

// GetStatus returns the Status field value
func (o *ProjectTaskInfo) GetStatus() TaskStatus {
	if o == nil {
		var ret TaskStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetStatusOk() (*TaskStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ProjectTaskInfo) SetStatus(v TaskStatus) {
	o.Status = v
}

// GetTaskId returns the TaskId field value
func (o *ProjectTaskInfo) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *ProjectTaskInfo) SetTaskId(v string) {
	o.TaskId = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProjectTaskInfo) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTaskInfo) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProjectTaskInfo) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ProjectTaskInfo) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o ProjectTaskInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attempt"] = o.Attempt
	toSerialize["created-at"] = o.CreatedAt
	if !IsNil(o.LastHeartbeatAt) {
		toSerialize["last-heartbeat-at"] = o.LastHeartbeatAt
	}
	if !IsNil(o.ParentTaskId) {
		toSerialize["parent-task-id"] = o.ParentTaskId
	}
	if !IsNil(o.PickedUpAt) {
		toSerialize["picked-up-at"] = o.PickedUpAt
	}
	toSerialize["progress"] = o.Progress
	toSerialize["project-id"] = o.ProjectId
	toSerialize["queue-name"] = o.QueueName
	toSerialize["scheduled-for"] = o.ScheduledFor
	toSerialize["status"] = o.Status
	toSerialize["task-id"] = o.TaskId
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated-at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

func (o *ProjectTaskInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attempt",
		"created-at",
		"progress",
		"project-id",
		"queue-name",
		"scheduled-for",
		"status",
		"task-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectTaskInfo := _ProjectTaskInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectTaskInfo)

	if err != nil {
		return err
	}

	*o = ProjectTaskInfo(varProjectTaskInfo)

	return err
}

type NullableProjectTaskInfo struct {
	value *ProjectTaskInfo
	isSet bool
}

func (v NullableProjectTaskInfo) Get() *ProjectTaskInfo {
	return v.value
}

func (v *NullableProjectTaskInfo) Set(val *ProjectTaskInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectTaskInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectTaskInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectTaskInfo(val *ProjectTaskInfo) *NullableProjectTaskInfo {
	return &NullableProjectTaskInfo{value: val, isSet: true}
}

func (v NullableProjectTaskInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectTaskInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
