/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CatalogActionCheckOperationWarehouseWarehouse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogActionCheckOperationWarehouseWarehouse{}

// CatalogActionCheckOperationWarehouseWarehouse struct for CatalogActionCheckOperationWarehouseWarehouse
type CatalogActionCheckOperationWarehouseWarehouse struct {
	Action      LakekeeperWarehouseAction `json:"action"`
	WarehouseId string                    `json:"warehouse-id"`
}

type _CatalogActionCheckOperationWarehouseWarehouse CatalogActionCheckOperationWarehouseWarehouse

// NewCatalogActionCheckOperationWarehouseWarehouse instantiates a new CatalogActionCheckOperationWarehouseWarehouse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogActionCheckOperationWarehouseWarehouse(action LakekeeperWarehouseAction, warehouseId string) *CatalogActionCheckOperationWarehouseWarehouse {
	this := CatalogActionCheckOperationWarehouseWarehouse{}
	this.Action = action
	this.WarehouseId = warehouseId
	return &this
}

// NewCatalogActionCheckOperationWarehouseWarehouseWithDefaults instantiates a new CatalogActionCheckOperationWarehouseWarehouse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogActionCheckOperationWarehouseWarehouseWithDefaults() *CatalogActionCheckOperationWarehouseWarehouse {
	this := CatalogActionCheckOperationWarehouseWarehouse{}
	return &this
}

// GetAction returns the Action field value
func (o *CatalogActionCheckOperationWarehouseWarehouse) GetAction() LakekeeperWarehouseAction {
	if o == nil {
		var ret LakekeeperWarehouseAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CatalogActionCheckOperationWarehouseWarehouse) GetActionOk() (*LakekeeperWarehouseAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CatalogActionCheckOperationWarehouseWarehouse) SetAction(v LakekeeperWarehouseAction) {
	o.Action = v
}

// GetWarehouseId returns the WarehouseId field value
func (o *CatalogActionCheckOperationWarehouseWarehouse) GetWarehouseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WarehouseId
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value
// and a boolean to check if the value has been set.
func (o *CatalogActionCheckOperationWarehouseWarehouse) GetWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarehouseId, true
}

// SetWarehouseId sets field value
func (o *CatalogActionCheckOperationWarehouseWarehouse) SetWarehouseId(v string) {
	o.WarehouseId = v
}

func (o CatalogActionCheckOperationWarehouseWarehouse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogActionCheckOperationWarehouseWarehouse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["warehouse-id"] = o.WarehouseId
	return toSerialize, nil
}

func (o *CatalogActionCheckOperationWarehouseWarehouse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"warehouse-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogActionCheckOperationWarehouseWarehouse := _CatalogActionCheckOperationWarehouseWarehouse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogActionCheckOperationWarehouseWarehouse)

	if err != nil {
		return err
	}

	*o = CatalogActionCheckOperationWarehouseWarehouse(varCatalogActionCheckOperationWarehouseWarehouse)

	return err
}

type NullableCatalogActionCheckOperationWarehouseWarehouse struct {
	value *CatalogActionCheckOperationWarehouseWarehouse
	isSet bool
}

func (v NullableCatalogActionCheckOperationWarehouseWarehouse) Get() *CatalogActionCheckOperationWarehouseWarehouse {
	return v.value
}

func (v *NullableCatalogActionCheckOperationWarehouseWarehouse) Set(val *CatalogActionCheckOperationWarehouseWarehouse) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogActionCheckOperationWarehouseWarehouse) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogActionCheckOperationWarehouseWarehouse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogActionCheckOperationWarehouseWarehouse(val *CatalogActionCheckOperationWarehouseWarehouse) *NullableCatalogActionCheckOperationWarehouseWarehouse {
	return &NullableCatalogActionCheckOperationWarehouseWarehouse{value: val, isSet: true}
}

func (v NullableCatalogActionCheckOperationWarehouseWarehouse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogActionCheckOperationWarehouseWarehouse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
