/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ViewAssignmentManageGrantsUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewAssignmentManageGrantsUser{}

// ViewAssignmentManageGrantsUser struct for ViewAssignmentManageGrantsUser
type ViewAssignmentManageGrantsUser struct {
	// Id of the user
	User string `json:"user"`
	Type string `json:"type"`
}

type _ViewAssignmentManageGrantsUser ViewAssignmentManageGrantsUser

// NewViewAssignmentManageGrantsUser instantiates a new ViewAssignmentManageGrantsUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewAssignmentManageGrantsUser(user string, type_ string) *ViewAssignmentManageGrantsUser {
	this := ViewAssignmentManageGrantsUser{}
	this.User = user
	this.Type = type_
	return &this
}

// NewViewAssignmentManageGrantsUserWithDefaults instantiates a new ViewAssignmentManageGrantsUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewAssignmentManageGrantsUserWithDefaults() *ViewAssignmentManageGrantsUser {
	this := ViewAssignmentManageGrantsUser{}
	return &this
}

// GetUser returns the User field value
func (o *ViewAssignmentManageGrantsUser) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *ViewAssignmentManageGrantsUser) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *ViewAssignmentManageGrantsUser) SetUser(v string) {
	o.User = v
}

// GetType returns the Type field value
func (o *ViewAssignmentManageGrantsUser) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ViewAssignmentManageGrantsUser) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ViewAssignmentManageGrantsUser) SetType(v string) {
	o.Type = v
}

func (o ViewAssignmentManageGrantsUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewAssignmentManageGrantsUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ViewAssignmentManageGrantsUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varViewAssignmentManageGrantsUser := _ViewAssignmentManageGrantsUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varViewAssignmentManageGrantsUser)

	if err != nil {
		return err
	}

	*o = ViewAssignmentManageGrantsUser(varViewAssignmentManageGrantsUser)

	return err
}

type NullableViewAssignmentManageGrantsUser struct {
	value *ViewAssignmentManageGrantsUser
	isSet bool
}

func (v NullableViewAssignmentManageGrantsUser) Get() *ViewAssignmentManageGrantsUser {
	return v.value
}

func (v *NullableViewAssignmentManageGrantsUser) Set(val *ViewAssignmentManageGrantsUser) {
	v.value = val
	v.isSet = true
}

func (v NullableViewAssignmentManageGrantsUser) IsSet() bool {
	return v.isSet
}

func (v *NullableViewAssignmentManageGrantsUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewAssignmentManageGrantsUser(val *ViewAssignmentManageGrantsUser) *NullableViewAssignmentManageGrantsUser {
	return &NullableViewAssignmentManageGrantsUser{value: val, isSet: true}
}

func (v NullableViewAssignmentManageGrantsUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewAssignmentManageGrantsUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
