/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetProjectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectResponse{}

// GetProjectResponse struct for GetProjectResponse
type GetProjectResponse struct {
	// ID of the project.
	ProjectId string `json:"project-id"`
	// Name of the project
	ProjectName string `json:"project-name"`
}

type _GetProjectResponse GetProjectResponse

// NewGetProjectResponse instantiates a new GetProjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectResponse(projectId string, projectName string) *GetProjectResponse {
	this := GetProjectResponse{}
	this.ProjectId = projectId
	this.ProjectName = projectName
	return &this
}

// NewGetProjectResponseWithDefaults instantiates a new GetProjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectResponseWithDefaults() *GetProjectResponse {
	this := GetProjectResponse{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *GetProjectResponse) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GetProjectResponse) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GetProjectResponse) SetProjectId(v string) {
	o.ProjectId = v
}

// GetProjectName returns the ProjectName field value
func (o *GetProjectResponse) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *GetProjectResponse) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *GetProjectResponse) SetProjectName(v string) {
	o.ProjectName = v
}

func (o GetProjectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project-id"] = o.ProjectId
	toSerialize["project-name"] = o.ProjectName
	return toSerialize, nil
}

func (o *GetProjectResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project-id",
		"project-name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetProjectResponse := _GetProjectResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetProjectResponse)

	if err != nil {
		return err
	}

	*o = GetProjectResponse(varGetProjectResponse)

	return err
}

type NullableGetProjectResponse struct {
	value *GetProjectResponse
	isSet bool
}

func (v NullableGetProjectResponse) Get() *GetProjectResponse {
	return v.value
}

func (v *NullableGetProjectResponse) Set(val *GetProjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectResponse(val *GetProjectResponse) *NullableGetProjectResponse {
	return &NullableGetProjectResponse{value: val, isSet: true}
}

func (v NullableGetProjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
