/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StorageCredentialTypeOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageCredentialTypeOneOf{}

// StorageCredentialTypeOneOf S3 credential type
type StorageCredentialTypeOneOf struct {
	// S3 credential type
	CredentialType S3CredentialType `json:"credential-type"`
	Type           string           `json:"type"`
}

type _StorageCredentialTypeOneOf StorageCredentialTypeOneOf

// NewStorageCredentialTypeOneOf instantiates a new StorageCredentialTypeOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageCredentialTypeOneOf(credentialType S3CredentialType, type_ string) *StorageCredentialTypeOneOf {
	this := StorageCredentialTypeOneOf{}
	this.CredentialType = credentialType
	this.Type = type_
	return &this
}

// NewStorageCredentialTypeOneOfWithDefaults instantiates a new StorageCredentialTypeOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageCredentialTypeOneOfWithDefaults() *StorageCredentialTypeOneOf {
	this := StorageCredentialTypeOneOf{}
	return &this
}

// GetCredentialType returns the CredentialType field value
func (o *StorageCredentialTypeOneOf) GetCredentialType() S3CredentialType {
	if o == nil {
		var ret S3CredentialType
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *StorageCredentialTypeOneOf) GetCredentialTypeOk() (*S3CredentialType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *StorageCredentialTypeOneOf) SetCredentialType(v S3CredentialType) {
	o.CredentialType = v
}

// GetType returns the Type field value
func (o *StorageCredentialTypeOneOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StorageCredentialTypeOneOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StorageCredentialTypeOneOf) SetType(v string) {
	o.Type = v
}

func (o StorageCredentialTypeOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageCredentialTypeOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credential-type"] = o.CredentialType
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *StorageCredentialTypeOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credential-type",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageCredentialTypeOneOf := _StorageCredentialTypeOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStorageCredentialTypeOneOf)

	if err != nil {
		return err
	}

	*o = StorageCredentialTypeOneOf(varStorageCredentialTypeOneOf)

	return err
}

type NullableStorageCredentialTypeOneOf struct {
	value *StorageCredentialTypeOneOf
	isSet bool
}

func (v NullableStorageCredentialTypeOneOf) Get() *StorageCredentialTypeOneOf {
	return v.value
}

func (v *NullableStorageCredentialTypeOneOf) Set(val *StorageCredentialTypeOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageCredentialTypeOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageCredentialTypeOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageCredentialTypeOneOf(val *StorageCredentialTypeOneOf) *NullableStorageCredentialTypeOneOf {
	return &NullableStorageCredentialTypeOneOf{value: val, isSet: true}
}

func (v NullableStorageCredentialTypeOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageCredentialTypeOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
