/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
)

// checks if the S3AwsSystemIdentityCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3AwsSystemIdentityCredential{}

// S3AwsSystemIdentityCredential struct for S3AwsSystemIdentityCredential
type S3AwsSystemIdentityCredential struct {
	ExternalId *string `json:"external-id,omitempty"`
}

// NewS3AwsSystemIdentityCredential instantiates a new S3AwsSystemIdentityCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3AwsSystemIdentityCredential() *S3AwsSystemIdentityCredential {
	this := S3AwsSystemIdentityCredential{}
	return &this
}

// NewS3AwsSystemIdentityCredentialWithDefaults instantiates a new S3AwsSystemIdentityCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3AwsSystemIdentityCredentialWithDefaults() *S3AwsSystemIdentityCredential {
	this := S3AwsSystemIdentityCredential{}
	return &this
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *S3AwsSystemIdentityCredential) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3AwsSystemIdentityCredential) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *S3AwsSystemIdentityCredential) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *S3AwsSystemIdentityCredential) SetExternalId(v string) {
	o.ExternalId = &v
}

func (o S3AwsSystemIdentityCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalId) {
		toSerialize["external-id"] = o.ExternalId
	}
	return toSerialize, nil
}

type NullableS3AwsSystemIdentityCredential struct {
	value *S3AwsSystemIdentityCredential
	isSet bool
}

func (v NullableS3AwsSystemIdentityCredential) Get() *S3AwsSystemIdentityCredential {
	return v.value
}

func (v *NullableS3AwsSystemIdentityCredential) Set(val *S3AwsSystemIdentityCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableS3AwsSystemIdentityCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableS3AwsSystemIdentityCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3AwsSystemIdentityCredential(val *S3AwsSystemIdentityCredential) *NullableS3AwsSystemIdentityCredential {
	return &NullableS3AwsSystemIdentityCredential{value: val, isSet: true}
}

func (v NullableS3AwsSystemIdentityCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3AwsSystemIdentityCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
