/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// ViewAssignmentOwnership - struct for ViewAssignmentOwnership
type ViewAssignmentOwnership struct {
	ViewAssignmentOwnershipRole *ViewAssignmentOwnershipRole
	ViewAssignmentOwnershipUser *ViewAssignmentOwnershipUser
}

// ViewAssignmentOwnershipRoleAsViewAssignmentOwnership is a convenience function that returns ViewAssignmentOwnershipRole wrapped in ViewAssignmentOwnership
func ViewAssignmentOwnershipRoleAsViewAssignmentOwnership(v *ViewAssignmentOwnershipRole) ViewAssignmentOwnership {
	return ViewAssignmentOwnership{
		ViewAssignmentOwnershipRole: v,
	}
}

// ViewAssignmentOwnershipUserAsViewAssignmentOwnership is a convenience function that returns ViewAssignmentOwnershipUser wrapped in ViewAssignmentOwnership
func ViewAssignmentOwnershipUserAsViewAssignmentOwnership(v *ViewAssignmentOwnershipUser) ViewAssignmentOwnership {
	return ViewAssignmentOwnership{
		ViewAssignmentOwnershipUser: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ViewAssignmentOwnership) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ViewAssignmentOwnershipRole
	err = json.Unmarshal(data, &dst.ViewAssignmentOwnershipRole)
	if err == nil {
		jsonViewAssignmentOwnershipRole, _ := json.Marshal(dst.ViewAssignmentOwnershipRole)
		if string(jsonViewAssignmentOwnershipRole) == "{}" { // empty struct
			dst.ViewAssignmentOwnershipRole = nil
		} else {
			match++
		}
	} else {
		dst.ViewAssignmentOwnershipRole = nil
	}

	// try to unmarshal data into ViewAssignmentOwnershipUser
	err = json.Unmarshal(data, &dst.ViewAssignmentOwnershipUser)
	if err == nil {
		jsonViewAssignmentOwnershipUser, _ := json.Marshal(dst.ViewAssignmentOwnershipUser)
		if string(jsonViewAssignmentOwnershipUser) == "{}" { // empty struct
			dst.ViewAssignmentOwnershipUser = nil
		} else {
			match++
		}
	} else {
		dst.ViewAssignmentOwnershipUser = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ViewAssignmentOwnershipRole = nil
		dst.ViewAssignmentOwnershipUser = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ViewAssignmentOwnership)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ViewAssignmentOwnership)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ViewAssignmentOwnership) MarshalJSON() ([]byte, error) {
	if src.ViewAssignmentOwnershipRole != nil {
		return json.Marshal(&src.ViewAssignmentOwnershipRole)
	}

	if src.ViewAssignmentOwnershipUser != nil {
		return json.Marshal(&src.ViewAssignmentOwnershipUser)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ViewAssignmentOwnership) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ViewAssignmentOwnershipRole != nil {
		return obj.ViewAssignmentOwnershipRole
	}

	if obj.ViewAssignmentOwnershipUser != nil {
		return obj.ViewAssignmentOwnershipUser
	}

	// all schemas are nil
	return nil
}

type NullableViewAssignmentOwnership struct {
	value *ViewAssignmentOwnership
	isSet bool
}

func (v NullableViewAssignmentOwnership) Get() *ViewAssignmentOwnership {
	return v.value
}

func (v *NullableViewAssignmentOwnership) Set(val *ViewAssignmentOwnership) {
	v.value = val
	v.isSet = true
}

func (v NullableViewAssignmentOwnership) IsSet() bool {
	return v.isSet
}

func (v *NullableViewAssignmentOwnership) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewAssignmentOwnership(val *ViewAssignmentOwnership) *NullableViewAssignmentOwnership {
	return &NullableViewAssignmentOwnership{value: val, isSet: true}
}

func (v NullableViewAssignmentOwnership) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewAssignmentOwnership) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
