/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
)

// checks if the UpdateNamespaceAssignmentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNamespaceAssignmentsRequest{}

// UpdateNamespaceAssignmentsRequest struct for UpdateNamespaceAssignmentsRequest
type UpdateNamespaceAssignmentsRequest struct {
	Deletes []NamespaceAssignment `json:"deletes,omitempty"`
	Writes  []NamespaceAssignment `json:"writes,omitempty"`
}

// NewUpdateNamespaceAssignmentsRequest instantiates a new UpdateNamespaceAssignmentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNamespaceAssignmentsRequest() *UpdateNamespaceAssignmentsRequest {
	this := UpdateNamespaceAssignmentsRequest{}
	return &this
}

// NewUpdateNamespaceAssignmentsRequestWithDefaults instantiates a new UpdateNamespaceAssignmentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNamespaceAssignmentsRequestWithDefaults() *UpdateNamespaceAssignmentsRequest {
	this := UpdateNamespaceAssignmentsRequest{}
	return &this
}

// GetDeletes returns the Deletes field value if set, zero value otherwise.
func (o *UpdateNamespaceAssignmentsRequest) GetDeletes() []NamespaceAssignment {
	if o == nil || IsNil(o.Deletes) {
		var ret []NamespaceAssignment
		return ret
	}
	return o.Deletes
}

// GetDeletesOk returns a tuple with the Deletes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNamespaceAssignmentsRequest) GetDeletesOk() ([]NamespaceAssignment, bool) {
	if o == nil || IsNil(o.Deletes) {
		return nil, false
	}
	return o.Deletes, true
}

// HasDeletes returns a boolean if a field has been set.
func (o *UpdateNamespaceAssignmentsRequest) HasDeletes() bool {
	if o != nil && !IsNil(o.Deletes) {
		return true
	}

	return false
}

// SetDeletes gets a reference to the given []NamespaceAssignment and assigns it to the Deletes field.
func (o *UpdateNamespaceAssignmentsRequest) SetDeletes(v []NamespaceAssignment) {
	o.Deletes = v
}

// GetWrites returns the Writes field value if set, zero value otherwise.
func (o *UpdateNamespaceAssignmentsRequest) GetWrites() []NamespaceAssignment {
	if o == nil || IsNil(o.Writes) {
		var ret []NamespaceAssignment
		return ret
	}
	return o.Writes
}

// GetWritesOk returns a tuple with the Writes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNamespaceAssignmentsRequest) GetWritesOk() ([]NamespaceAssignment, bool) {
	if o == nil || IsNil(o.Writes) {
		return nil, false
	}
	return o.Writes, true
}

// HasWrites returns a boolean if a field has been set.
func (o *UpdateNamespaceAssignmentsRequest) HasWrites() bool {
	if o != nil && !IsNil(o.Writes) {
		return true
	}

	return false
}

// SetWrites gets a reference to the given []NamespaceAssignment and assigns it to the Writes field.
func (o *UpdateNamespaceAssignmentsRequest) SetWrites(v []NamespaceAssignment) {
	o.Writes = v
}

func (o UpdateNamespaceAssignmentsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNamespaceAssignmentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deletes) {
		toSerialize["deletes"] = o.Deletes
	}
	if !IsNil(o.Writes) {
		toSerialize["writes"] = o.Writes
	}
	return toSerialize, nil
}

type NullableUpdateNamespaceAssignmentsRequest struct {
	value *UpdateNamespaceAssignmentsRequest
	isSet bool
}

func (v NullableUpdateNamespaceAssignmentsRequest) Get() *UpdateNamespaceAssignmentsRequest {
	return v.value
}

func (v *NullableUpdateNamespaceAssignmentsRequest) Set(val *UpdateNamespaceAssignmentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNamespaceAssignmentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNamespaceAssignmentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNamespaceAssignmentsRequest(val *UpdateNamespaceAssignmentsRequest) *NullableUpdateNamespaceAssignmentsRequest {
	return &NullableUpdateNamespaceAssignmentsRequest{value: val, isSet: true}
}

func (v NullableUpdateNamespaceAssignmentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNamespaceAssignmentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
