/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GcsCredentialSystemIdentity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GcsCredentialSystemIdentity{}

// GcsCredentialSystemIdentity GCP System Identity  Use the service account that the application is running as. This can be a Compute Engine default service account or a user-assigned service account.
type GcsCredentialSystemIdentity struct {
	CredentialType string `json:"credential-type"`
}

type _GcsCredentialSystemIdentity GcsCredentialSystemIdentity

// NewGcsCredentialSystemIdentity instantiates a new GcsCredentialSystemIdentity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGcsCredentialSystemIdentity(credentialType string) *GcsCredentialSystemIdentity {
	this := GcsCredentialSystemIdentity{}
	this.CredentialType = credentialType
	return &this
}

// NewGcsCredentialSystemIdentityWithDefaults instantiates a new GcsCredentialSystemIdentity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGcsCredentialSystemIdentityWithDefaults() *GcsCredentialSystemIdentity {
	this := GcsCredentialSystemIdentity{}
	return &this
}

// GetCredentialType returns the CredentialType field value
func (o *GcsCredentialSystemIdentity) GetCredentialType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *GcsCredentialSystemIdentity) GetCredentialTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *GcsCredentialSystemIdentity) SetCredentialType(v string) {
	o.CredentialType = v
}

func (o GcsCredentialSystemIdentity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credential-type"] = o.CredentialType
	return toSerialize, nil
}

func (o *GcsCredentialSystemIdentity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credential-type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGcsCredentialSystemIdentity := _GcsCredentialSystemIdentity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGcsCredentialSystemIdentity)

	if err != nil {
		return err
	}

	*o = GcsCredentialSystemIdentity(varGcsCredentialSystemIdentity)

	return err
}

type NullableGcsCredentialSystemIdentity struct {
	value *GcsCredentialSystemIdentity
	isSet bool
}

func (v NullableGcsCredentialSystemIdentity) Get() *GcsCredentialSystemIdentity {
	return v.value
}

func (v *NullableGcsCredentialSystemIdentity) Set(val *GcsCredentialSystemIdentity) {
	v.value = val
	v.isSet = true
}

func (v NullableGcsCredentialSystemIdentity) IsSet() bool {
	return v.isSet
}

func (v *NullableGcsCredentialSystemIdentity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcsCredentialSystemIdentity(val *GcsCredentialSystemIdentity) *NullableGcsCredentialSystemIdentity {
	return &NullableGcsCredentialSystemIdentity{value: val, isSet: true}
}

func (v NullableGcsCredentialSystemIdentity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcsCredentialSystemIdentity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
