/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ControlTaskActionOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControlTaskActionOneOf1{}

// ControlTaskActionOneOf1 Cancel the task permanently. The task is not retried.
type ControlTaskActionOneOf1 struct {
	ActionType string `json:"action-type"`
}

type _ControlTaskActionOneOf1 ControlTaskActionOneOf1

// NewControlTaskActionOneOf1 instantiates a new ControlTaskActionOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControlTaskActionOneOf1(actionType string) *ControlTaskActionOneOf1 {
	this := ControlTaskActionOneOf1{}
	this.ActionType = actionType
	return &this
}

// NewControlTaskActionOneOf1WithDefaults instantiates a new ControlTaskActionOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControlTaskActionOneOf1WithDefaults() *ControlTaskActionOneOf1 {
	this := ControlTaskActionOneOf1{}
	return &this
}

// GetActionType returns the ActionType field value
func (o *ControlTaskActionOneOf1) GetActionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActionType
}

// GetActionTypeOk returns a tuple with the ActionType field value
// and a boolean to check if the value has been set.
func (o *ControlTaskActionOneOf1) GetActionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActionType, true
}

// SetActionType sets field value
func (o *ControlTaskActionOneOf1) SetActionType(v string) {
	o.ActionType = v
}

func (o ControlTaskActionOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControlTaskActionOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action-type"] = o.ActionType
	return toSerialize, nil
}

func (o *ControlTaskActionOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action-type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varControlTaskActionOneOf1 := _ControlTaskActionOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varControlTaskActionOneOf1)

	if err != nil {
		return err
	}

	*o = ControlTaskActionOneOf1(varControlTaskActionOneOf1)

	return err
}

type NullableControlTaskActionOneOf1 struct {
	value *ControlTaskActionOneOf1
	isSet bool
}

func (v NullableControlTaskActionOneOf1) Get() *ControlTaskActionOneOf1 {
	return v.value
}

func (v *NullableControlTaskActionOneOf1) Set(val *ControlTaskActionOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableControlTaskActionOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableControlTaskActionOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControlTaskActionOneOf1(val *ControlTaskActionOneOf1) *NullableControlTaskActionOneOf1 {
	return &NullableControlTaskActionOneOf1{value: val, isSet: true}
}

func (v NullableControlTaskActionOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControlTaskActionOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
