/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// WarehouseRelation the model 'WarehouseRelation'
type WarehouseRelation string

// List of WarehouseRelation
const (
	WAREHOUSERELATION_OWNERSHIP     WarehouseRelation = "ownership"
	WAREHOUSERELATION_PASS_GRANTS   WarehouseRelation = "pass_grants"
	WAREHOUSERELATION_MANAGE_GRANTS WarehouseRelation = "manage_grants"
	WAREHOUSERELATION_DESCRIBE      WarehouseRelation = "describe"
	WAREHOUSERELATION_SELECT        WarehouseRelation = "select"
	WAREHOUSERELATION_CREATE        WarehouseRelation = "create"
	WAREHOUSERELATION_MODIFY        WarehouseRelation = "modify"
)

// All allowed values of WarehouseRelation enum
var AllowedWarehouseRelationEnumValues = []WarehouseRelation{
	"ownership",
	"pass_grants",
	"manage_grants",
	"describe",
	"select",
	"create",
	"modify",
}

func (v *WarehouseRelation) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WarehouseRelation(value)
	for _, existing := range AllowedWarehouseRelationEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WarehouseRelation", value)
}

// NewWarehouseRelationFromValue returns a pointer to a valid WarehouseRelation
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWarehouseRelationFromValue(v string) (*WarehouseRelation, error) {
	ev := WarehouseRelation(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WarehouseRelation: valid values are %v", v, AllowedWarehouseRelationEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WarehouseRelation) IsValid() bool {
	for _, existing := range AllowedWarehouseRelationEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WarehouseRelation value
func (v WarehouseRelation) Ptr() *WarehouseRelation {
	return &v
}

type NullableWarehouseRelation struct {
	value *WarehouseRelation
	isSet bool
}

func (v NullableWarehouseRelation) Get() *WarehouseRelation {
	return v.value
}

func (v *NullableWarehouseRelation) Set(val *WarehouseRelation) {
	v.value = val
	v.isSet = true
}

func (v NullableWarehouseRelation) IsSet() bool {
	return v.isSet
}

func (v *NullableWarehouseRelation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWarehouseRelation(val *WarehouseRelation) *NullableWarehouseRelation {
	return &NullableWarehouseRelation{value: val, isSet: true}
}

func (v NullableWarehouseRelation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWarehouseRelation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
