/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NamespaceAssignmentManageGrantsRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NamespaceAssignmentManageGrantsRole{}

// NamespaceAssignmentManageGrantsRole struct for NamespaceAssignmentManageGrantsRole
type NamespaceAssignmentManageGrantsRole struct {
	// Id of the role
	Role string `json:"role"`
	Type string `json:"type"`
}

type _NamespaceAssignmentManageGrantsRole NamespaceAssignmentManageGrantsRole

// NewNamespaceAssignmentManageGrantsRole instantiates a new NamespaceAssignmentManageGrantsRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNamespaceAssignmentManageGrantsRole(role string, type_ string) *NamespaceAssignmentManageGrantsRole {
	this := NamespaceAssignmentManageGrantsRole{}
	this.Role = role
	this.Type = type_
	return &this
}

// NewNamespaceAssignmentManageGrantsRoleWithDefaults instantiates a new NamespaceAssignmentManageGrantsRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamespaceAssignmentManageGrantsRoleWithDefaults() *NamespaceAssignmentManageGrantsRole {
	this := NamespaceAssignmentManageGrantsRole{}
	return &this
}

// GetRole returns the Role field value
func (o *NamespaceAssignmentManageGrantsRole) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *NamespaceAssignmentManageGrantsRole) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *NamespaceAssignmentManageGrantsRole) SetRole(v string) {
	o.Role = v
}

// GetType returns the Type field value
func (o *NamespaceAssignmentManageGrantsRole) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NamespaceAssignmentManageGrantsRole) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NamespaceAssignmentManageGrantsRole) SetType(v string) {
	o.Type = v
}

func (o NamespaceAssignmentManageGrantsRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *NamespaceAssignmentManageGrantsRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNamespaceAssignmentManageGrantsRole := _NamespaceAssignmentManageGrantsRole{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNamespaceAssignmentManageGrantsRole)

	if err != nil {
		return err
	}

	*o = NamespaceAssignmentManageGrantsRole(varNamespaceAssignmentManageGrantsRole)

	return err
}

type NullableNamespaceAssignmentManageGrantsRole struct {
	value *NamespaceAssignmentManageGrantsRole
	isSet bool
}

func (v NullableNamespaceAssignmentManageGrantsRole) Get() *NamespaceAssignmentManageGrantsRole {
	return v.value
}

func (v *NullableNamespaceAssignmentManageGrantsRole) Set(val *NamespaceAssignmentManageGrantsRole) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceAssignmentManageGrantsRole) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceAssignmentManageGrantsRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceAssignmentManageGrantsRole(val *NamespaceAssignmentManageGrantsRole) *NullableNamespaceAssignmentManageGrantsRole {
	return &NullableNamespaceAssignmentManageGrantsRole{value: val, isSet: true}
}

func (v NullableNamespaceAssignmentManageGrantsRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceAssignmentManageGrantsRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
