/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// ViewAction the model 'ViewAction'
type ViewAction string

// List of ViewAction
const (
	VIEWACTION_DROP                ViewAction = "drop"
	VIEWACTION_COMMIT              ViewAction = "commit"
	VIEWACTION_GET_METADATA        ViewAction = "get_metadata"
	VIEWACTION_SELECT              ViewAction = "select"
	VIEWACTION_RENAME              ViewAction = "rename"
	VIEWACTION_READ_ASSIGNMENTS    ViewAction = "read_assignments"
	VIEWACTION_GRANT_PASS_GRANTS   ViewAction = "grant_pass_grants"
	VIEWACTION_GRANT_MANAGE_GRANTS ViewAction = "grant_manage_grants"
	VIEWACTION_GRANT_DESCRIBE      ViewAction = "grant_describe"
	VIEWACTION_GRANT_SELECT        ViewAction = "grant_select"
	VIEWACTION_GRANT_MODIFY        ViewAction = "grant_modify"
	VIEWACTION_CHANGE_OWNERSHIP    ViewAction = "change_ownership"
	VIEWACTION_GET_TASKS           ViewAction = "get_tasks"
	VIEWACTION_CONTROL_TASKS       ViewAction = "control_tasks"
	VIEWACTION_SET_PROTECTION      ViewAction = "set_protection"
)

// All allowed values of ViewAction enum
var AllowedViewActionEnumValues = []ViewAction{
	"drop",
	"commit",
	"get_metadata",
	"select",
	"rename",
	"read_assignments",
	"grant_pass_grants",
	"grant_manage_grants",
	"grant_describe",
	"grant_select",
	"grant_modify",
	"change_ownership",
	"get_tasks",
	"control_tasks",
	"set_protection",
}

func (v *ViewAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ViewAction(value)
	for _, existing := range AllowedViewActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ViewAction", value)
}

// NewViewActionFromValue returns a pointer to a valid ViewAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewViewActionFromValue(v string) (*ViewAction, error) {
	ev := ViewAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ViewAction: valid values are %v", v, AllowedViewActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ViewAction) IsValid() bool {
	for _, existing := range AllowedViewActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ViewAction value
func (v ViewAction) Ptr() *ViewAction {
	return &v
}

type NullableViewAction struct {
	value *ViewAction
	isSet bool
}

func (v NullableViewAction) Get() *ViewAction {
	return v.value
}

func (v *NullableViewAction) Set(val *ViewAction) {
	v.value = val
	v.isSet = true
}

func (v NullableViewAction) IsSet() bool {
	return v.isSet
}

func (v *NullableViewAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewAction(val *ViewAction) *NullableViewAction {
	return &NullableViewAction{value: val, isSet: true}
}

func (v NullableViewAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
