/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the EndpointStatistic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointStatistic{}

// EndpointStatistic struct for EndpointStatistic
type EndpointStatistic struct {
	// Number of requests to this endpoint for the current time-slice.
	Count int64 `json:"count"`
	// Timestamp at which the datapoint was created in the database.  This is the exact time at which the current endpoint-status-warehouse combination was called for the first time in the current time-slice.
	CreatedAt time.Time `json:"created-at"`
	// The route of the endpoint.  Format: `METHOD /path/to/endpoint`
	HttpRoute string `json:"http-route"`
	// The status code of the response.
	StatusCode int32 `json:"status-code"`
	// Timestamp at which the datapoint was last updated.  This is the exact time at which the current datapoint was last updated.
	UpdatedAt NullableTime `json:"updated-at,omitempty"`
	// The ID of the warehouse that handled the request.  Only present for requests that could be associated with a warehouse. Some management endpoints cannot be associated with a warehouse, e.g. warehouse creation or user management will not have a `warehouse-id`.
	WarehouseId NullableString `json:"warehouse-id,omitempty"`
	// The name of the warehouse that handled the request.  Only present for requests that could be associated with a warehouse. Some management endpoints cannot be associated with a warehouse, e.g. warehouse creation or user management will not have a `warehouse-id`
	WarehouseName NullableString `json:"warehouse-name,omitempty"`
}

type _EndpointStatistic EndpointStatistic

// NewEndpointStatistic instantiates a new EndpointStatistic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointStatistic(count int64, createdAt time.Time, httpRoute string, statusCode int32) *EndpointStatistic {
	this := EndpointStatistic{}
	this.Count = count
	this.CreatedAt = createdAt
	this.HttpRoute = httpRoute
	this.StatusCode = statusCode
	return &this
}

// NewEndpointStatisticWithDefaults instantiates a new EndpointStatistic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointStatisticWithDefaults() *EndpointStatistic {
	this := EndpointStatistic{}
	return &this
}

// GetCount returns the Count field value
func (o *EndpointStatistic) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *EndpointStatistic) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *EndpointStatistic) SetCount(v int64) {
	o.Count = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EndpointStatistic) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EndpointStatistic) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EndpointStatistic) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetHttpRoute returns the HttpRoute field value
func (o *EndpointStatistic) GetHttpRoute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HttpRoute
}

// GetHttpRouteOk returns a tuple with the HttpRoute field value
// and a boolean to check if the value has been set.
func (o *EndpointStatistic) GetHttpRouteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HttpRoute, true
}

// SetHttpRoute sets field value
func (o *EndpointStatistic) SetHttpRoute(v string) {
	o.HttpRoute = v
}

// GetStatusCode returns the StatusCode field value
func (o *EndpointStatistic) GetStatusCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *EndpointStatistic) GetStatusCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *EndpointStatistic) SetStatusCode(v int32) {
	o.StatusCode = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointStatistic) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointStatistic) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *EndpointStatistic) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *EndpointStatistic) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *EndpointStatistic) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *EndpointStatistic) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetWarehouseId returns the WarehouseId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointStatistic) GetWarehouseId() string {
	if o == nil || IsNil(o.WarehouseId.Get()) {
		var ret string
		return ret
	}
	return *o.WarehouseId.Get()
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointStatistic) GetWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WarehouseId.Get(), o.WarehouseId.IsSet()
}

// HasWarehouseId returns a boolean if a field has been set.
func (o *EndpointStatistic) HasWarehouseId() bool {
	if o != nil && o.WarehouseId.IsSet() {
		return true
	}

	return false
}

// SetWarehouseId gets a reference to the given NullableString and assigns it to the WarehouseId field.
func (o *EndpointStatistic) SetWarehouseId(v string) {
	o.WarehouseId.Set(&v)
}

// SetWarehouseIdNil sets the value for WarehouseId to be an explicit nil
func (o *EndpointStatistic) SetWarehouseIdNil() {
	o.WarehouseId.Set(nil)
}

// UnsetWarehouseId ensures that no value is present for WarehouseId, not even an explicit nil
func (o *EndpointStatistic) UnsetWarehouseId() {
	o.WarehouseId.Unset()
}

// GetWarehouseName returns the WarehouseName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointStatistic) GetWarehouseName() string {
	if o == nil || IsNil(o.WarehouseName.Get()) {
		var ret string
		return ret
	}
	return *o.WarehouseName.Get()
}

// GetWarehouseNameOk returns a tuple with the WarehouseName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointStatistic) GetWarehouseNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WarehouseName.Get(), o.WarehouseName.IsSet()
}

// HasWarehouseName returns a boolean if a field has been set.
func (o *EndpointStatistic) HasWarehouseName() bool {
	if o != nil && o.WarehouseName.IsSet() {
		return true
	}

	return false
}

// SetWarehouseName gets a reference to the given NullableString and assigns it to the WarehouseName field.
func (o *EndpointStatistic) SetWarehouseName(v string) {
	o.WarehouseName.Set(&v)
}

// SetWarehouseNameNil sets the value for WarehouseName to be an explicit nil
func (o *EndpointStatistic) SetWarehouseNameNil() {
	o.WarehouseName.Set(nil)
}

// UnsetWarehouseName ensures that no value is present for WarehouseName, not even an explicit nil
func (o *EndpointStatistic) UnsetWarehouseName() {
	o.WarehouseName.Unset()
}

func (o EndpointStatistic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointStatistic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["created-at"] = o.CreatedAt
	toSerialize["http-route"] = o.HttpRoute
	toSerialize["status-code"] = o.StatusCode
	if o.UpdatedAt.IsSet() {
		toSerialize["updated-at"] = o.UpdatedAt.Get()
	}
	if o.WarehouseId.IsSet() {
		toSerialize["warehouse-id"] = o.WarehouseId.Get()
	}
	if o.WarehouseName.IsSet() {
		toSerialize["warehouse-name"] = o.WarehouseName.Get()
	}
	return toSerialize, nil
}

func (o *EndpointStatistic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"created-at",
		"http-route",
		"status-code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointStatistic := _EndpointStatistic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointStatistic)

	if err != nil {
		return err
	}

	*o = EndpointStatistic(varEndpointStatistic)

	return err
}

type NullableEndpointStatistic struct {
	value *EndpointStatistic
	isSet bool
}

func (v NullableEndpointStatistic) Get() *EndpointStatistic {
	return v.value
}

func (v *NullableEndpointStatistic) Set(val *EndpointStatistic) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointStatistic) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointStatistic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointStatistic(val *EndpointStatistic) *NullableEndpointStatistic {
	return &NullableEndpointStatistic{value: val, isSet: true}
}

func (v NullableEndpointStatistic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointStatistic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
