/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"fmt"
)

// LakekeeperNamespaceAction - struct for LakekeeperNamespaceAction
type LakekeeperNamespaceAction struct {
	LakekeeperNamespaceActionOneOf   *LakekeeperNamespaceActionOneOf
	LakekeeperNamespaceActionOneOf1  *LakekeeperNamespaceActionOneOf1
	LakekeeperNamespaceActionOneOf10 *LakekeeperNamespaceActionOneOf10
	LakekeeperNamespaceActionOneOf11 *LakekeeperNamespaceActionOneOf11
	LakekeeperNamespaceActionOneOf2  *LakekeeperNamespaceActionOneOf2
	LakekeeperNamespaceActionOneOf3  *LakekeeperNamespaceActionOneOf3
	LakekeeperNamespaceActionOneOf4  *LakekeeperNamespaceActionOneOf4
	LakekeeperNamespaceActionOneOf5  *LakekeeperNamespaceActionOneOf5
	LakekeeperNamespaceActionOneOf6  *LakekeeperNamespaceActionOneOf6
	LakekeeperNamespaceActionOneOf7  *LakekeeperNamespaceActionOneOf7
	LakekeeperNamespaceActionOneOf8  *LakekeeperNamespaceActionOneOf8
	LakekeeperNamespaceActionOneOf9  *LakekeeperNamespaceActionOneOf9
}

// LakekeeperNamespaceActionOneOfAsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOfAsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf: v,
	}
}

// LakekeeperNamespaceActionOneOf1AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf1 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf1AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf1) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf1: v,
	}
}

// LakekeeperNamespaceActionOneOf10AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf10 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf10AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf10) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf10: v,
	}
}

// LakekeeperNamespaceActionOneOf11AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf11 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf11AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf11) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf11: v,
	}
}

// LakekeeperNamespaceActionOneOf2AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf2 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf2AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf2) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf2: v,
	}
}

// LakekeeperNamespaceActionOneOf3AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf3 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf3AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf3) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf3: v,
	}
}

// LakekeeperNamespaceActionOneOf4AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf4 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf4AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf4) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf4: v,
	}
}

// LakekeeperNamespaceActionOneOf5AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf5 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf5AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf5) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf5: v,
	}
}

// LakekeeperNamespaceActionOneOf6AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf6 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf6AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf6) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf6: v,
	}
}

// LakekeeperNamespaceActionOneOf7AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf7 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf7AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf7) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf7: v,
	}
}

// LakekeeperNamespaceActionOneOf8AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf8 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf8AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf8) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf8: v,
	}
}

// LakekeeperNamespaceActionOneOf9AsLakekeeperNamespaceAction is a convenience function that returns LakekeeperNamespaceActionOneOf9 wrapped in LakekeeperNamespaceAction
func LakekeeperNamespaceActionOneOf9AsLakekeeperNamespaceAction(v *LakekeeperNamespaceActionOneOf9) LakekeeperNamespaceAction {
	return LakekeeperNamespaceAction{
		LakekeeperNamespaceActionOneOf9: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *LakekeeperNamespaceAction) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into LakekeeperNamespaceActionOneOf
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf)
		if string(jsonLakekeeperNamespaceActionOneOf) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf1
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf1)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf1, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf1)
		if string(jsonLakekeeperNamespaceActionOneOf1) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf1 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf1 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf10
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf10)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf10, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf10)
		if string(jsonLakekeeperNamespaceActionOneOf10) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf10 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf10 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf11
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf11)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf11, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf11)
		if string(jsonLakekeeperNamespaceActionOneOf11) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf11 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf11 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf2
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf2)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf2, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf2)
		if string(jsonLakekeeperNamespaceActionOneOf2) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf2 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf2 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf3
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf3)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf3, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf3)
		if string(jsonLakekeeperNamespaceActionOneOf3) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf3 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf3 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf4
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf4)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf4, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf4)
		if string(jsonLakekeeperNamespaceActionOneOf4) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf4 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf4 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf5
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf5)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf5, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf5)
		if string(jsonLakekeeperNamespaceActionOneOf5) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf5 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf5 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf6
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf6)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf6, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf6)
		if string(jsonLakekeeperNamespaceActionOneOf6) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf6 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf6 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf7
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf7)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf7, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf7)
		if string(jsonLakekeeperNamespaceActionOneOf7) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf7 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf7 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf8
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf8)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf8, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf8)
		if string(jsonLakekeeperNamespaceActionOneOf8) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf8 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf8 = nil
	}

	// try to unmarshal data into LakekeeperNamespaceActionOneOf9
	err = json.Unmarshal(data, &dst.LakekeeperNamespaceActionOneOf9)
	if err == nil {
		jsonLakekeeperNamespaceActionOneOf9, _ := json.Marshal(dst.LakekeeperNamespaceActionOneOf9)
		if string(jsonLakekeeperNamespaceActionOneOf9) == "{}" { // empty struct
			dst.LakekeeperNamespaceActionOneOf9 = nil
		} else {
			match++
		}
	} else {
		dst.LakekeeperNamespaceActionOneOf9 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.LakekeeperNamespaceActionOneOf = nil
		dst.LakekeeperNamespaceActionOneOf1 = nil
		dst.LakekeeperNamespaceActionOneOf10 = nil
		dst.LakekeeperNamespaceActionOneOf11 = nil
		dst.LakekeeperNamespaceActionOneOf2 = nil
		dst.LakekeeperNamespaceActionOneOf3 = nil
		dst.LakekeeperNamespaceActionOneOf4 = nil
		dst.LakekeeperNamespaceActionOneOf5 = nil
		dst.LakekeeperNamespaceActionOneOf6 = nil
		dst.LakekeeperNamespaceActionOneOf7 = nil
		dst.LakekeeperNamespaceActionOneOf8 = nil
		dst.LakekeeperNamespaceActionOneOf9 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(LakekeeperNamespaceAction)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(LakekeeperNamespaceAction)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src LakekeeperNamespaceAction) MarshalJSON() ([]byte, error) {
	if src.LakekeeperNamespaceActionOneOf != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf)
	}

	if src.LakekeeperNamespaceActionOneOf1 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf1)
	}

	if src.LakekeeperNamespaceActionOneOf10 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf10)
	}

	if src.LakekeeperNamespaceActionOneOf11 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf11)
	}

	if src.LakekeeperNamespaceActionOneOf2 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf2)
	}

	if src.LakekeeperNamespaceActionOneOf3 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf3)
	}

	if src.LakekeeperNamespaceActionOneOf4 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf4)
	}

	if src.LakekeeperNamespaceActionOneOf5 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf5)
	}

	if src.LakekeeperNamespaceActionOneOf6 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf6)
	}

	if src.LakekeeperNamespaceActionOneOf7 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf7)
	}

	if src.LakekeeperNamespaceActionOneOf8 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf8)
	}

	if src.LakekeeperNamespaceActionOneOf9 != nil {
		return json.Marshal(&src.LakekeeperNamespaceActionOneOf9)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *LakekeeperNamespaceAction) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.LakekeeperNamespaceActionOneOf != nil {
		return obj.LakekeeperNamespaceActionOneOf
	}

	if obj.LakekeeperNamespaceActionOneOf1 != nil {
		return obj.LakekeeperNamespaceActionOneOf1
	}

	if obj.LakekeeperNamespaceActionOneOf10 != nil {
		return obj.LakekeeperNamespaceActionOneOf10
	}

	if obj.LakekeeperNamespaceActionOneOf11 != nil {
		return obj.LakekeeperNamespaceActionOneOf11
	}

	if obj.LakekeeperNamespaceActionOneOf2 != nil {
		return obj.LakekeeperNamespaceActionOneOf2
	}

	if obj.LakekeeperNamespaceActionOneOf3 != nil {
		return obj.LakekeeperNamespaceActionOneOf3
	}

	if obj.LakekeeperNamespaceActionOneOf4 != nil {
		return obj.LakekeeperNamespaceActionOneOf4
	}

	if obj.LakekeeperNamespaceActionOneOf5 != nil {
		return obj.LakekeeperNamespaceActionOneOf5
	}

	if obj.LakekeeperNamespaceActionOneOf6 != nil {
		return obj.LakekeeperNamespaceActionOneOf6
	}

	if obj.LakekeeperNamespaceActionOneOf7 != nil {
		return obj.LakekeeperNamespaceActionOneOf7
	}

	if obj.LakekeeperNamespaceActionOneOf8 != nil {
		return obj.LakekeeperNamespaceActionOneOf8
	}

	if obj.LakekeeperNamespaceActionOneOf9 != nil {
		return obj.LakekeeperNamespaceActionOneOf9
	}

	// all schemas are nil
	return nil
}

type NullableLakekeeperNamespaceAction struct {
	value *LakekeeperNamespaceAction
	isSet bool
}

func (v NullableLakekeeperNamespaceAction) Get() *LakekeeperNamespaceAction {
	return v.value
}

func (v *NullableLakekeeperNamespaceAction) Set(val *LakekeeperNamespaceAction) {
	v.value = val
	v.isSet = true
}

func (v NullableLakekeeperNamespaceAction) IsSet() bool {
	return v.isSet
}

func (v *NullableLakekeeperNamespaceAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLakekeeperNamespaceAction(val *LakekeeperNamespaceAction) *NullableLakekeeperNamespaceAction {
	return &NullableLakekeeperNamespaceAction{value: val, isSet: true}
}

func (v NullableLakekeeperNamespaceAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLakekeeperNamespaceAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
