/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the TimeWindowSelectorOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimeWindowSelectorOneOf{}

// TimeWindowSelectorOneOf struct for TimeWindowSelectorOneOf
type TimeWindowSelectorOneOf struct {
	// End timestamp of the time window Specify
	End time.Time `json:"end"`
	// Duration/span of the time window  The returned statistics will be for the time window from `end` - `interval` to `end`. Specify a ISO8601 duration string, e.g. `PT1H` for 1 hour, `P1D` for 1 day.
	Interval string `json:"interval"`
	Type     string `json:"type"`
}

type _TimeWindowSelectorOneOf TimeWindowSelectorOneOf

// NewTimeWindowSelectorOneOf instantiates a new TimeWindowSelectorOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeWindowSelectorOneOf(end time.Time, interval string, type_ string) *TimeWindowSelectorOneOf {
	this := TimeWindowSelectorOneOf{}
	this.End = end
	this.Interval = interval
	this.Type = type_
	return &this
}

// NewTimeWindowSelectorOneOfWithDefaults instantiates a new TimeWindowSelectorOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeWindowSelectorOneOfWithDefaults() *TimeWindowSelectorOneOf {
	this := TimeWindowSelectorOneOf{}
	return &this
}

// GetEnd returns the End field value
func (o *TimeWindowSelectorOneOf) GetEnd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *TimeWindowSelectorOneOf) GetEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *TimeWindowSelectorOneOf) SetEnd(v time.Time) {
	o.End = v
}

// GetInterval returns the Interval field value
func (o *TimeWindowSelectorOneOf) GetInterval() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value
// and a boolean to check if the value has been set.
func (o *TimeWindowSelectorOneOf) GetIntervalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interval, true
}

// SetInterval sets field value
func (o *TimeWindowSelectorOneOf) SetInterval(v string) {
	o.Interval = v
}

// GetType returns the Type field value
func (o *TimeWindowSelectorOneOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TimeWindowSelectorOneOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TimeWindowSelectorOneOf) SetType(v string) {
	o.Type = v
}

func (o TimeWindowSelectorOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimeWindowSelectorOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["end"] = o.End
	toSerialize["interval"] = o.Interval
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TimeWindowSelectorOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"end",
		"interval",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimeWindowSelectorOneOf := _TimeWindowSelectorOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimeWindowSelectorOneOf)

	if err != nil {
		return err
	}

	*o = TimeWindowSelectorOneOf(varTimeWindowSelectorOneOf)

	return err
}

type NullableTimeWindowSelectorOneOf struct {
	value *TimeWindowSelectorOneOf
	isSet bool
}

func (v NullableTimeWindowSelectorOneOf) Get() *TimeWindowSelectorOneOf {
	return v.value
}

func (v *NullableTimeWindowSelectorOneOf) Set(val *TimeWindowSelectorOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeWindowSelectorOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeWindowSelectorOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeWindowSelectorOneOf(val *TimeWindowSelectorOneOf) *NullableTimeWindowSelectorOneOf {
	return &NullableTimeWindowSelectorOneOf{value: val, isSet: true}
}

func (v NullableTimeWindowSelectorOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeWindowSelectorOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
