/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"encoding/json"
	"time"
)

// checks if the ListTasksRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTasksRequest{}

// ListTasksRequest struct for ListTasksRequest
type ListTasksRequest struct {
	// Filter tasks created after this timestamp
	CreatedAfter NullableTime `json:"created-after,omitempty"`
	// Filter tasks created before this timestamp
	CreatedBefore NullableTime `json:"created-before,omitempty"`
	// Filter by specific entity
	Entities []WarehouseTaskEntityFilter `json:"entities,omitempty"`
	// Number of results per page
	PageSize NullableInt64 `json:"page-size,omitempty"`
	// Next page token, re-use the same request as for the original request, but set this to the `next_page_token` from the previous response. Stop iterating when no more items are returned in a page.
	PageToken NullableString `json:"page-token,omitempty"`
	// Filter by one or more queue names
	QueueName []string `json:"queue-name,omitempty"`
	// Filter by task status
	Status []TaskStatus `json:"status,omitempty"`
}

// NewListTasksRequest instantiates a new ListTasksRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTasksRequest() *ListTasksRequest {
	this := ListTasksRequest{}
	return &this
}

// NewListTasksRequestWithDefaults instantiates a new ListTasksRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTasksRequestWithDefaults() *ListTasksRequest {
	this := ListTasksRequest{}
	return &this
}

// GetCreatedAfter returns the CreatedAfter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListTasksRequest) GetCreatedAfter() time.Time {
	if o == nil || IsNil(o.CreatedAfter.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAfter.Get()
}

// GetCreatedAfterOk returns a tuple with the CreatedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListTasksRequest) GetCreatedAfterOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAfter.Get(), o.CreatedAfter.IsSet()
}

// HasCreatedAfter returns a boolean if a field has been set.
func (o *ListTasksRequest) HasCreatedAfter() bool {
	if o != nil && o.CreatedAfter.IsSet() {
		return true
	}

	return false
}

// SetCreatedAfter gets a reference to the given NullableTime and assigns it to the CreatedAfter field.
func (o *ListTasksRequest) SetCreatedAfter(v time.Time) {
	o.CreatedAfter.Set(&v)
}

// SetCreatedAfterNil sets the value for CreatedAfter to be an explicit nil
func (o *ListTasksRequest) SetCreatedAfterNil() {
	o.CreatedAfter.Set(nil)
}

// UnsetCreatedAfter ensures that no value is present for CreatedAfter, not even an explicit nil
func (o *ListTasksRequest) UnsetCreatedAfter() {
	o.CreatedAfter.Unset()
}

// GetCreatedBefore returns the CreatedBefore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListTasksRequest) GetCreatedBefore() time.Time {
	if o == nil || IsNil(o.CreatedBefore.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedBefore.Get()
}

// GetCreatedBeforeOk returns a tuple with the CreatedBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListTasksRequest) GetCreatedBeforeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBefore.Get(), o.CreatedBefore.IsSet()
}

// HasCreatedBefore returns a boolean if a field has been set.
func (o *ListTasksRequest) HasCreatedBefore() bool {
	if o != nil && o.CreatedBefore.IsSet() {
		return true
	}

	return false
}

// SetCreatedBefore gets a reference to the given NullableTime and assigns it to the CreatedBefore field.
func (o *ListTasksRequest) SetCreatedBefore(v time.Time) {
	o.CreatedBefore.Set(&v)
}

// SetCreatedBeforeNil sets the value for CreatedBefore to be an explicit nil
func (o *ListTasksRequest) SetCreatedBeforeNil() {
	o.CreatedBefore.Set(nil)
}

// UnsetCreatedBefore ensures that no value is present for CreatedBefore, not even an explicit nil
func (o *ListTasksRequest) UnsetCreatedBefore() {
	o.CreatedBefore.Unset()
}

// GetEntities returns the Entities field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListTasksRequest) GetEntities() []WarehouseTaskEntityFilter {
	if o == nil {
		var ret []WarehouseTaskEntityFilter
		return ret
	}
	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListTasksRequest) GetEntitiesOk() ([]WarehouseTaskEntityFilter, bool) {
	if o == nil || IsNil(o.Entities) {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *ListTasksRequest) HasEntities() bool {
	if o != nil && !IsNil(o.Entities) {
		return true
	}

	return false
}

// SetEntities gets a reference to the given []WarehouseTaskEntityFilter and assigns it to the Entities field.
func (o *ListTasksRequest) SetEntities(v []WarehouseTaskEntityFilter) {
	o.Entities = v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListTasksRequest) GetPageSize() int64 {
	if o == nil || IsNil(o.PageSize.Get()) {
		var ret int64
		return ret
	}
	return *o.PageSize.Get()
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListTasksRequest) GetPageSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PageSize.Get(), o.PageSize.IsSet()
}

// HasPageSize returns a boolean if a field has been set.
func (o *ListTasksRequest) HasPageSize() bool {
	if o != nil && o.PageSize.IsSet() {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given NullableInt64 and assigns it to the PageSize field.
func (o *ListTasksRequest) SetPageSize(v int64) {
	o.PageSize.Set(&v)
}

// SetPageSizeNil sets the value for PageSize to be an explicit nil
func (o *ListTasksRequest) SetPageSizeNil() {
	o.PageSize.Set(nil)
}

// UnsetPageSize ensures that no value is present for PageSize, not even an explicit nil
func (o *ListTasksRequest) UnsetPageSize() {
	o.PageSize.Unset()
}

// GetPageToken returns the PageToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListTasksRequest) GetPageToken() string {
	if o == nil || IsNil(o.PageToken.Get()) {
		var ret string
		return ret
	}
	return *o.PageToken.Get()
}

// GetPageTokenOk returns a tuple with the PageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListTasksRequest) GetPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PageToken.Get(), o.PageToken.IsSet()
}

// HasPageToken returns a boolean if a field has been set.
func (o *ListTasksRequest) HasPageToken() bool {
	if o != nil && o.PageToken.IsSet() {
		return true
	}

	return false
}

// SetPageToken gets a reference to the given NullableString and assigns it to the PageToken field.
func (o *ListTasksRequest) SetPageToken(v string) {
	o.PageToken.Set(&v)
}

// SetPageTokenNil sets the value for PageToken to be an explicit nil
func (o *ListTasksRequest) SetPageTokenNil() {
	o.PageToken.Set(nil)
}

// UnsetPageToken ensures that no value is present for PageToken, not even an explicit nil
func (o *ListTasksRequest) UnsetPageToken() {
	o.PageToken.Unset()
}

// GetQueueName returns the QueueName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListTasksRequest) GetQueueName() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.QueueName
}

// GetQueueNameOk returns a tuple with the QueueName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListTasksRequest) GetQueueNameOk() ([]string, bool) {
	if o == nil || IsNil(o.QueueName) {
		return nil, false
	}
	return o.QueueName, true
}

// HasQueueName returns a boolean if a field has been set.
func (o *ListTasksRequest) HasQueueName() bool {
	if o != nil && !IsNil(o.QueueName) {
		return true
	}

	return false
}

// SetQueueName gets a reference to the given []string and assigns it to the QueueName field.
func (o *ListTasksRequest) SetQueueName(v []string) {
	o.QueueName = v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListTasksRequest) GetStatus() []TaskStatus {
	if o == nil {
		var ret []TaskStatus
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListTasksRequest) GetStatusOk() ([]TaskStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListTasksRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given []TaskStatus and assigns it to the Status field.
func (o *ListTasksRequest) SetStatus(v []TaskStatus) {
	o.Status = v
}

func (o ListTasksRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTasksRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAfter.IsSet() {
		toSerialize["created-after"] = o.CreatedAfter.Get()
	}
	if o.CreatedBefore.IsSet() {
		toSerialize["created-before"] = o.CreatedBefore.Get()
	}
	if o.Entities != nil {
		toSerialize["entities"] = o.Entities
	}
	if o.PageSize.IsSet() {
		toSerialize["page-size"] = o.PageSize.Get()
	}
	if o.PageToken.IsSet() {
		toSerialize["page-token"] = o.PageToken.Get()
	}
	if o.QueueName != nil {
		toSerialize["queue-name"] = o.QueueName
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableListTasksRequest struct {
	value *ListTasksRequest
	isSet bool
}

func (v NullableListTasksRequest) Get() *ListTasksRequest {
	return v.value
}

func (v *NullableListTasksRequest) Set(val *ListTasksRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListTasksRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListTasksRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTasksRequest(val *ListTasksRequest) *NullableListTasksRequest {
	return &NullableListTasksRequest{value: val, isSet: true}
}

func (v NullableListTasksRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTasksRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
