/*
Lakekeeper Management API

Lakekeeper is a rust-native Apache Iceberg REST Catalog implementation. The Management API provides endpoints to manage the server, projects, warehouses, users, and roles. If Authorization is enabled, permissions can also be managed. An interactive Swagger-UI for the specific Lakekeeper Version and configuration running is available at `/swagger-ui/#/` of Lakekeeper (by default [http://localhost:8181/swagger-ui/#/](http://localhost:8181/swagger-ui/#/)).

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package managementv1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CatalogActionCheckOperationOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogActionCheckOperationOneOf2{}

// CatalogActionCheckOperationOneOf2 struct for CatalogActionCheckOperationOneOf2
type CatalogActionCheckOperationOneOf2 struct {
	Warehouse CatalogActionCheckOperationOneOf2Warehouse `json:"warehouse"`
}

type _CatalogActionCheckOperationOneOf2 CatalogActionCheckOperationOneOf2

// NewCatalogActionCheckOperationOneOf2 instantiates a new CatalogActionCheckOperationOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogActionCheckOperationOneOf2(warehouse CatalogActionCheckOperationOneOf2Warehouse) *CatalogActionCheckOperationOneOf2 {
	this := CatalogActionCheckOperationOneOf2{}
	this.Warehouse = warehouse
	return &this
}

// NewCatalogActionCheckOperationOneOf2WithDefaults instantiates a new CatalogActionCheckOperationOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogActionCheckOperationOneOf2WithDefaults() *CatalogActionCheckOperationOneOf2 {
	this := CatalogActionCheckOperationOneOf2{}
	return &this
}

// GetWarehouse returns the Warehouse field value
func (o *CatalogActionCheckOperationOneOf2) GetWarehouse() CatalogActionCheckOperationOneOf2Warehouse {
	if o == nil {
		var ret CatalogActionCheckOperationOneOf2Warehouse
		return ret
	}

	return o.Warehouse
}

// GetWarehouseOk returns a tuple with the Warehouse field value
// and a boolean to check if the value has been set.
func (o *CatalogActionCheckOperationOneOf2) GetWarehouseOk() (*CatalogActionCheckOperationOneOf2Warehouse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Warehouse, true
}

// SetWarehouse sets field value
func (o *CatalogActionCheckOperationOneOf2) SetWarehouse(v CatalogActionCheckOperationOneOf2Warehouse) {
	o.Warehouse = v
}

func (o CatalogActionCheckOperationOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogActionCheckOperationOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["warehouse"] = o.Warehouse
	return toSerialize, nil
}

func (o *CatalogActionCheckOperationOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"warehouse",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogActionCheckOperationOneOf2 := _CatalogActionCheckOperationOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogActionCheckOperationOneOf2)

	if err != nil {
		return err
	}

	*o = CatalogActionCheckOperationOneOf2(varCatalogActionCheckOperationOneOf2)

	return err
}

type NullableCatalogActionCheckOperationOneOf2 struct {
	value *CatalogActionCheckOperationOneOf2
	isSet bool
}

func (v NullableCatalogActionCheckOperationOneOf2) Get() *CatalogActionCheckOperationOneOf2 {
	return v.value
}

func (v *NullableCatalogActionCheckOperationOneOf2) Set(val *CatalogActionCheckOperationOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogActionCheckOperationOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogActionCheckOperationOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogActionCheckOperationOneOf2(val *CatalogActionCheckOperationOneOf2) *NullableCatalogActionCheckOperationOneOf2 {
	return &NullableCatalogActionCheckOperationOneOf2{value: val, isSet: true}
}

func (v NullableCatalogActionCheckOperationOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogActionCheckOperationOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
